// Generated by scripts/generate-sdk-types.py. Do not edit by hand.

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type JsonObject = { [key: string]: JsonValue };

export interface AdmissionReceipt {
  version: string;
  admissionId: string;
  operationId: string;
  status: "accepted" | "rejected";
  resourceId: string;
  requestHash: string;
  idempotencyKeyHash: string | null;
  replayed: boolean;
  admittedAtUtc: string;
  statusUri: string;
  resultUri: string | null;
  failureClass: string | null;
  error: string | null;
}

export interface CanonicalMigration {
  namespace: string;
  id: string;
  checksum: string;
  description?: string | null;
}

export type CanonicalMigrationReceipt = CanonicalMigration & JsonObject;

export interface CanonicalPreflightReport {
  store: string;
  provider: string;
  authenticationMode: string;
  tenantPoliciesEnforced: boolean;
  identityPolicyCount: number;
  migrationReceiptCount: number;
  rateLimitPermitLimit: number;
  rateLimitWindowSeconds: number;
  requiredOperations: Array<string>;
  dataPlaneProbe?: CanonicalDataPlanePreflightResult | null;
}

export interface CanonicalDataPlanePreflightResult {
  profile: "vyral.canonical.data-plane-preflight.v1";
  ready: boolean;
  status: "passed" | "failed";
  scope: "isolated_ephemeral_tenants";
  checkedAtUtc: string;
  durationMs: number;
  archiveChunkCount: number;
  backupRestoreVerified: boolean;
  tenantIsolationVerified: boolean;
  cleanupVerified: boolean;
  checks: Array<CanonicalDataPlanePreflightCheck>;
}

export interface CanonicalDataPlanePreflightCheck {
  id: string;
  status: "passed" | "failed";
  message: string;
}

export interface CanonicalDocument {
  tenantId: string;
  documentType: string;
  id: string;
  schemaVersion: string;
  data?: JsonValue;
  indexes: JsonObject;
  revision: number;
  etag: string;
  deleted: boolean;
  createdAtUtc: string;
  updatedAtUtc: string;
}

export interface CanonicalWritePrecondition {
  expectedRevision?: number | null;
  mustNotExist?: boolean;
  mustExist?: boolean;
}

export interface CanonicalMutation {
  operation: "upsert" | "delete";
  document?: CanonicalDocument | null;
  documentType?: string | null;
  id?: string | null;
  precondition?: CanonicalWritePrecondition | null;
}

export interface CanonicalFenceMutation {
  operation: "claim" | "release";
  name: string;
  value: string;
  ownerDocumentType: string;
  ownerDocumentId: string;
}

export interface CanonicalFence {
  tenantId: string;
  name: string;
  value: string;
  ownerDocumentType: string;
  ownerDocumentId: string;
  createdAtUtc: string;
  updatedAtUtc: string;
}

export interface CanonicalOutboxWrite {
  id?: string | null;
  topic: string;
  key: string;
  payload?: JsonValue;
  headers: JsonObject;
  notBeforeUtc?: string | null;
  maxDeliveryAttempts?: number | null;
}

export type CanonicalOutboxEvent = CanonicalOutboxWrite & JsonObject;

export interface CanonicalTransactionRequest {
  tenantId: string;
  idempotencyKey: string;
  correlationId?: string | null;
  actor?: string | null;
  mutations: Array<CanonicalMutation>;
  fences: Array<CanonicalFenceMutation>;
  outbox: Array<CanonicalOutboxWrite>;
}

export interface CanonicalTransactionResult {
  transactionId: string;
  tenantId: string;
  idempotencyKey: string;
  correlationId?: string | null;
  actor?: string | null;
  replayed: boolean;
  committedAtUtc: string;
  documents: Array<CanonicalDocument>;
  outbox: Array<CanonicalOutboxEvent>;
}

export interface CanonicalDocumentQuery {
  tenantId: string;
  documentType?: string | null;
  indexes: JsonObject;
  indexRange?: CanonicalDocumentIndexRange | null;
  orderByIndex?: string | null;
  orderDirection?: "ascending" | "descending";
  includeDeleted?: boolean;
  limit?: number | null;
  continuationToken?: string | null;
}

export interface CanonicalDocumentIndexRange {
  name: string;
  greaterThanOrEqual?: string | null;
  lessThanOrEqual?: string | null;
}

export interface CanonicalDocumentQueryResult {
  items: Array<CanonicalDocument>;
  continuationToken?: string | null;
}

export interface CanonicalDocumentReadRequest {
  tenantId: string;
  documentType: string;
  id: string;
  includeDeleted?: boolean;
}

export interface CanonicalDocumentRevisionQuery {
  tenantId: string;
  documentType: string;
  id: string;
  limit?: number | null;
}

export interface CanonicalDocumentRevision {
  tenantId: string;
  documentType: string;
  id: string;
  revision: number;
  transactionId: string;
  operation: "upsert" | "delete";
  document: CanonicalDocument;
  recordedAtUtc: string;
}

export interface CanonicalOutboxLeaseRequest {
  tenantId: string;
  consumerId: string;
  maxItems?: number;
  leaseSeconds?: number;
}

export interface CanonicalOutboxLease {
  event: CanonicalOutboxEvent;
  leaseToken: string;
  expiresAtUtc: string;
}

export interface CanonicalOutboxLeaseRenewalRequest {
  tenantId: string;
  eventId: string;
  leaseToken: string;
  leaseSeconds?: number;
}

export interface CanonicalOutboxLeaseRenewal {
  expiresAtUtc: string;
}

export interface CanonicalOutboxAcknowledgement {
  leaseToken: string;
}

export interface CanonicalOutboxNackRequest {
  tenantId: string;
  eventId: string;
  leaseToken: string;
  notBeforeUtc?: string | null;
  retryAfterSeconds?: number | null;
  error?: string | null;
}

export interface CanonicalOutboxQuery {
  tenantId: string;
  state?: "ready" | "leased" | "scheduled" | "delivered" | "dead-letter" | null;
  topic?: string | null;
  limit?: number | null;
  continuationToken?: string | null;
}

export interface CanonicalOutboxQueryResult {
  items: Array<CanonicalOutboxEvent>;
  continuationToken?: string | null;
}

export interface CanonicalOutboxReplayRequest {
  tenantId: string;
  eventId: string;
  resetDeliveryCount?: boolean;
}

export interface CanonicalTransactionReceipt {
  transactionId: string;
  tenantId: string;
  idempotencyKey: string;
  requestHash: string;
  result: CanonicalTransactionResult;
  committedAtUtc: string;
}

export interface CanonicalTenantSnapshot {
  tenantId: string;
  documents: Array<CanonicalDocument>;
  revisions: Array<CanonicalDocumentRevision>;
  fences: Array<CanonicalFence>;
  outbox: Array<CanonicalOutboxEvent>;
  transactions: Array<CanonicalTransactionReceipt>;
  exportedAtUtc: string;
  contentHash: string;
}

export interface CanonicalRestoreRequest {
  snapshot: CanonicalTenantSnapshot;
  expectedContentHash?: string | null;
}

export interface RecordCollectionPolicy {
  name: string;
  partitionKeyPath?: string;
  vectorPolicies?: Array<VectorFieldPolicy>;
  indexedMetadata?: Array<string>;
}

export interface CollectionInspectionResult {
  collection?: string;
  generatedAt?: string;
  policy?: RecordCollectionPolicy;
  recordCount?: number;
  partitionCount?: number;
  typeCounts?: JsonObject;
  embeddingProviderCounts?: JsonObject;
  embeddingModelCounts?: JsonObject;
  rag?: RagCollectionInspection;
  vectors?: Array<VectorFieldInspection>;
  extraVectorFieldCounts?: JsonObject;
  anomalyCount?: number;
  returnedAnomalyCount?: number;
  anomalies?: Array<CollectionInspectionAnomaly>;
}

export interface RagCollectionInspection {
  documentCount?: number;
  chunkCount?: number;
  manifestCount?: number;
  chunkRecordsWithDocumentIdCount?: number;
  chunkRecordsWithVectorCount?: number;
  chunkRecordsWithoutVectorCount?: number;
}

export interface VectorFieldInspection {
  field?: string;
  path?: string;
  policyDimensions?: number;
  datatype?: string;
  distanceFunction?: string;
  indexType?: string;
  recordCount?: number;
  presentCount?: number;
  missingCount?: number;
  notApplicableCount?: number;
  emptyCount?: number;
  dimensionMismatchCount?: number;
  policyCoverage?: number;
  modelCounts?: JsonObject;
  sourceFieldCounts?: JsonObject;
}

export interface CollectionInspectionAnomaly {
  kind?: string;
  id?: string;
  partitionKey?: string;
  type?: string | null;
  field?: string | null;
  message?: string;
  details?: JsonObject;
}

export interface VectorFieldPolicy {
  name: string;
  path: string;
  dimensions: number;
  datatype?: string;
  distanceFunction?: "cosine" | "dotProduct" | "euclidean";
  indexType?: string;
}

export interface VyralRecord {
  id: string;
  partitionKey: string;
  type?: string;
  schemaVersion?: string | null;
  metadata?: JsonObject | null;
  content?: JsonObject | null;
  sources?: Array<VyralSourceReference> | null;
  vectors?: JsonObject | null;
  embedding?: JsonObject | null;
  etag?: string | null;
  revision?: number | null;
  createdAt?: string | null;
  updatedAt?: string | null;
  [key: string]: unknown;
}

export interface VyralSourceReference {
  id?: string;
  kind?: string;
  uri?: string;
  label?: string | null;
  span?: JsonObject | null;
}

export interface VyralVector {
  values: Array<number>;
  dimensions: number;
  model?: string | null;
  datatype?: string;
  distanceFunction?: string;
  generatedAt?: string | null;
  sourceField?: string | null;
}

export interface QueryEnvelope {
  partitionKeys?: Array<string> | null;
  filter?: FilterNode;
  vector?: VectorSearchOptions;
  lexical?: LexicalSearchOptions;
  orderBy?: Array<OrderExpression> | null;
  limit?: number | null;
  continuationToken?: string | null;
}

export interface FilterNode {
  path?: string | null;
  op?: "eq" | "neq" | "in" | "gt" | "gte" | "lt" | "lte" | "exists" | "contains" | "startsWith" | null;
  value?: JsonValue;
  combine?: "all" | "any" | null | null;
  children?: Array<FilterNode> | null;
}

export interface VectorSearchOptions {
  field: string;
  value: Array<number>;
  top?: number;
  minScore?: number | null;
}

export interface LexicalSearchOptions {
  query?: string;
  fields?: Array<string> | null;
  top?: number;
  scanLimit?: number | null;
  minScore?: number | null;
  scoring?: "bm25" | "coverage";
  matchMode?: "any" | "all";
  fieldBoosts?: JsonObject | null;
  bm25K1?: number;
  bm25B?: number;
  phraseBoost?: number;
  exactBoost?: number;
  metadataBoost?: number;
  prefixMatching?: boolean;
  prefixMinChars?: number;
  requiredPhraseGroups?: Array<Array<string>> | null;
}

export interface HybridSearchOptions {
  vectorWeight?: number;
  lexicalWeight?: number;
  candidateMultiplier?: number;
  vectorCandidateLimit?: number | null;
  lexicalCandidateLimit?: number | null;
  fusion?: "weighted" | "rrf";
  rrfK?: number;
}

export interface RerankOptions {
  enabled?: boolean;
  provider?: string | null;
  mode?: string;
  candidateLimit?: number | null;
  maxCandidateChars?: number;
  contentField?: string | null;
  rerankScoreWeight?: number;
  originalScoreWeight?: number;
  timeoutSeconds?: number | null;
  maxOutputBytes?: number | null;
  fallbackOnFailure?: boolean;
}

export interface OrderExpression {
  path: string;
  direction?: "asc" | "desc";
}

export interface ArtifactRecordIngestManifest {
  collection: string;
  record: VyralRecord;
  artifact: ArtifactRecordDescriptor;
  externalContext?: ExternalContextProof;
}

export interface ArtifactRecordDescriptor {
  container: string;
  key: string;
  contentType?: string | null;
  metadata?: JsonObject | null;
}

export interface ExternalContextProof {
  token: string;
}

export interface ArtifactRecordIngestReceipt {
  accepted: boolean;
  collection: string;
  recordId: string;
  partitionKey: string;
  recordUri: string;
  artifact: ObjectInfo;
  externalContextVerified: boolean;
  receivedAt: string;
}

export interface RecordQueryResult {
  items: Array<VyralRecord>;
  continuationToken?: string | null;
}

export interface RecordSearchResult {
  items: Array<VyralRecordMatch>;
  continuationToken?: string | null;
}

export interface VyralGraphScope {
  graphId?: string;
  namespace?: string;
  collection?: string;
  tenantId?: string;
  partitionKey?: string;
  [key: string]: unknown;
}

export interface VyralGraphSourceSpan {
  sourceRef?: string;
  charStart?: number | null;
  charEnd?: number | null;
  unit?: string;
  locator?: string | null;
  textHash?: string | null;
  metadata?: JsonObject | null;
  [key: string]: unknown;
}

export interface VyralGraphNode {
  id: string;
  type: string;
  label?: string | null;
  properties?: JsonObject | null;
  sourceSpans?: Array<VyralGraphSourceSpan>;
  assertionIds?: Array<string>;
  createdAt?: string | null;
  updatedAt?: string | null;
  [key: string]: unknown;
}

export interface VyralGraphEdge {
  id: string;
  sourceId: string;
  targetId: string;
  predicate: string;
  label?: string | null;
  properties?: JsonObject | null;
  sourceSpans?: Array<VyralGraphSourceSpan>;
  assertionIds?: Array<string>;
  createdAt?: string | null;
  updatedAt?: string | null;
  [key: string]: unknown;
}

export interface VyralGraphAssertion {
  id: string;
  subjectId: string;
  subjectKind: string;
  status?: string;
  method?: string;
  actor?: string;
  confidence?: number | null;
  sourceSpans?: Array<VyralGraphSourceSpan>;
  properties?: JsonObject | null;
  createdAt?: string | null;
  [key: string]: unknown;
}

export interface VyralGraphReviewEvent {
  id: string;
  subjectId: string;
  subjectKind: string;
  status: string;
  reviewer: string;
  notes?: string | null;
  properties?: JsonObject | null;
  createdAt?: string | null;
  [key: string]: unknown;
}

export interface VyralGraphTraversalProfile {
  id?: string;
  direction?: "outgoing" | "incoming" | "both";
  maxDepth?: number;
  predicates?: Array<string>;
  nodeTypes?: Array<string>;
  limit?: number;
  edgeLimit?: number;
  includeStart?: boolean;
  reviewStatuses?: Array<string>;
  assertionStatuses?: Array<string>;
  requireSourceGrounding?: boolean;
  minScore?: number | null;
  includePathExplanations?: boolean;
  [key: string]: unknown;
}

export interface VyralGraphProjection {
  id: string;
  profile?: VyralGraphTraversalProfile;
  startNodeIds?: Array<string>;
  nodes?: Array<VyralGraphNode>;
  edges?: Array<VyralGraphEdge>;
  diagnostics?: JsonObject | null;
  createdAt?: string | null;
  [key: string]: unknown;
}

export interface VyralGraphEnvelope {
  schema?: string;
  scope?: VyralGraphScope;
  metadata?: JsonObject | null;
  nodes?: Array<VyralGraphNode>;
  edges?: Array<VyralGraphEdge>;
  assertions?: Array<VyralGraphAssertion>;
  reviews?: Array<VyralGraphReviewEvent>;
  projections?: Array<VyralGraphProjection>;
}

export interface VyralGraphProviderShape {
  providerId?: string;
  kind?: string;
  graphIdField?: string;
  nodeIdField?: string;
  edgeIdField?: string;
  sourceField?: string;
  targetField?: string;
  partitionField?: string;
  tenantField?: string;
  capabilities?: Array<string>;
  limitations?: Array<string>;
  metadata?: JsonObject | null;
  id?: string;
  [key: string]: unknown;
}

export interface VyralGraphCollectionImportRequest {
  envelope: VyralGraphEnvelope;
  createCollectionIfMissing?: boolean;
  replaceExisting?: boolean;
  continueOnError?: boolean;
  allowNonGraphPolicy?: boolean;
}

export interface VyralGraphCollectionImportResult {
  collection?: string;
  graphId?: string;
  partitionKey?: string;
  policyStatus?: string;
  nodeCount?: number;
  edgeCount?: number;
  assertionCount?: number;
  reviewCount?: number;
  projectionCount?: number;
  recordCount?: number;
  records?: RecordBatchUpsertResult;
}

export interface VyralGraphCollectionExportRequest {
  graphId?: string | null;
  namespace?: string | null;
  tenantId?: string | null;
  partitionKey?: string | null;
  includeProjections?: boolean;
  maxRecords?: number | null;
  failOnLimitExceeded?: boolean;
}

export interface VyralGraphCollectionExportResult {
  collection?: string;
  envelope?: VyralGraphEnvelope;
  recordCount?: number;
  truncated?: boolean;
  continuationToken?: string | null;
  exportedAt?: string | null;
}

export interface VyralGraphTraversalRequest {
  graphId?: string | null;
  namespace?: string | null;
  tenantId?: string | null;
  partitionKey?: string | null;
  startNodeIds: Array<string>;
  profile?: VyralGraphTraversalProfile;
  maxRecords?: number | null;
  allowPartialGraph?: boolean;
}

export interface VyralGraphTraversalResult {
  collection?: string;
  graphId?: string;
  projection?: VyralGraphProjection;
  nodeCount?: number;
  edgeCount?: number;
  sourceRecordCount?: number;
  sourceTruncated?: boolean;
  requestedMaxRecords?: number;
  exportedRecordCount?: number;
  estimatedRequiredRecordCount?: number | null;
  sourceContinuationToken?: string | null;
}

export interface VyralGraphCollectionInspectionRequest {
  graphId?: string | null;
  namespace?: string | null;
  tenantId?: string | null;
  partitionKey?: string | null;
  maxRecords?: number | null;
  allowPartialGraph?: boolean;
  includeAnomalies?: boolean;
  anomalyLimit?: number;
}

export interface VyralGraphSourceGroundingInspection {
  nodeGroundedCount?: number;
  nodeUngroundedCount?: number;
  nodeCoverage?: number;
  edgeGroundedCount?: number;
  edgeUngroundedCount?: number;
  edgeCoverage?: number;
  assertionGroundedCount?: number;
  assertionUngroundedCount?: number;
  assertionCoverage?: number;
}

export interface VyralGraphInspectionAnomaly {
  kind?: string;
  id?: string;
  subjectId?: string | null;
  subjectKind?: string | null;
  message?: string;
  details?: JsonObject;
}

export interface VyralGraphCollectionInspectionResult {
  collection?: string;
  generatedAt?: string;
  graphId?: string;
  namespace?: string;
  tenantId?: string;
  partitionKey?: string;
  recordCount?: number;
  truncated?: boolean;
  continuationToken?: string | null;
  traversalReady?: boolean;
  nodeCount?: number;
  edgeCount?: number;
  assertionCount?: number;
  reviewCount?: number;
  projectionCount?: number;
  recordTypeCounts?: JsonObject;
  graphIdCounts?: JsonObject;
  namespaceCounts?: JsonObject;
  tenantIdCounts?: JsonObject;
  partitionKeyCounts?: JsonObject;
  nodeTypeCounts?: JsonObject;
  predicateCounts?: JsonObject;
  assertionStatusCounts?: JsonObject;
  reviewStatusCounts?: JsonObject;
  sourceGrounding?: VyralGraphSourceGroundingInspection;
  danglingEdgeCount?: number;
  orphanAssertionCount?: number;
  orphanReviewCount?: number;
  danglingAssertionReferenceCount?: number;
  danglingProjectionStartNodeCount?: number;
  duplicateNodeIdCount?: number;
  duplicateEdgeIdCount?: number;
  duplicateAssertionIdCount?: number;
  duplicateReviewIdCount?: number;
  duplicateProjectionIdCount?: number;
  warningCount?: number;
  warnings?: Array<string>;
  anomalyCount?: number;
  returnedAnomalyCount?: number;
  anomalies?: Array<VyralGraphInspectionAnomaly>;
}

export interface CollectionExportEnvelope {
  collection: string;
  policy: RecordCollectionPolicy;
  records: Array<VyralRecord>;
  query?: QueryEnvelope | null;
  maxRecords?: number | null;
  recordCount?: number | null;
  truncated?: boolean;
  continuationToken?: string | null;
  exportedAt?: string | null;
  contentHash?: string | null;
}

export interface CollectionExportRequest {
  query?: QueryEnvelope | null;
  maxRecords?: number | null;
  failOnLimitExceeded?: boolean;
}

export interface CollectionImportRequest {
  snapshot: CollectionExportEnvelope;
  expectedContentHash?: string | null;
  replaceExisting?: boolean;
  continueOnError?: boolean;
  allowCollectionRename?: boolean;
  allowPartialSnapshot?: boolean;
}

export interface CollectionImportResult {
  collection: string;
  sourceCollection: string;
  policyStatus: "created" | "existing_equivalent" | "replaced";
  recordCount: number;
  contentHash: string;
  contentHashComparison: CollectionSnapshotHashComparison;
  records: RecordBatchUpsertResult;
}

export interface CollectionSnapshotHashComparison {
  kind: string;
  expectedHash?: string | null;
  actualHash?: string | null;
  compared: boolean;
  matches: boolean;
  status: "not_provided" | "actual_missing" | "matched" | "drifted";
}

export interface RecordBatchUpsertRequest {
  records: Array<VyralRecord>;
  preconditions?: Array<RecordWritePrecondition>;
  continueOnError?: boolean;
}

export interface RecordWritePrecondition {
  ifMatch?: string;
  ifNoneMatch?: string;
  expectedEtag?: string;
  expectedRevision?: number;
}

export interface RecordBatchUpsertResult {
  collection: string;
  requested: number;
  attempted: number;
  succeeded: number;
  failed: number;
  stoppedOnError: boolean;
  items: Array<RecordBatchUpsertItemResult>;
}

export interface RecordBatchUpsertItemResult {
  index: number;
  id?: string | null;
  partitionKey?: string | null;
  status: "succeeded" | "failed";
  etag?: string | null;
  revision?: number | null;
  error?: string | null;
}

export interface RecordImportJob {
  admission: AdmissionReceipt;
  id: string;
  kind: "batch_upsert" | "collection_import";
  status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "rejected";
  collection: string;
  sourceCollection?: string | null;
  requestHash: string;
  createdAt: string;
  startedAt?: string | null;
  completedAt?: string | null;
  durationMs?: number | null;
  cancellationRequested: boolean;
  requested: number;
  attempted: number;
  succeeded: number;
  failed: number;
  progress: number;
  stoppedOnError: boolean;
  failureClass?: string | null;
  error?: string | null;
  batchResult?: RecordBatchUpsertResult;
  importResult?: CollectionImportResult;
}

export interface VyralRecordMatch {
  record: VyralRecord;
  score: number;
  diagnostics?: RetrievalDiagnostics;
}

export interface RetrievalDiagnostics {
  schemaVersion?: string;
  resultIdentity?: RetrievalResultIdentity;
  scoreComponents?: JsonObject;
  scoreNormalization?: RetrievalScoreNormalization;
  candidateSources?: Array<string>;
  candidateCounts?: JsonObject;
  reasonCodes?: Array<string>;
  matchedFields?: Array<string>;
  matchedTerms?: Array<string>;
  traceReferences?: Array<RetrievalTraceReference>;
  details?: JsonObject;
}

export interface RetrievalResultIdentity {
  collection?: string;
  partitionKey?: string;
  id?: string;
  type?: string;
  etag?: string | null;
  revision?: number | null;
}

export interface RetrievalScoreNormalization {
  finalScoreKind?: string;
  vectorScoreKind?: string | null;
  lexicalScoreKind?: string | null;
  hybridFusion?: string | null;
  vectorDistanceFunction?: string | null;
  vectorNormalization?: string | null;
  weights?: JsonObject;
  parameters?: JsonObject;
}

export interface RetrievalTraceReference {
  kind?: string;
  operation?: string;
  traceId?: string;
  provider?: string | null;
  modelId?: string | null;
  redaction?: string;
  safe?: boolean;
}

export interface ObjectInfo {
  container: string;
  key: string;
  contentType?: string | null;
  contentLength: number;
  etag: string;
  contentHash: string;
  metadata: JsonObject;
  updatedAt: string;
}

export interface ObjectListResult {
  items: Array<ObjectInfo>;
  continuationToken?: string | null;
}

export interface EmbeddingOptions {
  field?: string | null;
  purpose?: "query" | "passage" | "document" | "symmetric" | null;
  queryPrefix?: string | null;
  passagePrefix?: string | null;
  symmetricPrefix?: string | null;
}

export interface RetrievalProfileDescriptor {
  id: string;
  label: string;
  description: string;
  searchMode: "vector" | "lexical" | "hybrid";
  requiresVector: boolean;
  usesRerank: boolean;
  recommendedFor: Array<string>;
  cautions: Array<string>;
  defaults: RetrievalProfileDefaults;
}

export interface RetrievalProfileDefaults {
  searchMode: "vector" | "lexical" | "hybrid";
  embedding?: EmbeddingOptions | null;
  lexical?: LexicalSearchOptions | null;
  hybrid?: HybridSearchOptions | null;
  rerank?: RerankOptions | null;
  limit: number;
  includeTrace: boolean;
}

export interface RetrievalRequest {
  profile?: string | null;
  query: string;
  collections: Array<string>;
  partitionKeys?: Array<string> | null;
  filter?: FilterNode;
  embedding?: EmbeddingOptions;
  vectorFields?: Array<RetrievalVectorFieldQuery> | null;
  searchMode?: "vector" | "lexical" | "hybrid";
  lexical?: LexicalSearchOptions;
  hybrid?: HybridSearchOptions;
  rerank?: RerankOptions;
  limit?: number;
  minScore?: number | null;
  includeTrace?: boolean;
}

export interface RetrievalResultEnvelope {
  query: string;
  results: Array<RetrievalMatch>;
  trace?: JsonObject | null;
}

export interface RetrievalMatch {
  rank: number;
  score: number;
  collection: string;
  snippet?: string | null;
  record: VyralRecord;
  diagnostics?: RetrievalDiagnostics;
}

export interface RetrievalEvaluationRequest {
  cases: Array<RetrievalEvaluationCase>;
  continueOnError?: boolean;
  defaultK?: number | null;
  includeTopResults?: boolean;
}

export interface RetrievalEvaluationComparisonRequest {
  cases: Array<RetrievalEvaluationCase>;
  variants: Array<RetrievalEvaluationVariant>;
  continueOnError?: boolean;
  defaultK?: number | null;
  includeTopResults?: boolean;
  includeCaseResults?: boolean;
}

export interface RetrievalEvaluationVariant {
  id: string;
  label?: string | null;
  profile?: string | null;
  collections?: Array<string> | null;
  partitionKeys?: Array<string> | null;
  filter?: FilterNode;
  embedding?: EmbeddingOptions;
  vectorFields?: Array<RetrievalVectorFieldQuery> | null;
  searchMode?: "lexical" | "vector" | "hybrid" | null;
  lexical?: LexicalSearchOptions;
  hybrid?: HybridSearchOptions;
  rerank?: RerankOptions;
  limit?: number | null;
  minScore?: number | null;
  includeTrace?: boolean | null;
}

export interface RetrievalEvaluationCase {
  name?: string | null;
  request: RetrievalRequest;
  expected: Array<RetrievalEvaluationExpectedMatch>;
  hardNegatives?: Array<RetrievalEvaluationHardNegativeMatch>;
  k?: number | null;
  metadata?: JsonObject | null;
}

export interface RetrievalEvaluationExpectedMatch {
  id?: string;
  partitionKey?: string | null;
  collection?: string | null;
  aliases?: Array<string>;
  sourceIds?: Array<string>;
  sources?: Array<VyralSourceReference>;
  relevance?: number;
}

export interface RetrievalEvaluationHardNegativeMatch {
  id?: string;
  partitionKey?: string | null;
  collection?: string | null;
  aliases?: Array<string>;
  sourceIds?: Array<string>;
  sources?: Array<VyralSourceReference>;
  reason?: string | null;
}

export interface RetrievalEvaluationResult {
  requested: number;
  attempted: number;
  succeeded: number;
  failed: number;
  stoppedOnError?: boolean;
  hitCount: number;
  hitRate: number;
  meanReciprocalRank?: number;
  meanPrecisionAtK?: number;
  meanRecallAtK?: number;
  meanNdcgAtK?: number;
  hardNegativeCaseCount?: number;
  hardNegativeHitCount?: number;
  hardNegativeHitRate?: number;
  meanHardNegativeRateAtK?: number;
  rerankCaseCount?: number;
  rerankFallbackCaseCount?: number;
  rerankFallbackRate?: number;
  cases: Array<RetrievalEvaluationCaseResult>;
}

export interface RetrievalEvaluationComparisonResult {
  requested: number;
  variantsRequested: number;
  variantsAttempted: number;
  variantsSucceeded: number;
  variantsFailed: number;
  stoppedOnError?: boolean;
  baselineVariantId?: string | null;
  variants: Array<RetrievalEvaluationVariantResult>;
}

export interface RetrievalEvaluationProgress {
  currentCaseIndex?: number | null;
  currentCaseName?: string | null;
  requested?: number;
  casesAttempted?: number;
  casesSucceeded?: number;
  casesFailed?: number;
  result?: RetrievalEvaluationResult;
}

export interface RetrievalEvaluationComparisonProgress {
  currentVariantId?: string | null;
  currentVariantIndex?: number | null;
  requested?: number;
  variantsRequested?: number;
  variantsAttempted?: number;
  variantsSucceeded?: number;
  variantsFailed?: number;
  result?: RetrievalEvaluationComparisonResult;
}

export interface RetrievalEvaluationJob {
  admission: AdmissionReceipt;
  id: string;
  kind: "evaluation" | "comparison";
  status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "rejected";
  requestHash: string;
  createdAt: string;
  startedAt?: string | null;
  completedAt?: string | null;
  durationMs?: number | null;
  cancellationRequested?: boolean;
  requested: number;
  casesAttempted: number;
  casesSucceeded: number;
  casesFailed: number;
  currentCaseIndex?: number | null;
  currentCaseName?: string | null;
  variantsRequested: number;
  variantsAttempted: number;
  variantsSucceeded: number;
  variantsFailed: number;
  currentVariantId?: string | null;
  currentVariantIndex?: number | null;
  progress: number;
  failureClass?: string | null;
  error?: string | null;
  evaluationResult?: RetrievalEvaluationResult;
  result?: RetrievalEvaluationComparisonResult;
}

export interface RetrievalEvaluationVariantResult {
  id: string;
  label?: string | null;
  status: "succeeded" | "failed";
  error?: string | null;
  durationMs: number;
  metrics: RetrievalEvaluationMetrics;
  deltaFromBaseline?: RetrievalEvaluationMetricDeltas;
  cases: Array<RetrievalEvaluationCaseResult>;
}

export interface RetrievalEvaluationMetrics {
  requested?: number;
  attempted?: number;
  succeeded?: number;
  failed?: number;
  stoppedOnError?: boolean;
  hitCount?: number;
  hitRate?: number;
  meanReciprocalRank?: number;
  meanPrecisionAtK?: number;
  meanRecallAtK?: number;
  meanNdcgAtK?: number;
  hardNegativeCaseCount?: number;
  hardNegativeHitCount?: number;
  hardNegativeHitRate?: number;
  meanHardNegativeRateAtK?: number;
  rerankCaseCount?: number;
  rerankFallbackCaseCount?: number;
  rerankFallbackRate?: number;
}

export interface RetrievalEvaluationMetricDeltas {
  hitRate?: number;
  meanReciprocalRank?: number;
  meanPrecisionAtK?: number;
  meanRecallAtK?: number;
  meanNdcgAtK?: number;
  hardNegativeHitRate?: number;
  meanHardNegativeRateAtK?: number;
  rerankFallbackRate?: number;
}

export interface RetrievalEvaluationCaseResult {
  index: number;
  name?: string | null;
  query: string;
  status: "succeeded" | "failed";
  error?: string | null;
  durationMs: number;
  k: number;
  expectedCount: number;
  retrievedCount: number;
  matchedCount: number;
  hit: boolean;
  firstRelevantRank?: number | null;
  reciprocalRank?: number;
  precisionAtK?: number;
  recallAtK?: number;
  ndcgAtK?: number;
  hardNegativeCount?: number;
  hardNegativeMatchedCount?: number;
  hardNegativeHit?: boolean;
  firstHardNegativeRank?: number | null;
  hardNegativeRateAtK?: number;
  rerankEnabled?: boolean;
  rerankProvider?: string | null;
  rerankTraceId?: string | null;
  rerankFallbackApplied?: boolean;
  rerankFailureClass?: string | null;
  rerankProviderStatus?: string | null;
  rerankInputCandidateCount?: number;
  rerankProviderPayloadBytes?: number;
  rerankProviderMaxInputBytes?: number;
  expected?: Array<RetrievalEvaluationExpectedResult>;
  hardNegatives?: Array<RetrievalEvaluationHardNegativeResult>;
  topResults?: Array<RetrievalEvaluationTopResult>;
}

export interface RetrievalEvaluationExpectedResult {
  id?: string;
  partitionKey?: string | null;
  collection?: string | null;
  relevance?: number;
  rank?: number | null;
  score?: number | null;
}

export interface RetrievalEvaluationHardNegativeResult {
  id?: string;
  partitionKey?: string | null;
  collection?: string | null;
  reason?: string | null;
  rank?: number | null;
  score?: number | null;
}

export interface RetrievalEvaluationTopResult {
  rank?: number;
  score?: number;
  collection?: string;
  id?: string;
  partitionKey?: string;
  type?: string | null;
  matchedExpected?: boolean;
  matchedHardNegative?: boolean;
  rerankFallbackApplied?: boolean;
  rerankProviderStatus?: string | null;
  vectorIndexUsed?: boolean;
  vectorIndexProvider?: string | null;
  vectorIndexFields?: Array<string>;
  snippet?: string | null;
}

export interface RagIngestTextRequest {
  documentId?: string | null;
  idPrefix?: string | null;
  partitionKey: string;
  type?: string;
  schemaVersion?: string | null;
  text: string;
  contentField?: string;
  embedding?: EmbeddingOptions;
  metadata?: JsonObject | null;
  sourceUri?: string | null;
  sourceKind?: string | null;
  sourceId?: string | null;
  sourceLabel?: string | null;
  sources?: Array<VyralSourceReference> | null;
  options?: RagIngestionOptions;
}

export interface RagIngestionOptions {
  chunkChars?: number;
  chunkOverlapChars?: number;
  dryRun?: boolean;
  replaceDocumentChunks?: boolean;
  skipUnchangedChunks?: boolean;
  reuseExistingChunkVectors?: boolean;
  vectorReuseScope?: "request" | "partition" | "collection";
  deduplicateExistingChunks?: boolean;
  chunkDedupeScope?: "request" | "partition" | "collection";
  persistManifest?: boolean;
  manifestId?: string | null;
  expectedPlanHash?: string | null;
  expectedManifestHash?: string | null;
  includeTrace?: boolean;
}

export interface RagIngestTextBatchRequest {
  items: Array<RagIngestTextRequest>;
  continueOnError?: boolean;
}

export interface RagIngestTextBatchResult {
  collection: string;
  requested: number;
  attempted: number;
  succeeded: number;
  failed: number;
  stoppedOnError: boolean;
  textLength: number;
  chunkCount: number;
  deletedStaleCount: number;
  createdCount: number;
  updatedCount: number;
  reusedCount: number;
  vectorGeneratedCount: number;
  vectorReusedCount: number;
  deduplicatedCount: number;
  items: Array<RagIngestTextBatchItemResult>;
}

export interface RagIngestTextBatchItemResult {
  index: number;
  documentId?: string | null;
  partitionKey?: string | null;
  status: "succeeded" | "failed";
  result?: RagIngestTextResult | null;
  error?: string | null;
}

export interface RagIngestTextResult {
  collection: string;
  documentId: string;
  partitionKey: string;
  embeddingField: string;
  embeddingProvider: string;
  embeddingModel: string;
  embeddingPurpose: string;
  dimensions: number;
  textLength: number;
  textHash: string;
  planHash: string;
  chunkCount: number;
  dryRun: boolean;
  deletedStaleCount: number;
  createdCount: number;
  updatedCount: number;
  reusedCount: number;
  vectorGeneratedCount: number;
  vectorReusedCount: number;
  deduplicatedCount: number;
  manifestId?: string | null;
  manifestHash?: string | null;
  manifestAction?: "created" | "updated" | "reused" | null | null;
  manifestEtag?: string | null;
  manifestRevision?: number | null;
  actionSummary: RagIngestActionSummary;
  planHashComparison: RagIngestHashComparison;
  manifestHashComparison: RagIngestHashComparison;
  staleDeletes: Array<RagIngestStaleDeleteResult>;
  chunks: Array<RagIngestChunkResult>;
  trace?: JsonObject | null;
}

export interface RagIngestActionSummary {
  actionCounts?: JsonObject;
  embeddingActionCounts?: JsonObject;
  createdIds?: Array<string>;
  updatedIds?: Array<string>;
  reusedIds?: Array<string>;
  deduplicatedIds?: Array<string>;
  staleDeleteIds?: Array<string>;
}

export interface RagIngestHashComparison {
  kind?: string;
  expectedHash?: string | null;
  actualHash?: string | null;
  compared?: boolean;
  matches?: boolean;
  status?: "not_provided" | "matched" | "drifted" | "actual_missing";
}

export interface RagIngestStaleDeleteResult {
  id: string;
  partitionKey: string;
  chunkIndex?: number | null;
  textHash?: string | null;
  etag?: string | null;
  revision?: number | null;
}

export interface RagIngestChunkResult {
  index: number;
  id: string;
  partitionKey: string;
  charStart: number;
  charEnd: number;
  textLength: number;
  textHash: string;
  embeddingTextHash: string;
  action: "created" | "updated" | "reused" | "deduplicated";
  embeddingAction: "generated" | "reused" | "unchanged" | "deduplicated";
  reusedVectorFromId?: string | null;
  reusedVectorFromPartitionKey?: string | null;
  deduplicatedFromId?: string | null;
  deduplicatedFromPartitionKey?: string | null;
  etag?: string | null;
  revision?: number | null;
}

export interface RetrievalVectorFieldQuery {
  field: string;
  weight?: number;
  query?: string | null;
  embedding?: EmbeddingOptions;
  candidateLimit?: number | null;
  minScore?: number | null;
}

export interface RagContextRequest {
  retrieval: RetrievalRequest;
  contentField?: string;
  maxChars?: number;
  maxCharsPerChunk?: number;
  maxCitationsPerChunk?: number | null;
  contextAssembly?: RagContextAssemblyOptions;
  graphExpansion?: RagContextGraphExpansionOptions;
  includeRecords?: boolean;
  includeCitations?: boolean;
  includeContextText?: boolean;
  includeTrace?: boolean;
}

export interface RagContextEvaluationRequest {
  cases: Array<RagContextEvaluationCase>;
  continueOnError?: boolean;
  includeContext?: boolean;
}

export interface RagContextEvaluationCase {
  name?: string | null;
  request: RagContextRequest;
  expectedGraph?: RagContextExpectedGraph;
  metadata?: JsonObject | null;
}

export interface RagContextExpectedGraph {
  nodeIds?: Array<string>;
  edgeIds?: Array<string>;
  provenanceEntityIds?: Array<string>;
  requireSourceGroundedProvenance?: boolean;
  requireGraphContextText?: boolean;
  requireContextTextNotTruncated?: boolean;
}

export interface RagContextEvaluationResult {
  requested?: number;
  attempted?: number;
  succeeded?: number;
  failed?: number;
  stoppedOnError?: boolean;
  passedCount?: number;
  passRate?: number;
  nodeHitRate?: number;
  edgeHitRate?: number;
  provenanceHitRate?: number;
  cases?: Array<RagContextEvaluationCaseResult>;
  failureCategoryCounts?: JsonObject;
  limitReasonCounts?: JsonObject;
}

export interface RagContextEvaluationCaseResult {
  index?: number;
  name?: string | null;
  status?: "succeeded" | "failed";
  passed?: boolean;
  durationMs?: number;
  graph?: RagContextGraphEvaluationResult;
  context?: RagContextEnvelope | null;
  error?: string | null;
  queryId?: string | null;
  profileName?: string | null;
  expectedAnchorIds?: Array<string>;
  retrievedRecordIds?: Array<string>;
  graphExpandedNodeIds?: Array<string>;
  graphExpandedEdgeIds?: Array<string>;
  lexicalContributionCount?: number;
  vectorContributionCount?: number;
  graphContributionCount?: number;
  failureCategories?: Array<string>;
  limitReasons?: Array<string>;
  graphContribution?: RagContextGraphExpansionSummary | null;
}

export interface RagContextGraphEvaluationResult {
  status?: string | null;
  expectedNodeCount?: number;
  matchedNodeCount?: number;
  missingNodeIds?: Array<string>;
  expectedEdgeCount?: number;
  matchedEdgeCount?: number;
  missingEdgeIds?: Array<string>;
  expectedProvenanceCount?: number;
  matchedProvenanceCount?: number;
  missingProvenanceEntityIds?: Array<string>;
  sourceGroundedProvenanceCount?: number;
  sourceGroundingSatisfied?: boolean;
  graphContextTextPresent?: boolean;
  contextTextTruncated?: boolean;
  passed?: boolean;
  budgetTruncated?: boolean;
  failureModes?: RagContextGraphEvaluationFailureModes;
  failureCategories?: Array<string>;
}

export interface RagContextGraphExpansionOptions {
  enabled?: boolean;
  collection?: string;
  graphId?: string | null;
  namespace?: string | null;
  tenantId?: string | null;
  partitionKey?: string | null;
  seedNodeIds?: Array<string>;
  seedJsonPointers?: Array<string>;
  maxSeedNodes?: number;
  profile?: VyralGraphTraversalProfile;
  maxRecords?: number | null;
  allowPartialGraph?: boolean;
  includeGraphContextText?: boolean;
  maxGraphContextChars?: number;
  includeGraphProvenance?: boolean;
  maxGraphProvenanceItems?: number;
  fallbackOnFailure?: boolean;
}

export interface RagContextAssemblyOptions {
  groupBy?: "collection" | "sourceKind" | "metadata" | "jsonPointer" | null | null;
  groupByPath?: string | null;
  defaultMaxChunksPerGroup?: number | null;
  defaultMaxCharsPerGroup?: number | null;
  failOnUnsatisfiedRequiredGroups?: boolean;
  groups?: Array<RagContextGroupBudget>;
}

export interface RagContextGroupBudget {
  key: string;
  priority?: number | null;
  required?: boolean;
  minChunks?: number | null;
  maxChunks?: number | null;
  minChars?: number | null;
  maxChars?: number | null;
}

export interface RagContextEnvelope {
  query: string;
  chunks: Array<RagContextChunk>;
  citations: Array<RagContextCitation>;
  totalChars: number;
  omittedCitationCount?: number;
  contextText?: string | null;
  contextTextFormat?: "citation-markdown" | null | null;
  contextTextHash?: string | null;
  graphContext?: RagContextGraphContext | null;
  trace?: JsonObject | null;
  graphExpansion?: RagContextGraphExpansionSummary | null;
}

export interface RagContextGraphProvenance {
  entityKind?: string;
  entityId?: string;
  label?: string | null;
  nodeType?: string | null;
  predicate?: string | null;
  sourceId?: string | null;
  targetId?: string | null;
  sourceSpans?: Array<VyralGraphSourceSpan>;
  assertionIds?: Array<string>;
}

export interface RagContextGraphContext {
  status?: "not_requested" | "succeeded" | "no_seeds" | "graph_not_found" | "budget_truncated" | "failed";
  collection?: string;
  graphId?: string | null;
  seedNodeIds?: Array<string>;
  seedCandidateCount?: number;
  projection?: VyralGraphProjection | null;
  nodeCount?: number;
  edgeCount?: number;
  sourceRecordCount?: number;
  sourceTruncated?: boolean;
  contextText?: string | null;
  contextTextHash?: string | null;
  contextTextChars?: number;
  contextTextTruncated?: boolean;
  provenance?: Array<RagContextGraphProvenance>;
  omittedProvenanceCount?: number;
  failureReason?: string | null;
  seedJsonPointers?: Array<string>;
  seedDiagnostics?: Array<RagContextGraphSeedDiagnostic>;
  omittedSeedDiagnosticCount?: number;
  droppedSeedCount?: number;
  maxSeedNodes?: number;
  requestedMaxRecords?: number | null;
  exportedRecordCount?: number;
  estimatedRequiredRecordCount?: number | null;
  sourceContinuationToken?: string | null;
  limitsHit?: Array<string>;
}

export interface RagPromptRequest {
  context: RagContextRequest;
  template?: RagPromptTemplateOptions;
}

export interface RagPromptTemplateOptions {
  format?: "chat-markdown";
  systemInstruction?: string | null;
  userInstruction?: string | null;
  citationInstruction?: string | null;
  includeCitationInstruction?: boolean;
  failOnEmptyContext?: boolean;
  maxPromptChars?: number | null;
}

export interface RagPromptEnvelope {
  query: string;
  format: "chat-markdown";
  prompt: string;
  promptHash: string;
  messages: Array<RagPromptMessage>;
  context: RagContextEnvelope;
  trace?: JsonObject | null;
}

export interface RagPromptMessage {
  role: "system" | "user";
  content: string;
}

export interface RagContextChunk {
  rank: number;
  score: number;
  collection: string;
  partitionKey: string;
  id: string;
  text: string;
  contentField: string;
  groupKey?: string | null;
  charStart: number;
  charEnd: number;
  originalTextLength: number;
  truncated: boolean;
  contextExcerptHash: string;
  citationIds?: Array<string>;
  retrievalDiagnostics?: RetrievalDiagnostics;
  retrievalMatch?: RagContextRetrievalMatch;
  metadata?: JsonObject | null;
  sources?: Array<VyralSourceReference> | null;
  record?: VyralRecord;
}

export interface RagContextCitation {
  id: string;
  chunkRank: number;
  collection: string;
  partitionKey: string;
  recordId: string;
  sourceId?: string | null;
  sourceKind?: string | null;
  sourceUri?: string | null;
  sourceLabel?: string | null;
  sourceSpan?: JsonObject | null;
  includedSourceSpan?: JsonObject | null;
  contextCharStart: number;
  contextCharEnd: number;
  contextExcerptHash: string;
}

export interface RagContextRetrievalMatch {
  rank: number;
  score: number;
  collection: string;
  searchMode: string;
  snippet?: string | null;
}

export interface TraceRecord {
  id: string;
  operation: string;
  adapter?: string | null;
  request: JsonObject;
  resultSummary: JsonObject;
  startedAt: string;
  durationMs: number;
  createdAt: string;
}

export interface TracePruneRequest {
  operation?: string | null;
  olderThan?: string | null;
  keepLatest?: number | null;
  limit?: number | null;
  dryRun?: boolean;
}

export interface TraceSummary {
  operation?: string | null;
  totalCount: number;
  statusCounts: JsonObject;
  failureClassCounts: JsonObject;
  providerStatusCounts: JsonObject;
  providerCounts: JsonObject;
  capabilityCounts: JsonObject;
  operations: Array<TraceOperationSummary>;
}

export interface TraceOperationSummary {
  operation: string;
  count: number;
  firstCreatedAt: string;
  latestCreatedAt: string;
  adapters: Array<string>;
  statusCounts: JsonObject;
  failureClassCounts: JsonObject;
  providerStatusCounts: JsonObject;
  providerCounts: JsonObject;
  capabilityCounts: JsonObject;
}

export interface TraceExportRequest {
  operation?: string | null;
  limit?: number | null;
  failOnUnsafeContent?: boolean;
}

export interface TraceExportBundle {
  formatVersion: string;
  exportedAt: string;
  operation?: string | null;
  limit: number;
  traceCount: number;
  warningCount: number;
  contentHash: string;
  warnings: Array<TraceExportWarning>;
  traces: Array<TraceRecord>;
}

export interface TraceExportWarning {
  traceId: string;
  location: string;
  reason: string;
}

export interface TracePruneResult {
  operation?: string | null;
  olderThan?: string | null;
  keepLatest?: number | null;
  limit?: number | null;
  dryRun: boolean;
  matchedCount: number;
  deletedCount: number;
  matchedIds: Array<string>;
  deletedIds: Array<string>;
}

export interface ServerHealthStatus {
  status: "ok";
  service: string;
  version: string;
  contractPath: string;
  schemaContractPath: string;
  storage: ServerStorageStatus;
  embedding: ServerEmbeddingStatus;
  security: ServerSecurityStatus;
  checkedAt: string;
}

export interface ServerStorageStatus {
  recordStore: string;
  objectStore: string;
  traceStore: string;
  canonicalStore: string;
}

export interface ServerEmbeddingStatus {
  provider: string;
  modelId: string;
  dimensions: number;
  runtime?: JsonObject;
}

export interface ExecutionRuntimeSurface {
  status: ExecutionRuntimeAdapterStatus;
  plugins: Array<ExecutionPluginDescriptor>;
  handlers: Array<ExecutionHandlerDescriptor>;
}

export interface EffectiveExecutionRuntimeSurface {
  status: ExecutionRuntimeAdapterStatus;
  scope: ExecutionRuntimeDiscoveryScope;
  handlers: Array<ExecutionHandlerDescriptor>;
}

export interface ExecutionRuntimeDiscoveryScope {
  sharedExecution: boolean;
  scopeRequired: boolean;
  productId?: string | null;
  tenantId?: string | null;
}

export interface ExecutionRuntimeAdapterStatus {
  adapter: ExecutionRuntimeAdapterDescriptor;
  available: boolean;
  status: string;
  checkedAtUtc: string;
  activeRuns?: number | null;
  operationalPolicy?: ExecutionOperationalPolicy | null;
  resumePolicy?: ExecutionResumePolicy | null;
  details?: JsonObject | null;
}

export interface ExecutionMaintenanceStatus {
  adapterId: string;
  runtimeKind: string;
  checkedAtUtc: string;
  retentionScope: string;
  maxRetainedTerminalRuns?: number | null;
  runCounts: JsonObject;
  rowCounts: JsonObject;
  artifactDirectory?: string | null;
  artifactDirectoryCount?: number | null;
  artifactFileCount?: number | null;
  artifactBytes?: number | null;
}

export interface ExecutionMaintenancePruneRequest {
  dryRun?: boolean;
  retainTerminalRuns?: number | null;
}

export interface ExecutionMaintenancePruneResult {
  dryRun: boolean;
  retainTerminalRuns: number;
  prunedAtUtc: string;
  runIds: Array<string>;
  runs: number;
  events: number;
  artifacts: number;
  checkpoints: number;
  timers: number;
  externalEvents: number;
  leases: number;
  artifactDirectories: number;
}

export interface ExecutionMaintenanceDispatchReconcileRequest {
  dryRun?: boolean;
  limit?: number | null;
}

export interface ExecutionMaintenanceDispatchReconcileResult {
  dryRun: boolean;
  limit: number;
  reconciledAtUtc: string;
  candidateRunIds: Array<string>;
  dispatched: number;
  failures: JsonObject;
}

export interface ExecutionOperationalPolicy {
  maxActiveRuns: number;
  maxRetainedTerminalRuns?: number | null;
  defaultListLimit: number;
  maxListLimit: number;
  defaultHistoryLimit: number;
  maxHistoryLimit: number;
  maxPayloadBytes: number;
  maxResultBytes: number;
  maxStatusDetailsBytes: number;
  maxArtifactBytes: number;
  maxArtifactInlineBytes: number;
  maxTraceMessageChars: number;
  maxTraceDetailsBytes: number;
  maxRetryAttempts: number;
  maxRetryDelaySeconds: number;
  maxLeaseTtlSeconds: number;
  concurrencyKeyPolicy: string;
  concurrencyRetryDelayMs?: number | null;
  defaultTraceSeverity: string;
  retentionScope: string;
}

export interface ExecutionResumePolicy {
  mode: string;
  interruptedRunningBehavior: string;
  scheduledWaitingBehavior: string;
  terminalBehavior: string;
  pluginCheckpointBehavior: string;
  idempotencyScope: string;
  createsLinkedFollowUpRuns: boolean;
}

export interface ExecutionRuntimeAdapterDescriptor {
  adapterId: string;
  runtimeKind: string;
  displayName: string;
  version: string;
  capabilities: Array<string>;
  metadata: JsonObject;
}

export interface ExecutionPluginDescriptor {
  pluginId: string;
  name: string;
  version: string;
  handlers: Array<ExecutionHandlerDescriptor>;
}

export interface ExecutionHandlerDescriptor {
  handlerId: string;
  pluginId?: string | null;
  displayName: string;
  description?: string | null;
  maxAttempts: number;
  concurrencyKey?: string | null;
  tags: JsonObject;
}

export interface ExecutionRetryPolicy {
  maxAttempts?: number;
  initialDelaySeconds?: number;
  maxDelaySeconds?: number;
  backoffMultiplier?: number;
}

export interface ExecutionRunRequest {
  handlerId: string;
  pluginId?: string | null;
  payload?: JsonValue;
  idempotencyKey?: string | null;
  correlationId?: string | null;
  scope?: ExecutionScope | null;
  scheduledAtUtc?: string | null;
  retryPolicy?: ExecutionRetryPolicy;
  tags?: JsonObject;
}

export interface ExecutionRun {
  admission: AdmissionReceipt;
  id: string;
  handlerId: string;
  pluginId?: string | null;
  status: "queued" | "waiting" | "running" | "succeeded" | "failed" | "cancelled" | "rejected" | "timed_out";
  attempt: number;
  maxAttempts: number;
  retryPolicy?: JsonObject;
  correlationId: string;
  scope?: ExecutionScope | null;
  payloadHash: string;
  payload?: JsonValue;
  createdAtUtc: string;
  scheduledAtUtc?: string | null;
  startedAtUtc?: string | null;
  updatedAtUtc: string;
  completedAtUtc?: string | null;
  durationMs?: number | null;
  cancellationRequested: boolean;
  requested?: number | null;
  attempted?: number | null;
  succeeded?: number | null;
  failed?: number | null;
  progress?: number | null;
  currentStep?: string | null;
  failureClass?: string | null;
  error?: string | null;
  result?: JsonValue;
  statusDetails?: JsonObject | null;
  tags: JsonObject;
}

export interface ExecutionTraceEvent {
  id: string;
  sequenceId: string;
  runId: string;
  type: string;
  timestampUtc: string;
  attempt: number;
  stepId?: string | null;
  status?: string | null;
  severity: string;
  message?: string | null;
  details?: JsonObject | null;
  context: JsonObject;
}

export interface ExecutionArtifact {
  id: string;
  runId: string;
  name: string;
  kind: string;
  mediaType?: string | null;
  contentHash: string;
  sizeBytes: number;
  text?: string | null;
  content?: JsonValue;
  uri?: string | null;
  createdAtUtc: string;
  metadata: JsonObject;
}

export interface ExecutionCheckpoint {
  runId: string;
  key: string;
  contentHash: string;
  updatedAtUtc: string;
  content?: JsonValue;
  metadata: JsonObject;
}

export interface ExecutionScope {
  productId: string;
  tenantId: string;
  serviceIdentity?: string | null;
}

export interface ExecutionRunUpdate {
  status?: string | null;
  requested?: number | null;
  attempted?: number | null;
  succeeded?: number | null;
  failed?: number | null;
  progress?: number | null;
  currentStep?: string | null;
  failureClass?: string | null;
  error?: string | null;
  result?: JsonValue;
  statusDetails?: JsonObject | null;
}

export interface ExecutionRunResult {
  status: string;
  result?: JsonValue;
  failureClass?: string | null;
  error?: string | null;
  statusDetails?: JsonObject | null;
}

export interface ExecutionArtifactWrite {
  name: string;
  kind?: string | null;
  mediaType?: string | null;
  text?: string | null;
  content?: JsonValue;
  uri?: string | null;
  metadata: JsonObject;
}

export interface ExecutionCheckpointWrite {
  key: string;
  content?: JsonValue;
  metadata: JsonObject;
}

export interface ExecutionExternalEventRequest {
  name: string;
  runId?: string | null;
  payload?: JsonValue;
}

export interface ExecutionExternalEvent {
  id: string;
  name: string;
  runId?: string | null;
  raisedAtUtc: string;
  payload?: JsonValue;
}

export interface ExecutionTimer {
  id: string;
  name: string;
  runId?: string | null;
  fireAtUtc: string;
  createdAtUtc: string;
  payload?: JsonValue;
}

export interface ExecutionWaitResult {
  name: string;
  outcome: string;
  event?: ExecutionExternalEvent | null;
  timer?: ExecutionTimer | null;
}

export interface ExecutionExternalWorkerLeaseRequest {
  workerId: string;
  handlerIds: Array<string>;
  runId?: string | null;
  ttlSeconds: number;
}

export interface ExecutionExternalWorkerLease {
  leaseKey: string;
  leaseToken: string;
  workerId: string;
  run: ExecutionRun;
  acquiredAtUtc: string;
  expiresAtUtc: string;
}

export interface ExecutionExternalWorkerHeartbeatRequest {
  leaseKey: string;
  leaseToken: string;
  workerId: string;
  ttlSeconds: number;
}

export interface ExecutionExternalWorkerReportRequest {
  leaseKey: string;
  leaseToken: string;
  workerId: string;
  update: ExecutionRunUpdate;
}

export interface ExecutionExternalWorkerEventRequest {
  leaseKey: string;
  leaseToken: string;
  workerId: string;
  type: string;
  message?: string | null;
  severity: string;
  details?: JsonObject | null;
}

export interface ExecutionExternalWorkerArtifactRequest {
  leaseKey: string;
  leaseToken: string;
  workerId: string;
  artifact: ExecutionArtifactWrite;
}

export interface ExecutionExternalWorkerCheckpointRequest {
  leaseKey: string;
  leaseToken: string;
  workerId: string;
  checkpoint: ExecutionCheckpointWrite;
}

export interface ExecutionExternalWorkerCheckpointReadRequest {
  leaseKey: string;
  leaseToken: string;
  workerId: string;
  key: string;
}

export interface ExecutionExternalWorkerWaitRequest {
  leaseKey: string;
  leaseToken: string;
  workerId: string;
  kind: "external_event" | "timer";
  name: string;
  timeoutAtUtc?: string | null;
  fireAtUtc?: string | null;
  payload?: JsonValue;
}

export interface ExecutionExternalWorkerWaitResponse {
  run: ExecutionRun;
  suspended: boolean;
  outcome?: ExecutionWaitResult | null;
}

export interface ExecutionExternalWorkerCompletionRequest {
  leaseKey: string;
  leaseToken: string;
  workerId: string;
  result: ExecutionRunResult;
}

export interface ServerSecurityStatus {
  apiKeyRequired: boolean;
  apiKeyHeader: string;
  providerRunLimits: JsonObject;
}

export interface ServerReadinessReport {
  status: "ok" | "warning" | "failed" | "unknown";
  ready: boolean;
  summary: string;
  checkedAt: string;
  health: ServerHealthStatus;
  checks: Array<ServerReadinessCheck>;
  blockers: Array<string>;
  warnings: Array<string>;
  embedding: JsonObject;
  providers: ServerProviderReadinessSummary;
  operationalLimits: JsonObject;
}

export interface ServerReadinessCheck {
  id: string;
  status: "ok" | "warning" | "failed" | "unknown";
  message: string;
  details: JsonObject;
}

export interface ServerProviderReadinessSummary {
  providerCount: number;
  capabilityCount: number;
  callableCapabilityCount: number;
  readyCapabilityCount: number;
  unvalidatedCapabilityCount: number;
  networkProviderCount: number;
  authProviderCount: number;
}

export interface EmbeddingProviderDescriptor {
  provider: string;
  displayName: string;
  description: string;
  defaultModelId: string;
  defaultDimensions: number;
  local: boolean;
  cpuOnly: boolean;
  requiresNetwork: boolean;
  semanticQuality: string;
  defaultQueryPrefix: string | null;
  defaultPassagePrefix: string | null;
  defaultSymmetricPrefix: string | null;
}

export interface EmbeddingProviderGuidance {
  provider: string;
  displayName: string;
  semanticQuality: string;
  defaultDimensions: number;
  hardwareProfile: string;
  requiresModelFiles: boolean;
  realisticForSemanticRetrieval: boolean;
  defaultQueryPrefix?: string | null;
  defaultPassagePrefix?: string | null;
  recommendedFor: Array<string>;
  cautions: Array<string>;
  suggestedRetrievalProfiles: Array<string>;
  suggestedEvaluationVariants: Array<string>;
  selectionNotes: Array<string>;
}

export interface EmbeddingRequest {
  text?: string | null;
  texts?: Array<string> | null;
  purpose?: "query" | "passage" | "document" | "symmetric" | null;
  queryPrefix?: string | null;
  passagePrefix?: string | null;
  symmetricPrefix?: string | null;
}

export interface EmbeddingResponse {
  provider: string;
  modelId: string;
  dimensions: number;
  purpose: string;
  items: Array<EmbeddingResult>;
}

export interface EmbeddingJob {
  admission: AdmissionReceipt;
  id: string;
  status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "rejected";
  provider: string;
  modelId: string;
  dimensions: number;
  purpose: string;
  requestHash: string;
  createdAt: string;
  startedAt?: string | null;
  completedAt?: string | null;
  durationMs?: number | null;
  cancellationRequested: boolean;
  requested: number;
  attempted: number;
  succeeded: number;
  failed: number;
  currentIndex?: number | null;
  progress: number;
  failureClass?: string | null;
  error?: string | null;
  result?: EmbeddingResponse;
}

export interface EmbeddingResult {
  index: number;
  textLength: number;
  preparedTextLength: number;
  prefixApplied: boolean;
  prefixLength: number;
  values: Array<number>;
}

export interface ProviderProfile {
  id: string;
  displayName: string;
  family: string;
  profileVersion?: string;
  implementationVersion?: string;
  local: boolean;
  requiresNetwork: boolean;
  auth: string;
  configHash?: string | null;
  capabilities: Array<string>;
  [key: string]: unknown;
}

export interface ProviderCapabilityDescriptor {
  id: string;
  version?: string;
  operations: Array<string>;
  inputLimits?: JsonObject;
  outputLimits?: JsonObject;
  toolPolicy?: string;
  modePolicies?: Array<ProviderModePolicy>;
  unsupportedFeatures?: Array<string>;
  [key: string]: unknown;
}

export interface ProviderQualification {
  provider: string;
  capability: string;
  operationSet: Array<string>;
  configHash?: string | null;
  status: "unvalidated" | "validated" | "failed" | "unsupported";
  lastValidatedAt?: string | null;
  driftTriggers: Array<string>;
  unsupportedFeatures: Array<string>;
  evidenceRefs: Array<string>;
}

export interface ProviderQualificationRequest {
  capability?: string | null;
  mode?: string;
}

export interface ProviderDoctorResult {
  provider: string;
  status: "ok" | "warning" | "failed" | "unknown";
  summary: string;
  generatedAt: string;
  checks: Array<ProviderDoctorCheck>;
  metadata: JsonObject;
  [key: string]: unknown;
}

export interface ProviderDoctorCheck {
  id: string;
  status: "ok" | "warning" | "failed" | "unknown";
  message: string;
  details: JsonObject;
  [key: string]: unknown;
}

export interface ProviderCapabilityMatrix {
  generatedAt: string;
  capabilityIds: Array<string>;
  items: Array<ProviderCapabilityMatrixItem>;
  disabledProviders: Array<ProviderDisabledInfo>;
  failureClasses: Array<string>;
  operationalLimits: JsonObject;
  notes: Array<string>;
  [key: string]: unknown;
}

export interface ProviderCapabilityMatrixItem {
  provider: string;
  displayName: string;
  family: string;
  registered: boolean;
  enabled: boolean;
  registrationStatus: string;
  registrationHint?: string | null;
  local: boolean;
  requiresNetwork: boolean;
  auth: string;
  capabilityIds: Array<string>;
  capabilities: JsonObject;
  supportsModelListing: boolean;
  supportsQuota: boolean;
  supportsAsyncJobs: boolean;
  supportsArtifacts: boolean;
  artifactPolicy: string;
  failureSemantics: Array<string>;
  [key: string]: unknown;
}

export interface ProviderCapabilitySupport {
  supported: boolean;
  operations: Array<string>;
  modes: Array<string>;
  toolPolicy: string;
  unsupportedFeatures: Array<string>;
  [key: string]: unknown;
}

export interface ProviderReadinessEnvelope {
  generatedAt: string;
  items: Array<ProviderCapabilityReadiness>;
  disabledProviders: Array<ProviderDisabledInfo>;
}

export interface ProviderDisabledInfo {
  providerId: string;
  registrationStatus: string;
  enableLiveTargets: boolean;
  hint: string;
  [key: string]: unknown;
}

export interface ProviderModelListResult {
  provider: string;
  status: "succeeded" | "unsupported" | "failed";
  source: string;
  defaultModelId?: string | null;
  items: Array<ProviderModelDescriptor>;
  failureClass?: string | null;
  providerStatus?: string | null;
  generatedAt: string;
  [key: string]: unknown;
}

export interface ProviderModelDescriptor {
  id: string;
  displayName?: string | null;
  default: boolean;
  capabilities: Array<string>;
  metadata: JsonObject;
  [key: string]: unknown;
}

export interface ProviderQuotaResult {
  provider: string;
  status: "succeeded" | "unsupported" | "unavailable" | "failed";
  source: string;
  advisory: boolean;
  items: Array<ProviderQuotaBucket>;
  failureClass?: string | null;
  providerStatus?: string | null;
  generatedAt: string;
  metadata: JsonObject;
  [key: string]: unknown;
}

export interface ProviderQuotaBucket {
  limitId: string;
  limitName?: string | null;
  primary?: ProviderQuotaWindow | null;
  secondary?: ProviderQuotaWindow | null;
  rateLimitReachedType?: string | null;
  planType?: string | null;
  credits?: JsonObject | null;
  metadata: JsonObject;
  [key: string]: unknown;
}

export interface ProviderQuotaWindow {
  usedPercent?: number | null;
  remainingPercent?: number | null;
  windowDurationMins?: number | null;
  resetsAtUnixSeconds?: number | null;
  resetsAt?: string | null;
  [key: string]: unknown;
}

export interface ProviderCapabilityReadiness {
  provider: string;
  capability: string;
  registrationStatus: string;
  registrationHint?: string | null;
  operations: Array<string>;
  modes: Array<string>;
  configHash?: string | null;
  qualificationStatus: "unvalidated" | "validated" | "failed" | "unsupported";
  lastValidatedAt?: string | null;
  callable: boolean;
  ready: boolean;
  canRunUnvalidated: boolean;
  reason: string;
  evidenceRefs: Array<string>;
  driftTriggers: Array<string>;
  unsupportedFeatures: Array<string>;
  local: boolean;
  requiresNetwork: boolean;
  auth: string;
  authRequired: boolean;
  operationalLimits: JsonObject;
}

export interface ProviderModePolicy {
  id: string;
  allowedOutputKinds?: Array<string>;
  maxInputBytes: number;
  maxOutputBytes: number;
  toolPolicy: string;
  allowNetwork: boolean;
  allowSourceWrites: boolean;
  reviewRequired: boolean;
  traceRequired: boolean;
  timeoutSeconds: number;
}

export interface ProviderTargetDescriptor {
  profile: ProviderProfile;
  capabilities: Array<ProviderCapabilityDescriptor>;
}

export interface ProviderRunRequest {
  provider?: string | null;
  capability: string;
  operation?: string;
  mode?: string;
  modelId?: string | null;
  payload: AiChatPayload | AiExtractPayload | AiRerankPayload | AiReviewPayload | AiScaffoldPayload | AiToolPlanPayload | JsonObject;
  correlationId?: string;
  contextRefs?: Array<string>;
  timeoutSeconds?: number | null;
  maxOutputBytes?: number | null;
  artifactDirectory?: string | null;
}

export interface ProviderRunResult {
  status: "Succeeded" | "Failed" | "TimedOut" | "Rejected" | "Unsupported" | "NotConfigured" | "Cancelled";
  provider: string;
  capability: string;
  operation: string;
  mode: string;
  output: AiChatResult | AiExtractResult | AiRerankResult | AiReviewResult | AiScaffoldResult | AiToolPlanResult | JsonObject;
  failureClass?: string | null;
  providerStatus?: string | null;
  error?: string | null;
  rejection?: ProviderRunRejectionDiagnostic | null;
  trace?: ProviderTraceEvent | null;
}

export interface ProviderRunRejectionDiagnostic {
  source: "vyral_policy" | "vyral_guardrail" | "vyral_classification" | "provider_policy" | "provider_runtime" | "configuration" | "unsupported" | "unknown";
  category: string;
  message: string;
  contentUsable: boolean;
  parsedOutputPresent: boolean;
  structuredOutputAccepted: boolean;
  structuredOutputValidationStatus?: string | null;
  parsedOutputDisposition: "none" | "not_capability_output" | "quarantine_for_operator_review" | "debug_only";
  decisionAuthority: "vyral_preflight" | "vyral_policy" | "vyral_guardrail" | "vyral_structured_output_validation" | "provider_process_exit" | "provider_response_status" | "server_guardrail" | "unknown";
  processOutcome: "not_started" | "exit_zero" | "exit_nonzero" | "cancelled" | "timed_out" | "output_truncated" | "http_success" | "http_failure" | "unknown";
  retryable: boolean;
  retryRecommendation: "do_not_retry" | "retry_after_backoff" | "retry_with_smaller_input" | "retry_with_redacted_input" | "retry_with_stricter_structured_output_instructions" | "fix_configuration" | "use_supported_capability" | "operator_review";
  operatorReviewRecommended: boolean;
}

export interface ProviderRunJob {
  admission: AdmissionReceipt;
  id: string;
  status: "Succeeded" | "Failed" | "TimedOut" | "Rejected" | "Unsupported" | "NotConfigured" | "Cancelled" | "Queued" | "Running";
  provider: string;
  capability: string;
  operation: string;
  mode: string;
  correlationId: string;
  requestHash: string;
  createdAt: string;
  startedAt?: string | null;
  completedAt?: string | null;
  durationMs?: number | null;
  cancellationRequested: boolean;
  traceId?: string | null;
  failureClass?: string | null;
  providerStatus?: string | null;
  result?: ProviderRunResult | null;
}

export interface ProviderTraceEvent {
  traceId?: string;
  timestamp?: string;
  provider?: string;
  capability?: string;
  operation?: string;
  mode?: string;
  inputHash?: string | null;
  outputHash?: string | null;
  modelId?: string | null;
  adapterId?: string | null;
  configHash?: string | null;
  durationMs?: number;
  failureClass?: string | null;
  authorityBoundary?: string;
  artifactRefs?: Array<string>;
}

export interface AiChatPayload {
  messages?: Array<AiMessage>;
  system?: string | null;
  maxOutputChars?: number | null;
}

export interface AiChatResult {
  message: AiMessage;
  stopReason: string;
}

export interface AiExtractPayload {
  text: string;
  schema?: JsonObject | null;
  instructions?: string | null;
}

export interface AiExtractResult {
  data: JsonObject;
  validationStatus: string;
}

export interface AiRerankPayload {
  query: string;
  candidates: Array<AiRerankCandidate>;
  limit?: number | null;
}

export interface AiRerankResult {
  items: Array<AiRerankItem>;
  validationStatus: string;
}

export interface AiRerankCandidate {
  id: string;
  text: string;
  metadata?: JsonObject | null;
}

export interface AiRerankItem {
  id: string;
  rank: number;
  score: number;
}

export interface AiReviewPayload {
  prompt?: string | null;
  subject?: string | null;
  instructions?: string | null;
  references?: Array<AiReference>;
  maxFindings?: number | null;
}

export interface AiReviewResult {
  summary: string;
  findings: Array<AiReviewFinding>;
  validationStatus: string;
  references: Array<AiReference>;
}

export interface AiReviewFinding {
  id: string;
  severity: string;
  category?: string | null;
  message: string;
  location?: AiReviewLocation;
  evidenceRefs: Array<string>;
  confidence?: number | null;
}

export interface AiReviewLocation {
  path?: string | null;
  line?: number | null;
  column?: number | null;
  symbol?: string | null;
}

export interface AiScaffoldPayload {
  prompt: string;
  instructions?: string | null;
  target?: string | null;
  references?: Array<AiReference>;
  allowedPaths?: Array<string>;
  maxArtifacts?: number | null;
}

export interface AiScaffoldResult {
  summary: string;
  artifacts: Array<AiScaffoldArtifact>;
  validationStatus: string;
  references: Array<AiReference>;
}

export interface AiScaffoldArtifact {
  path: string;
  kind: string;
  action: string;
  content?: string | null;
  contentHash?: string | null;
  evidenceRefs: Array<string>;
  metadata?: JsonObject | null;
}

export interface AiReference {
  id: string;
  kind: string;
  uri?: string | null;
  contentHash?: string | null;
  label?: string | null;
  metadata?: JsonObject | null;
}

export interface AiToolPlanPayload {
  prompt: string;
  tools?: Array<AiToolDefinition>;
}

export interface AiToolPlanResult {
  calls: Array<AiToolCallProposal>;
  validationStatus: string;
}

export interface AiToolCallProposal {
  tool: string;
  arguments: JsonObject;
  requiresApproval: boolean;
  rationale?: string | null;
}

export interface AiToolDefinition {
  name: string;
  description?: string | null;
  inputSchema?: JsonObject | null;
}

export interface AiMessage {
  role: string;
  content: string;
  contentBlocks?: Array<JsonObject> | null;
}

export interface ProblemDetails {
  type?: string | null;
  title?: string | null;
  status?: number | null;
  detail?: string | null;
  instance?: string | null;
  admission?: AdmissionReceipt | null;
  [key: string]: unknown;
}

export interface VyralGraphCollectionImportPreflightResult {
  collection?: string;
  generatedAt?: string;
  valid?: boolean;
  readyToImport?: boolean;
  graphId?: string;
  namespace?: string;
  tenantId?: string;
  partitionKey?: string;
  collectionExists?: boolean;
  collectionPolicyStatus?: string;
  wouldCreateCollection?: boolean;
  wouldReplaceCollection?: boolean;
  wouldAllowNonGraphPolicy?: boolean;
  createCollectionIfMissing?: boolean;
  replaceExisting?: boolean;
  allowNonGraphPolicy?: boolean;
  nodeCount?: number;
  edgeCount?: number;
  assertionCount?: number;
  reviewCount?: number;
  projectionCount?: number;
  recordCount?: number;
  maxRecords?: number;
  warningCount?: number;
  warnings?: Array<string>;
  errorCount?: number;
  errors?: Array<string>;
}

export interface VyralGraphDoctorRequest {
  graphId?: string | null;
  namespace?: string | null;
  tenantId?: string | null;
  partitionKey?: string | null;
  targetCollection?: string | null;
  targetPartitionKeys?: Array<string>;
  seedJsonPointers?: Array<string>;
  maxGraphRecords?: number | null;
  maxTargetRecords?: number;
  allowPartialGraph?: boolean;
  includeAnomalies?: boolean;
  anomalyLimit?: number;
}

export interface VyralGraphSeedCoverage {
  targetCollection?: string;
  targetRecordCount?: number;
  targetTruncated?: boolean;
  seedJsonPointers?: Array<string>;
  recordsWithSeedMetadataCount?: number;
  seedValueCount?: number;
  uniqueSeedValueCount?: number;
  resolvedSeedNodeCount?: number;
  unresolvedSeedNodeCount?: number;
  seedCoverage?: number;
  resolvedSeedCoverage?: number;
  resolvedSeedNodeIds?: Array<string>;
  unresolvedSeedNodeIds?: Array<string>;
}

export interface VyralGraphDoctorResult {
  collection?: string;
  generatedAt?: string;
  ready?: boolean;
  status?: string;
  failureMode?: string | null;
  graphReady?: boolean;
  graphRecordCount?: number;
  graphNodeCount?: number;
  graphEdgeCount?: number;
  graphTruncated?: boolean;
  inspection?: VyralGraphCollectionInspectionResult | null;
  seedCoverage?: VyralGraphSeedCoverage | null;
  recommendedActions?: Array<string>;
}

export interface RagContextGraphSeedDiagnostic {
  recordId?: string | null;
  partitionKey?: string | null;
  pointer?: string;
  found?: boolean;
  rawValue?: string | null;
  normalizedValue?: string | null;
  skippedReason?: string | null;
  accepted?: boolean;
}

export interface RagContextGraphExpansionSummary {
  expansionAttempted?: boolean;
  expansionEnabled?: boolean;
  collection?: string;
  graphId?: string | null;
  namespace?: string | null;
  tenantId?: string | null;
  partitionKey?: string | null;
  status?: string;
  skippedReason?: string | null;
  profileId?: string | null;
  maxDepth?: number;
  nodeLimit?: number;
  edgeLimit?: number;
  maxRecords?: number | null;
  maxGraphContextChars?: number;
  maxGraphProvenanceItems?: number;
  retrievedRecordIds?: Array<string>;
  sourceRecordIdsTouched?: Array<string>;
  seedJsonPointers?: Array<string>;
  seedCandidateCount?: number;
  seedCount?: number;
  seedNodeIds?: Array<string>;
  droppedSeedCount?: number;
  nodesAdded?: number;
  edgesAdded?: number;
  relationshipsAdded?: number;
  sourceRecordCount?: number;
  sourceTruncated?: boolean;
  exportedRecordCount?: number;
  estimatedRequiredRecordCount?: number | null;
  limitsHit?: Array<string>;
  groundingStatus?: string;
  graphContextInfluencedContextText?: boolean;
  contextTextTruncated?: boolean;
  omittedProvenanceCount?: number;
}

export interface GraphJob {
  admission: AdmissionReceipt;
  id: string;
  kind: "import" | "inspect" | "doctor";
  status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "rejected";
  collection: string;
  requestHash: string;
  createdAt: string;
  startedAt?: string | null;
  completedAt?: string | null;
  durationMs?: number | null;
  cancellationRequested: boolean;
  requested: number;
  attempted: number;
  succeeded: number;
  failed: number;
  progress: number;
  graphId?: string | null;
  partitionKey?: string | null;
  recordCount: number;
  nodeCount: number;
  edgeCount: number;
  assertionCount: number;
  reviewCount: number;
  projectionCount: number;
  warningCount: number;
  errorCount: number;
  anomalyCount: number;
  failureClass?: string | null;
  error?: string | null;
  importResult?: VyralGraphCollectionImportResult;
  inspectionResult?: VyralGraphCollectionInspectionResult;
  doctorResult?: VyralGraphDoctorResult;
}

export interface RagIngestionJob {
  admission: AdmissionReceipt;
  id: string;
  kind: "text" | "batch";
  status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "rejected";
  collection: string;
  requestHash: string;
  createdAt: string;
  startedAt?: string | null;
  completedAt?: string | null;
  durationMs?: number | null;
  cancellationRequested: boolean;
  requested: number;
  attempted: number;
  succeeded: number;
  failed: number;
  currentIndex?: number | null;
  currentDocumentId?: string | null;
  currentPartitionKey?: string | null;
  progress: number;
  textLength: number;
  chunkCount: number;
  deletedStaleCount: number;
  createdCount: number;
  updatedCount: number;
  reusedCount: number;
  vectorGeneratedCount: number;
  vectorReusedCount: number;
  deduplicatedCount: number;
  failureClass?: string | null;
  error?: string | null;
  textResult?: RagIngestTextResult;
  batchResult?: RagIngestTextBatchResult;
}

export interface RagContextGraphEvaluationFailureModes {
  retrievalMiss?: boolean;
  seedMiss?: boolean;
  graphNotFound?: boolean;
  traversalEmpty?: boolean;
  expectedNodeMissing?: boolean;
  expectedEdgeMissing?: boolean;
  expectedProvenanceMissing?: boolean;
  sourceGroundingFailed?: boolean;
  graphContextTextMissing?: boolean;
  contextTextTruncated?: boolean;
  budgetTruncated?: boolean;
}

export interface VyralRequestOptions {
  headers?: HeadersInit;
  signal?: AbortSignal;
  timeoutMs?: number;
  correlationId?: string;
  idempotencyKey?: string;
}

export interface VyralClientOptions extends VyralRequestOptions {
  fetch?: typeof fetch;
  apiKey?: string;
  bearerToken?: string;
  maxRetries?: number;
  retryBackoffMs?: number;
}

export class VyralClientError extends Error {
  readonly status: number;
  readonly body: string;
  readonly problem: ProblemDetails | null;
  readonly admission: AdmissionReceipt | null;
  readonly failureClass?: string;
  readonly type: string | null;
  readonly title: string | null;
  readonly detail: string | null;
  readonly instance: string | null;
  readonly problemStatus: number | null;
  readonly retryAfter: string | null;
  readonly correlationId: string | null;
  constructor(status: number, body: string, options?: Record<string, unknown>);
  static timeout(detail: string): VyralClientError;
  static cancelled(detail?: string): VyralClientError;
  isMissingCollection(): boolean;
  isAuthError(): boolean;
  isValidationError(): boolean;
  isTimeout(): boolean;
  isCancelled(): boolean;
  isTransient(): boolean;
}

export const TERMINAL_EXECUTION_RUN_STATUSES: readonly ["succeeded", "failed", "cancelled", "rejected", "timed_out"];
export const RETRIEVAL_PROFILES: Readonly<Record<string, string>>;
export const EVIDENCE_BRIEF_SCHEMA: "vyral.evidence-brief.v1";
export const EVIDENCE_BRIEF_DOCUMENT_TYPE: "vyral.evidence-brief";
export const EVIDENCE_BRIEF_CHANGED_EVENT_TOPIC: "vyral.evidence-brief.changed";

export function isProviderRunSucceeded(result: JsonObject): boolean;
export function getProviderRunRejection(result: JsonObject): ProviderRunRejectionDiagnostic | null;
export function isProviderRunOutputUsable(result: JsonObject): boolean;
export function isExecutionRunTerminal(runOrStatus: JsonObject): boolean;
export function buildRagCollectionPolicy(collection: string, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildEvidenceBriefTransaction(tenantId: string, idempotencyKey: string, brief: JsonObject, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildVerifiedRetrievalRequest(query: string, collections: string[], options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildRetrievalProfileRequest(profile: string, query: string, collections: string[], options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildRetrievalEvaluationExpectedMatch(idOrMatch: JsonObject, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildRetrievalEvaluationHardNegative(idOrMatch: JsonObject, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildRetrievalEvaluationCase(name: string, request: JsonObject, expected: JsonObject, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildRetrievalEvaluationRequest(cases: JsonObject[], options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildRetrievalEvaluationVariant(id: string, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildRetrievalEvaluationComparisonRequest(cases: JsonObject[], variants: JsonObject[], options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildRagTextIngestionRequest(text: string, partitionKey: string, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildRagContextRequest(query: string, collections: string[], options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildGraphCollectionImportRequest(envelope: JsonObject, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildGraphCollectionExportRequest(options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildGraphTraversalRequest(startNodeIds: string[], options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildGraphInspectionRequest(options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildGraphDoctorRequest(options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildGraphExpansionOptions(collection: string, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildGraphScope(graphId: string, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildGraphSourceSpan(sourceRef: JsonObject, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildGraphNode(id: string, type: JsonObject, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildGraphEdge(id: string, sourceId: string, targetId: string, predicate: string, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildGraphAssertion(id: string, subjectId: string, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildGraphReview(id: string, subjectId: string, status: string, reviewer: string, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildGraphEnvelope(scope: JsonObject, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function stampGraphNodeMetadata(record: JsonObject, graphNodeId: string, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildRerankOptions(options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildProviderRunRequest(capability: string, payload: JsonObject, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildProviderChatRequest(messages: JsonObject[], options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildProviderExtractRequest(text: string, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildProviderRerankRequest(query: string, candidates: JsonObject[], options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildProviderReviewRequest(options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildProviderScaffoldRequest(prompt: string, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function buildProviderToolPlanRequest(prompt: string, options?: VyralRequestOptions & Record<string, unknown>): JsonObject;
export function summarizeRagIngestResult(result?: JsonObject): JsonObject;
export function compareRagIngestResults(planned?: JsonObject, committed?: JsonObject): JsonObject;

export class VyralClient {
  readonly baseUrl: string;
  constructor(baseUrl?: string, options?: VyralClientOptions);
  withOptions(options?: VyralClientOptions): VyralClient;
  health(): Promise<ServerHealthStatus>;
  readiness(): Promise<ServerReadinessReport>;
  ingestRecordArtifact(manifest: ArtifactRecordIngestManifest, artifact: Blob | ArrayBuffer | ArrayBufferView, options?: VyralRequestOptions & Record<string, unknown>): Promise<ExecutionRun>;
  openApiContract(): Promise<JsonObject>;
  getPublicSchemaContract(): Promise<JsonObject>;
  listCanonicalMigrations(): Promise<Array<CanonicalMigrationReceipt>>;
  getCanonicalPreflight(): Promise<CanonicalPreflightReport>;
  probeCanonicalDataPlane(): Promise<CanonicalPreflightReport>;
  applyCanonicalMigrations(migrations: JsonObject[]): Promise<null>;
  commitCanonicalTransaction(tenantId: string, request: CanonicalTransactionRequest): Promise<CanonicalTransactionResult>;
  storeEvidenceBrief(tenantId: string, brief: JsonObject, options?: VyralRequestOptions & Record<string, unknown>): Promise<JsonValue>;
  getEvidenceBrief(tenantId: string, briefId: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<JsonValue>;
  getCanonicalDocument(tenantId: string, documentType: string, id: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<CanonicalDocument>;
  queryCanonicalDocuments(tenantId: string, query: CanonicalDocumentQuery): Promise<CanonicalDocumentQueryResult>;
  iterateCanonicalDocuments(tenantId: string, query?: string, options?: VyralRequestOptions & Record<string, unknown>): AsyncIterable<CanonicalDocument>;
  queryAllCanonicalDocuments(tenantId: string, query?: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<CanonicalDocument[]>;
  listCanonicalDocumentRevisions(tenantId: string, documentType: string, id: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<Array<CanonicalDocumentRevision>>;
  leaseCanonicalOutbox(tenantId: string, request: CanonicalOutboxLeaseRequest): Promise<Array<CanonicalOutboxLease>>;
  queryCanonicalOutbox(tenantId: string, query: CanonicalOutboxQuery): Promise<CanonicalOutboxQueryResult>;
  renewCanonicalOutboxLease(tenantId: string, eventId: string, request: CanonicalOutboxLeaseRenewalRequest): Promise<CanonicalOutboxLeaseRenewal>;
  acknowledgeCanonicalOutbox(tenantId: string, eventId: string, leaseToken: string): Promise<null>;
  releaseCanonicalOutbox(tenantId: string, eventId: string, request: CanonicalOutboxNackRequest): Promise<null>;
  replayCanonicalOutbox(tenantId: string, eventId: string, request: CanonicalOutboxReplayRequest): Promise<null>;
  exportCanonicalTenant(tenantId: string): Promise<CanonicalTenantSnapshot>;
  restoreCanonicalTenant(tenantId: string, snapshot: JsonObject, expectedContentHash: string | null): Promise<null>;
  listGraphProviderShapes(): Promise<Array<VyralGraphProviderShape>>;
  getGraphProviderShape(providerId: string): Promise<VyralGraphProviderShape>;
  listEmbeddingProviders(): Promise<Array<EmbeddingProviderDescriptor>>;
  listEmbeddingProviderGuidance(): Promise<Array<EmbeddingProviderGuidance>>;
  getEmbeddingProviderDoctor(): Promise<ProviderDoctorResult>;
  getExecutionRuntime(): Promise<ExecutionRuntimeSurface>;
  getEffectiveExecutionRuntime(options?: VyralRequestOptions & Record<string, unknown>): Promise<EffectiveExecutionRuntimeSurface>;
  getExecutionRuntimeMaintenance(): Promise<ExecutionMaintenanceStatus>;
  pruneExecutionRuntimeMaintenance(options?: VyralRequestOptions & Record<string, unknown>): Promise<ExecutionMaintenancePruneResult>;
  reconcileExecutionRuntimeDispatch(options?: VyralRequestOptions & Record<string, unknown>): Promise<ExecutionMaintenanceDispatchReconcileResult>;
  leaseExternalExecutionRun(request: ExecutionExternalWorkerLeaseRequest): Promise<ExecutionExternalWorkerLease | null>;
  heartbeatExternalExecutionLease(request: ExecutionExternalWorkerHeartbeatRequest): Promise<ExecutionExternalWorkerLease>;
  reportExternalExecutionLease(request: ExecutionExternalWorkerReportRequest): Promise<ExecutionRun>;
  recordExternalExecutionLeaseEvent(request: ExecutionExternalWorkerEventRequest): Promise<null>;
  putExternalExecutionLeaseArtifact(request: ExecutionExternalWorkerArtifactRequest): Promise<ExecutionArtifact>;
  putExternalExecutionLeaseCheckpoint(request: ExecutionExternalWorkerCheckpointRequest): Promise<ExecutionCheckpoint>;
  getExternalExecutionLeaseCheckpoint(request: ExecutionExternalWorkerCheckpointReadRequest): Promise<ExecutionCheckpoint>;
  waitExternalExecutionLease(request: ExecutionExternalWorkerWaitRequest): Promise<ExecutionExternalWorkerWaitResponse>;
  completeExternalExecutionLease(request: ExecutionExternalWorkerCompletionRequest): Promise<ExecutionRun>;
  listExecutionRuns(options?: VyralRequestOptions & Record<string, unknown>): Promise<Array<ExecutionRun>>;
  startExecutionRun(request: ExecutionRunRequest, options?: VyralRequestOptions & Record<string, unknown>): Promise<ExecutionRun>;
  raiseExecutionEvent(runId: string, request: ExecutionExternalEventRequest): Promise<ExecutionExternalEvent>;
  getExecutionRun(runId: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<ExecutionRun>;
  cancelExecutionRun(runId: string): Promise<ExecutionRun>;
  waitExecutionRun(runId: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<JsonValue>;
  getExecutionRunHistory(runId: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<Array<ExecutionTraceEvent>>;
  listExecutionRunArtifacts(runId: string): Promise<Array<ExecutionArtifact>>;
  getExecutionRunArtifact(runId: string, artifactRef: string): Promise<ExecutionArtifact>;
  getExecutionRunCheckpoint(runId: string, key: string): Promise<ExecutionCheckpoint>;
  listProviders(): Promise<Array<ProviderProfile>>;
  getProviderCapabilityMatrix(): Promise<ProviderCapabilityMatrix>;
  getProvider(provider: string): Promise<ProviderTargetDescriptor>;
  listProviderDoctor(): Promise<Array<ProviderDoctorResult>>;
  getProviderDoctor(provider: string): Promise<ProviderDoctorResult>;
  listProviderReadiness(): Promise<ProviderReadinessEnvelope>;
  getProviderReadiness(provider: string): Promise<ProviderReadinessEnvelope>;
  listProviderQuotas(): Promise<Array<ProviderQuotaResult>>;
  getProviderQuota(provider: string): Promise<ProviderQuotaResult>;
  listProviderQualifications(provider: string): Promise<Array<ProviderQualification>>;
  listProviderModels(provider: string): Promise<ProviderModelListResult>;
  qualifyProvider(provider: string, request?: ProviderQualificationRequest): Promise<Array<ProviderQualification>>;
  runProvider(provider: string, request: ProviderRunRequest, options?: VyralRequestOptions & Record<string, unknown>): Promise<ProviderRunJob>;
  runProviderExtract(provider: string, text: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<JsonValue>;
  startProviderJob(provider: string, request: ProviderRunRequest, options?: VyralRequestOptions & Record<string, unknown>): Promise<ProviderRunJob>;
  listProviderJobs(options?: VyralRequestOptions & Record<string, unknown>): Promise<Array<ProviderRunJob>>;
  getProviderJob(id: string): Promise<ProviderRunJob>;
  cancelProviderJob(id: string): Promise<ProviderRunJob>;
  waitProviderJob(id: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<JsonValue>;
  embedText(text: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<JsonValue>;
  embedTexts(texts: string[], options?: VyralRequestOptions & Record<string, unknown>): Promise<EmbeddingResponse>;
  startEmbeddingJob(request: EmbeddingRequest, options?: VyralRequestOptions & Record<string, unknown>): Promise<EmbeddingJob>;
  listEmbeddingJobs(options?: VyralRequestOptions & Record<string, unknown>): Promise<Array<EmbeddingJob>>;
  getEmbeddingJob(id: string): Promise<EmbeddingJob>;
  cancelEmbeddingJob(id: string): Promise<EmbeddingJob>;
  waitEmbeddingJob(id: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<JsonValue>;
  listCollections(): Promise<Array<string>>;
  createCollection(policy: RecordCollectionPolicy, options?: VyralRequestOptions & Record<string, unknown>): Promise<ExecutionRun>;
  createRagCollection(collection: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<JsonValue>;
  getCollectionPolicy(collection: string): Promise<RecordCollectionPolicy>;
  exportCollection(collection: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<CollectionExportEnvelope>;
  importCollection(collection: string, snapshot: JsonObject, options?: VyralRequestOptions & Record<string, unknown>): Promise<RecordImportJob>;
  startCollectionImportJob(collection: string, snapshot: JsonObject, options?: VyralRequestOptions & Record<string, unknown>): Promise<RecordImportJob>;
  importGraphEnvelope(collection: string, envelope: JsonObject, options?: VyralRequestOptions & Record<string, unknown>): Promise<GraphJob>;
  preflightGraphImport(collection: string, envelope: JsonObject, options?: VyralRequestOptions & Record<string, unknown>): Promise<VyralGraphCollectionImportPreflightResult>;
  exportGraphEnvelope(collection: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<VyralGraphCollectionExportResult>;
  traverseGraph(collection: string, startNodeIds: string[], options?: VyralRequestOptions & Record<string, unknown>): Promise<VyralGraphTraversalResult>;
  inspectGraph(collection: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<VyralGraphCollectionInspectionResult>;
  doctorGraph(collection: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<VyralGraphDoctorResult>;
  startGraphImportJob(collection: string, request: VyralGraphCollectionImportRequest, options?: VyralRequestOptions & Record<string, unknown>): Promise<GraphJob>;
  startGraphInspectionJob(collection: string, request: VyralGraphCollectionInspectionRequest, options?: VyralRequestOptions & Record<string, unknown>): Promise<GraphJob>;
  startGraphDoctorJob(collection: string, request: VyralGraphDoctorRequest, options?: VyralRequestOptions & Record<string, unknown>): Promise<GraphJob>;
  listGraphJobs(options?: VyralRequestOptions & Record<string, unknown>): Promise<Array<GraphJob>>;
  getGraphJob(id: string): Promise<GraphJob>;
  cancelGraphJob(id: string): Promise<GraphJob>;
  waitGraphJob(id: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<JsonValue>;
  inspectCollection(collection: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<CollectionInspectionResult>;
  deleteCollection(collection: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<ExecutionRun>;
  upsertRecord(collection: string, record: VyralRecord): Promise<VyralRecord>;
  upsertRecords(collection: string, records: JsonObject[], options?: VyralRequestOptions & Record<string, unknown>): Promise<RecordImportJob>;
  startRecordBatchUpsertJob(collection: string, records: JsonObject[], options?: VyralRequestOptions & Record<string, unknown>): Promise<RecordImportJob>;
  listRecordImportJobs(options?: VyralRequestOptions & Record<string, unknown>): Promise<Array<RecordImportJob>>;
  getRecordImportJob(id: string): Promise<RecordImportJob>;
  cancelRecordImportJob(id: string): Promise<RecordImportJob>;
  waitRecordImportJob(id: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<JsonValue>;
  getRecord(collection: string, partitionKey: string, id: string): Promise<VyralRecord>;
  deleteRecord(collection: string, partitionKey: string, id: string): Promise<null>;
  queryRecords(collection: string, query: QueryEnvelope): Promise<RecordQueryResult>;
  iterateRecords(collection: string, query?: string, options?: VyralRequestOptions & Record<string, unknown>): AsyncIterable<VyralRecord>;
  queryAllRecords(collection: string, query?: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<VyralRecord[]>;
  searchRecords(collection: string, query: QueryEnvelope): Promise<RecordSearchResult>;
  iterateSearchRecords(collection: string, query?: string, options?: VyralRequestOptions & Record<string, unknown>): AsyncIterable<VyralRecordMatch>;
  searchAllRecords(collection: string, query?: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<VyralRecordMatch[]>;
  retrieve(request: RetrievalRequest): Promise<RetrievalResultEnvelope>;
  listRetrievalProfiles(): Promise<Array<RetrievalProfileDescriptor>>;
  evaluateRetrieval(request: RetrievalEvaluationRequest): Promise<RetrievalEvaluationResult>;
  compareRetrievalEvaluations(request: RetrievalEvaluationComparisonRequest): Promise<RetrievalEvaluationComparisonResult>;
  startRetrievalEvaluationJob(request: RetrievalEvaluationRequest, options?: VyralRequestOptions & Record<string, unknown>): Promise<RetrievalEvaluationJob>;
  startRetrievalEvaluationComparisonJob(request: RetrievalEvaluationComparisonRequest, options?: VyralRequestOptions & Record<string, unknown>): Promise<RetrievalEvaluationJob>;
  listRetrievalEvaluationJobs(options?: VyralRequestOptions & Record<string, unknown>): Promise<Array<RetrievalEvaluationJob>>;
  getRetrievalEvaluationJob(id: string): Promise<RetrievalEvaluationJob>;
  cancelRetrievalEvaluationJob(id: string): Promise<RetrievalEvaluationJob>;
  waitRetrievalEvaluationJob(id: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<JsonValue>;
  buildRagContext(request: RagContextRequest): Promise<RagContextEnvelope>;
  evaluateRagContext(request: RagContextEvaluationRequest): Promise<RagContextEvaluationResult>;
  buildRagPrompt(request: RagPromptRequest): Promise<RagPromptEnvelope>;
  ingestRagText(collection: string, request: RagIngestTextRequest, options?: VyralRequestOptions & Record<string, unknown>): Promise<RagIngestTextResult | RagIngestionJob>;
  planRagTextIngestion(collection: string, request: JsonObject): Promise<JsonValue>;
  commitRagTextIngestion(collection: string, request: JsonObject, plannedResult?: JsonObject | null, options?: VyralRequestOptions & Record<string, unknown>): Promise<JsonValue>;
  ingestRagTexts(collection: string, items: JsonObject[], options?: VyralRequestOptions & Record<string, unknown>): Promise<RagIngestionJob>;
  startRagTextIngestionJob(collection: string, request: RagIngestTextRequest, options?: VyralRequestOptions & Record<string, unknown>): Promise<RagIngestionJob>;
  startRagTextBatchIngestionJob(collection: string, request: RagIngestTextBatchRequest, options?: VyralRequestOptions & Record<string, unknown>): Promise<RagIngestionJob>;
  listRagIngestionJobs(options?: VyralRequestOptions & Record<string, unknown>): Promise<Array<RagIngestionJob>>;
  getRagIngestionJob(id: string): Promise<RagIngestionJob>;
  cancelRagIngestionJob(id: string): Promise<RagIngestionJob>;
  waitRagIngestionJob(id: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<JsonValue>;
  listObjects(container: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<ObjectListResult>;
  putObject(container: string, key: string, content: BodyInit, options?: VyralRequestOptions & Record<string, unknown>): Promise<ObjectInfo>;
  getObject(container: string, key: string): Promise<string>;
  deleteObject(container: string, key: string, options?: VyralRequestOptions & Record<string, unknown>): Promise<null>;
  listTraces(options?: VyralRequestOptions & Record<string, unknown>): Promise<Array<TraceRecord>>;
  pruneTraces(request: TracePruneRequest): Promise<TracePruneResult>;
  summarizeTraces(options?: VyralRequestOptions & Record<string, unknown>): Promise<TraceSummary>;
  exportTraces(request?: TraceExportRequest): Promise<TraceExportBundle>;
  getTrace(id: string): Promise<TraceRecord>;
}
