"""Cross-collection vector, lexical, hybrid, and reranked retrieval."""

from .models import (
    EmbeddingOptions,
    HybridSearchOptions,
    RerankOptions,
    RetrievalMatch,
    RetrievalRequest,
    RetrievalResultEnvelope,
    RetrievalVectorFieldQuery,
)
from .profiles import apply_retrieval_profile, get_retrieval_profiles
from .evaluation import (
    ComparisonProgress,
    EvaluationProgress,
    RetrievalEvaluationService,
)
from .evaluation_models import (
    MAX_EVALUATION_CASES,
    MAX_EVALUATION_K,
    MAX_EVALUATION_VARIANTS,
    MAX_EXPECTED_MATCHES,
    MAX_HARD_NEGATIVES,
    RetrievalEvaluationCase,
    RetrievalEvaluationCaseResult,
    RetrievalEvaluationComparisonRequest,
    RetrievalEvaluationComparisonResult,
    RetrievalEvaluationExpectedMatch,
    RetrievalEvaluationExpectedResult,
    RetrievalEvaluationHardNegativeMatch,
    RetrievalEvaluationHardNegativeResult,
    RetrievalEvaluationMetricDeltas,
    RetrievalEvaluationMetrics,
    RetrievalEvaluationRequest,
    RetrievalEvaluationResult,
    RetrievalEvaluationTopResult,
    RetrievalEvaluationVariant,
    RetrievalEvaluationVariantResult,
)
from .service import (
    MAX_VECTOR_FIELDS,
    RerankingService,
    RetrievalService,
    TokenOverlapReranker,
)

__all__ = [
    "EmbeddingOptions",
    "ComparisonProgress",
    "EvaluationProgress",
    "HybridSearchOptions",
    "MAX_VECTOR_FIELDS",
    "MAX_EVALUATION_CASES",
    "MAX_EVALUATION_K",
    "MAX_EVALUATION_VARIANTS",
    "MAX_EXPECTED_MATCHES",
    "MAX_HARD_NEGATIVES",
    "RerankOptions",
    "RerankingService",
    "RetrievalMatch",
    "RetrievalEvaluationCase",
    "RetrievalEvaluationCaseResult",
    "RetrievalEvaluationComparisonRequest",
    "RetrievalEvaluationComparisonResult",
    "RetrievalEvaluationExpectedMatch",
    "RetrievalEvaluationExpectedResult",
    "RetrievalEvaluationHardNegativeMatch",
    "RetrievalEvaluationHardNegativeResult",
    "RetrievalEvaluationMetricDeltas",
    "RetrievalEvaluationMetrics",
    "RetrievalEvaluationRequest",
    "RetrievalEvaluationResult",
    "RetrievalEvaluationService",
    "RetrievalEvaluationTopResult",
    "RetrievalEvaluationVariant",
    "RetrievalEvaluationVariantResult",
    "RetrievalRequest",
    "RetrievalResultEnvelope",
    "RetrievalService",
    "RetrievalVectorFieldQuery",
    "TokenOverlapReranker",
    "apply_retrieval_profile",
    "get_retrieval_profiles",
]
