<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Vyral.Abstractions\Vyral.Abstractions.csproj" />
    <ProjectReference Include="..\Vyral.Execution\Vyral.Execution.csproj" />
    <ProjectReference Include="..\Vyral.Pgvector\Vyral.Pgvector.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageReference Include="Google.Apis.Core" Version="1.76.0" />
    <PackageReference Include="Google.Cloud.Firestore" Version="4.4.0" />
    <PackageReference Include="Google.Cloud.Storage.V1" Version="4.15.0" />
    <PackageReference Include="Google.Cloud.Tasks.V2" Version="3.6.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
