using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Amazon.Runtime;

namespace Vyral.Aws;

/// <summary>Minimal transport boundary so projection behavior is testable without an OpenSearch domain.</summary>
public interface IOpenSearchTransport
{
    Task<OpenSearchTransportResponse> SendAsync(
        HttpMethod method,
        string pathAndQuery,
        string? jsonBody,
        CancellationToken ct = default);
}

public sealed class OpenSearchTransportResponse
{
    public int StatusCode { get; init; }
    public string Body { get; init; } = string.Empty;
}

/// <summary>
/// AWS Signature Version 4 transport for Amazon OpenSearch Service data-plane
/// requests. It signs only fixed relative request paths generated by Vyral,
/// never accepts a caller-supplied destination URI, and never records request
/// bodies or credentials in exceptions.
/// </summary>
public sealed class AwsSigV4OpenSearchTransport : IOpenSearchTransport, IDisposable
{
    private const int MaximumResponseBytes = 512 * 1024;
    private readonly HttpClient _httpClient;
    private readonly bool _ownsHttpClient;
    private readonly AWSCredentials _credentials;
    private readonly Uri _endpoint;
    private readonly string _region;
    private readonly string _service;
    private readonly Func<DateTime> _utcNow;

    public AwsSigV4OpenSearchTransport(
        Uri endpoint,
        string region,
        AWSCredentials credentials,
        string service = "es",
        HttpClient? httpClient = null,
        Func<DateTime>? utcNow = null)
    {
        if (endpoint is null) throw new ArgumentNullException(nameof(endpoint));
        if (!endpoint.IsAbsoluteUri || endpoint.UserInfo.Length > 0 || endpoint.Query.Length > 0 || endpoint.Fragment.Length > 0 || endpoint.AbsolutePath != "/")
            throw new ArgumentException("The OpenSearch endpoint must be an absolute credential-free URI without query or fragment.", nameof(endpoint));
        if (endpoint.Scheme != Uri.UriSchemeHttps && !string.Equals(endpoint.Host, "localhost", StringComparison.OrdinalIgnoreCase))
            throw new ArgumentException("The OpenSearch endpoint must use HTTPS unless it is localhost for a test.", nameof(endpoint));
        if (string.IsNullOrWhiteSpace(region)) throw new ArgumentException("AWS region is required.", nameof(region));
        if (string.IsNullOrWhiteSpace(service) || service.Any(c => !char.IsAsciiLetterOrDigit(c) && c != '-'))
            throw new ArgumentException("AWS signing service is invalid.", nameof(service));

        _endpoint = new Uri(endpoint.GetLeftPart(UriPartial.Authority) + "/", UriKind.Absolute);
        _region = region;
        _service = service;
        _credentials = credentials ?? throw new ArgumentNullException(nameof(credentials));
        _httpClient = httpClient ?? new HttpClient();
        _ownsHttpClient = httpClient is null;
        _utcNow = utcNow ?? (() => DateTime.UtcNow);
    }

    public async Task<OpenSearchTransportResponse> SendAsync(
        HttpMethod method,
        string pathAndQuery,
        string? jsonBody,
        CancellationToken ct = default)
    {
        if (method is null) throw new ArgumentNullException(nameof(method));
        if (string.IsNullOrWhiteSpace(pathAndQuery) || !pathAndQuery.StartsWith("/", StringComparison.Ordinal) ||
            pathAndQuery.StartsWith("//", StringComparison.Ordinal) || pathAndQuery.Contains("#", StringComparison.Ordinal))
        {
            throw new ArgumentException("OpenSearch requests must use a safe absolute path without a fragment.", nameof(pathAndQuery));
        }

        var credentials = await _credentials.GetCredentialsAsync().ConfigureAwait(false);
        var now = _utcNow().ToUniversalTime();
        var dateStamp = now.ToString("yyyyMMdd", CultureInfo.InvariantCulture);
        var amzDate = now.ToString("yyyyMMdd'T'HHmmss'Z'", CultureInfo.InvariantCulture);
        var payload = jsonBody is null ? Array.Empty<byte>() : Encoding.UTF8.GetBytes(jsonBody);
        var payloadHash = Sha256Hex(payload);
        var requestUri = new Uri(_endpoint, pathAndQuery);
        if (!string.Equals(requestUri.Host, _endpoint.Host, StringComparison.OrdinalIgnoreCase) ||
            requestUri.Port != _endpoint.Port || requestUri.Scheme != _endpoint.Scheme)
        {
            throw new InvalidOperationException("OpenSearch request path escaped its configured endpoint.");
        }

        var headers = new SortedDictionary<string, string>(StringComparer.Ordinal)
        {
            ["host"] = requestUri.IsDefaultPort ? requestUri.Host : requestUri.Authority,
            ["x-amz-content-sha256"] = payloadHash,
            ["x-amz-date"] = amzDate
        };
        if (payload.Length > 0) headers["content-type"] = "application/json";
        if (!string.IsNullOrWhiteSpace(credentials.Token)) headers["x-amz-security-token"] = credentials.Token;

        var canonicalHeaders = string.Concat(headers.Select(pair => $"{pair.Key}:{NormalizeHeader(pair.Value)}\n"));
        var signedHeaders = string.Join(';', headers.Keys);
        var canonicalRequest = string.Join('\n', new[]
        {
            method.Method,
            CanonicalPath(requestUri.AbsolutePath),
            CanonicalQuery(requestUri.Query),
            canonicalHeaders,
            signedHeaders,
            payloadHash
        });
        var credentialScope = $"{dateStamp}/{_region}/{_service}/aws4_request";
        var stringToSign = $"AWS4-HMAC-SHA256\n{amzDate}\n{credentialScope}\n{Sha256Hex(Encoding.UTF8.GetBytes(canonicalRequest))}";
        var signingKey = DeriveSigningKey(credentials.SecretKey, dateStamp, _region, _service);
        var signature = Convert.ToHexString(Hmac(signingKey, stringToSign)).ToLowerInvariant();
        var authorization = $"AWS4-HMAC-SHA256 Credential={credentials.AccessKey}/{credentialScope}, SignedHeaders={signedHeaders}, Signature={signature}";

        using var request = new HttpRequestMessage(method, requestUri);
        request.Headers.Host = headers["host"];
        request.Headers.TryAddWithoutValidation("x-amz-date", amzDate);
        request.Headers.TryAddWithoutValidation("x-amz-content-sha256", payloadHash);
        request.Headers.TryAddWithoutValidation("Authorization", authorization);
        if (!string.IsNullOrWhiteSpace(credentials.Token))
            request.Headers.TryAddWithoutValidation("x-amz-security-token", credentials.Token);
        if (payload.Length > 0)
        {
            request.Content = new ByteArrayContent(payload);
            request.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
        }

        using var response = await _httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, ct).ConfigureAwait(false);
        var body = await ReadLimitedAsync(response.Content, ct).ConfigureAwait(false);
        return new OpenSearchTransportResponse { StatusCode = (int)response.StatusCode, Body = body };
    }

    public void Dispose()
    {
        if (_ownsHttpClient) _httpClient.Dispose();
    }

    private static async Task<string> ReadLimitedAsync(HttpContent content, CancellationToken ct)
    {
        await using var stream = await content.ReadAsStreamAsync(ct).ConfigureAwait(false);
        using var buffer = new MemoryStream();
        var chunk = new byte[8192];
        int read;
        while ((read = await stream.ReadAsync(chunk.AsMemory(0, chunk.Length), ct).ConfigureAwait(false)) > 0)
        {
            if (buffer.Length + read > MaximumResponseBytes)
                throw new InvalidOperationException("OpenSearch response exceeded the configured safety limit.");
            await buffer.WriteAsync(chunk.AsMemory(0, read), ct).ConfigureAwait(false);
        }
        return Encoding.UTF8.GetString(buffer.ToArray());
    }

    private static string CanonicalPath(string absolutePath) =>
        string.Join('/', absolutePath.Split('/').Select(Uri.EscapeDataString));

    private static string CanonicalQuery(string query)
    {
        if (string.IsNullOrEmpty(query) || query == "?") return string.Empty;
        return string.Join('&', query[1..].Split('&', StringSplitOptions.RemoveEmptyEntries)
            .Select(part => part.Split('=', 2))
            .Select(parts => new KeyValuePair<string, string>(
                Uri.EscapeDataString(Uri.UnescapeDataString(parts[0])),
                Uri.EscapeDataString(Uri.UnescapeDataString(parts.Length == 2 ? parts[1] : string.Empty))))
            .OrderBy(pair => pair.Key, StringComparer.Ordinal)
            .ThenBy(pair => pair.Value, StringComparer.Ordinal)
            .Select(pair => $"{pair.Key}={pair.Value}"));
    }

    private static string NormalizeHeader(string value) => string.Join(' ', value.Trim().Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));
    private static string Sha256Hex(byte[] value) => Convert.ToHexString(SHA256.HashData(value)).ToLowerInvariant();
    private static byte[] Hmac(byte[] key, string value) => HMACSHA256.HashData(key, Encoding.UTF8.GetBytes(value));
    private static byte[] DeriveSigningKey(string secret, string date, string region, string service)
    {
        var dateKey = Hmac(Encoding.UTF8.GetBytes("AWS4" + secret), date);
        var regionKey = Hmac(dateKey, region);
        var serviceKey = Hmac(regionKey, service);
        return Hmac(serviceKey, "aws4_request");
    }
}
