# Generated by scripts/generate-sdk-types.py. Do not edit by hand.
from __future__ import annotations

from typing import Literal, TypeAlias, TypedDict

JSONPrimitive: TypeAlias = str | int | float | bool | None
JSONValue: TypeAlias = JSONPrimitive | list["JSONValue"] | dict[str, "JSONValue"]
JsonObject: TypeAlias = dict[str, JSONValue]

class _AdmissionReceiptRequired(TypedDict):
    version: str
    admissionId: str
    operationId: str
    status: Literal['accepted', 'rejected']
    resourceId: str
    requestHash: str
    idempotencyKeyHash: str | None
    replayed: bool
    admittedAtUtc: str
    statusUri: str
    resultUri: str | None
    failureClass: str | None
    error: str | None

class AdmissionReceipt(_AdmissionReceiptRequired, total=False):
    """Durable, deterministic proof that one exact request was admitted or synchronously rejected. The referenced resource is authoritative for lifecycle state."""

class _CanonicalMigrationRequired(TypedDict):
    namespace: str
    id: str
    checksum: str

class CanonicalMigration(_CanonicalMigrationRequired, total=False):
    description: str | None

CanonicalMigrationReceipt: TypeAlias = CanonicalMigration

class _CanonicalPreflightReportRequired(TypedDict):
    store: str
    provider: str
    authenticationMode: str
    tenantPoliciesEnforced: bool
    identityPolicyCount: int
    migrationReceiptCount: int
    rateLimitPermitLimit: int
    rateLimitWindowSeconds: int
    requiredOperations: list[str]

class CanonicalPreflightReport(_CanonicalPreflightReportRequired, total=False):
    dataPlaneProbe: CanonicalDataPlanePreflightResult | None

class _CanonicalDataPlanePreflightResultRequired(TypedDict):
    profile: Literal['vyral.canonical.data-plane-preflight.v1']
    ready: bool
    status: Literal['passed', 'failed']
    scope: Literal['isolated_ephemeral_tenants']
    checkedAtUtc: str
    durationMs: int
    archiveChunkCount: int
    backupRestoreVerified: bool
    tenantIsolationVerified: bool
    cleanupVerified: bool
    checks: list[CanonicalDataPlanePreflightCheck]

class CanonicalDataPlanePreflightResult(_CanonicalDataPlanePreflightResultRequired, total=False):
    pass

class _CanonicalDataPlanePreflightCheckRequired(TypedDict):
    id: str
    status: Literal['passed', 'failed']
    message: str

class CanonicalDataPlanePreflightCheck(_CanonicalDataPlanePreflightCheckRequired, total=False):
    pass

class _CanonicalDocumentRequired(TypedDict):
    tenantId: str
    documentType: str
    id: str
    schemaVersion: str
    indexes: dict[str, str]
    revision: int
    etag: str
    deleted: bool
    createdAtUtc: str
    updatedAtUtc: str

class CanonicalDocument(_CanonicalDocumentRequired, total=False):
    data: JSONValue

class CanonicalWritePrecondition(TypedDict, total=False):
    expectedRevision: int | None
    mustNotExist: bool
    mustExist: bool

class _CanonicalMutationRequired(TypedDict):
    operation: Literal['upsert', 'delete']

class CanonicalMutation(_CanonicalMutationRequired, total=False):
    document: CanonicalDocument | None
    documentType: str | None
    id: str | None
    precondition: CanonicalWritePrecondition | None

class _CanonicalFenceMutationRequired(TypedDict):
    operation: Literal['claim', 'release']
    name: str
    value: str
    ownerDocumentType: str
    ownerDocumentId: str

class CanonicalFenceMutation(_CanonicalFenceMutationRequired, total=False):
    pass

class _CanonicalFenceRequired(TypedDict):
    tenantId: str
    name: str
    value: str
    ownerDocumentType: str
    ownerDocumentId: str
    createdAtUtc: str
    updatedAtUtc: str

class CanonicalFence(_CanonicalFenceRequired, total=False):
    pass

class _CanonicalOutboxWriteRequired(TypedDict):
    topic: str
    key: str
    headers: dict[str, str]

class CanonicalOutboxWrite(_CanonicalOutboxWriteRequired, total=False):
    id: str | None
    payload: JSONValue
    notBeforeUtc: str | None
    maxDeliveryAttempts: int | None

CanonicalOutboxEvent: TypeAlias = CanonicalOutboxWrite

class _CanonicalTransactionRequestRequired(TypedDict):
    tenantId: str
    idempotencyKey: str
    mutations: list[CanonicalMutation]
    fences: list[CanonicalFenceMutation]
    outbox: list[CanonicalOutboxWrite]

class CanonicalTransactionRequest(_CanonicalTransactionRequestRequired, total=False):
    correlationId: str | None
    actor: str | None

class _CanonicalTransactionResultRequired(TypedDict):
    transactionId: str
    tenantId: str
    idempotencyKey: str
    replayed: bool
    committedAtUtc: str
    documents: list[CanonicalDocument]
    outbox: list[CanonicalOutboxEvent]

class CanonicalTransactionResult(_CanonicalTransactionResultRequired, total=False):
    correlationId: str | None
    actor: str | None

class _CanonicalDocumentQueryRequired(TypedDict):
    tenantId: str
    indexes: dict[str, str]

class CanonicalDocumentQuery(_CanonicalDocumentQueryRequired, total=False):
    documentType: str | None
    indexRange: CanonicalDocumentIndexRange | None
    orderByIndex: str | None
    orderDirection: Literal['ascending', 'descending']
    includeDeleted: bool
    limit: int | None
    continuationToken: str | None

class _CanonicalDocumentIndexRangeRequired(TypedDict):
    name: str

class CanonicalDocumentIndexRange(_CanonicalDocumentIndexRangeRequired, total=False):
    greaterThanOrEqual: str | None
    lessThanOrEqual: str | None

class _CanonicalDocumentQueryResultRequired(TypedDict):
    items: list[CanonicalDocument]

class CanonicalDocumentQueryResult(_CanonicalDocumentQueryResultRequired, total=False):
    continuationToken: str | None

class _CanonicalDocumentReadRequestRequired(TypedDict):
    tenantId: str
    documentType: str
    id: str

class CanonicalDocumentReadRequest(_CanonicalDocumentReadRequestRequired, total=False):
    includeDeleted: bool

class _CanonicalDocumentRevisionQueryRequired(TypedDict):
    tenantId: str
    documentType: str
    id: str

class CanonicalDocumentRevisionQuery(_CanonicalDocumentRevisionQueryRequired, total=False):
    limit: int | None

class _CanonicalDocumentRevisionRequired(TypedDict):
    tenantId: str
    documentType: str
    id: str
    revision: int
    transactionId: str
    operation: Literal['upsert', 'delete']
    document: CanonicalDocument
    recordedAtUtc: str

class CanonicalDocumentRevision(_CanonicalDocumentRevisionRequired, total=False):
    pass

class _CanonicalOutboxLeaseRequestRequired(TypedDict):
    tenantId: str
    consumerId: str

class CanonicalOutboxLeaseRequest(_CanonicalOutboxLeaseRequestRequired, total=False):
    maxItems: int
    leaseSeconds: float

class _CanonicalOutboxLeaseRequired(TypedDict):
    event: CanonicalOutboxEvent
    leaseToken: str
    expiresAtUtc: str

class CanonicalOutboxLease(_CanonicalOutboxLeaseRequired, total=False):
    pass

class _CanonicalOutboxLeaseRenewalRequestRequired(TypedDict):
    tenantId: str
    eventId: str
    leaseToken: str

class CanonicalOutboxLeaseRenewalRequest(_CanonicalOutboxLeaseRenewalRequestRequired, total=False):
    leaseSeconds: float

class _CanonicalOutboxLeaseRenewalRequired(TypedDict):
    expiresAtUtc: str

class CanonicalOutboxLeaseRenewal(_CanonicalOutboxLeaseRenewalRequired, total=False):
    pass

class _CanonicalOutboxAcknowledgementRequired(TypedDict):
    leaseToken: str

class CanonicalOutboxAcknowledgement(_CanonicalOutboxAcknowledgementRequired, total=False):
    pass

class _CanonicalOutboxNackRequestRequired(TypedDict):
    tenantId: str
    eventId: str
    leaseToken: str

class CanonicalOutboxNackRequest(_CanonicalOutboxNackRequestRequired, total=False):
    notBeforeUtc: str | None
    retryAfterSeconds: float | None
    error: str | None

class _CanonicalOutboxQueryRequired(TypedDict):
    tenantId: str

class CanonicalOutboxQuery(_CanonicalOutboxQueryRequired, total=False):
    state: Literal['ready', 'leased', 'scheduled', 'delivered', 'dead-letter'] | None
    topic: str | None
    limit: int | None
    continuationToken: str | None

class _CanonicalOutboxQueryResultRequired(TypedDict):
    items: list[CanonicalOutboxEvent]

class CanonicalOutboxQueryResult(_CanonicalOutboxQueryResultRequired, total=False):
    continuationToken: str | None

class _CanonicalOutboxReplayRequestRequired(TypedDict):
    tenantId: str
    eventId: str

class CanonicalOutboxReplayRequest(_CanonicalOutboxReplayRequestRequired, total=False):
    resetDeliveryCount: bool

class _CanonicalTransactionReceiptRequired(TypedDict):
    transactionId: str
    tenantId: str
    idempotencyKey: str
    requestHash: str
    result: CanonicalTransactionResult
    committedAtUtc: str

class CanonicalTransactionReceipt(_CanonicalTransactionReceiptRequired, total=False):
    pass

class _CanonicalTenantSnapshotRequired(TypedDict):
    tenantId: str
    documents: list[CanonicalDocument]
    revisions: list[CanonicalDocumentRevision]
    fences: list[CanonicalFence]
    outbox: list[CanonicalOutboxEvent]
    transactions: list[CanonicalTransactionReceipt]
    exportedAtUtc: str
    contentHash: str

class CanonicalTenantSnapshot(_CanonicalTenantSnapshotRequired, total=False):
    pass

class _CanonicalRestoreRequestRequired(TypedDict):
    snapshot: CanonicalTenantSnapshot

class CanonicalRestoreRequest(_CanonicalRestoreRequestRequired, total=False):
    expectedContentHash: str | None

class _RecordCollectionPolicyRequired(TypedDict):
    name: str

class RecordCollectionPolicy(_RecordCollectionPolicyRequired, total=False):
    partitionKeyPath: str
    vectorPolicies: list[VectorFieldPolicy]
    indexedMetadata: list[str]

class CollectionInspectionResult(TypedDict, total=False):
    collection: str
    generatedAt: str
    policy: RecordCollectionPolicy
    recordCount: int
    partitionCount: int
    typeCounts: dict[str, int]
    embeddingProviderCounts: dict[str, int]
    embeddingModelCounts: dict[str, int]
    rag: RagCollectionInspection
    vectors: list[VectorFieldInspection]
    extraVectorFieldCounts: dict[str, int]
    anomalyCount: int
    returnedAnomalyCount: int
    anomalies: list[CollectionInspectionAnomaly]

class RagCollectionInspection(TypedDict, total=False):
    documentCount: int
    chunkCount: int
    manifestCount: int
    chunkRecordsWithDocumentIdCount: int
    chunkRecordsWithVectorCount: int
    chunkRecordsWithoutVectorCount: int

class VectorFieldInspection(TypedDict, total=False):
    field: str
    path: str
    policyDimensions: int
    datatype: str
    distanceFunction: str
    indexType: str
    recordCount: int
    presentCount: int
    missingCount: int
    notApplicableCount: int
    emptyCount: int
    dimensionMismatchCount: int
    policyCoverage: float
    modelCounts: dict[str, int]
    sourceFieldCounts: dict[str, int]

class CollectionInspectionAnomaly(TypedDict, total=False):
    kind: str
    id: str
    partitionKey: str
    type: str | None
    field: str | None
    message: str
    details: dict[str, JSONValue]

class _VectorFieldPolicyRequired(TypedDict):
    name: str
    path: str
    dimensions: int

class VectorFieldPolicy(_VectorFieldPolicyRequired, total=False):
    datatype: str
    distanceFunction: Literal['cosine', 'dotProduct', 'euclidean']
    indexType: str

class _VyralRecordRequired(TypedDict):
    id: str
    partitionKey: str

class VyralRecord(_VyralRecordRequired, total=False):
    type: str
    schemaVersion: str | None
    metadata: dict[str, JSONValue] | None
    content: dict[str, JSONValue] | None
    sources: list[VyralSourceReference] | None
    vectors: dict[str, VyralVector] | None
    embedding: dict[str, JSONValue] | None
    etag: str | None
    revision: int | None
    createdAt: str | None
    updatedAt: str | None

class VyralSourceReference(TypedDict, total=False):
    id: str
    kind: str
    uri: str
    label: str | None
    span: dict[str, JSONValue] | None

class _VyralVectorRequired(TypedDict):
    values: list[float]
    dimensions: int

class VyralVector(_VyralVectorRequired, total=False):
    model: str | None
    datatype: str
    distanceFunction: str
    generatedAt: str | None
    sourceField: str | None

class QueryEnvelope(TypedDict, total=False):
    partitionKeys: list[str] | None
    filter: FilterNode
    vector: VectorSearchOptions
    lexical: LexicalSearchOptions
    orderBy: list[OrderExpression] | None
    limit: int | None
    continuationToken: str | None

class FilterNode(TypedDict, total=False):
    """Recursive filter tree. Leaf nodes use path/op/value. Compound nodes use combine plus children."""
    path: str | None
    op: Literal['eq', 'neq', 'in', 'gt', 'gte', 'lt', 'lte', 'exists', 'contains', 'startsWith'] | None
    value: JSONValue
    combine: Literal['all', 'any', None] | None
    children: list[FilterNode] | None

class _VectorSearchOptionsRequired(TypedDict):
    field: str
    value: list[float]

class VectorSearchOptions(_VectorSearchOptionsRequired, total=False):
    top: int
    minScore: float | None

class LexicalSearchOptions(TypedDict, total=False):
    query: str
    fields: list[str] | None
    top: int
    scanLimit: int | None
    minScore: float | None
    scoring: Literal['bm25', 'coverage']
    matchMode: Literal['any', 'all']
    fieldBoosts: dict[str, float] | None
    bm25K1: float
    bm25B: float
    phraseBoost: float
    exactBoost: float
    metadataBoost: float
    prefixMatching: bool
    prefixMinChars: int
    requiredPhraseGroups: list[list[str]] | None

class HybridSearchOptions(TypedDict, total=False):
    vectorWeight: float
    lexicalWeight: float
    candidateMultiplier: int
    vectorCandidateLimit: int | None
    lexicalCandidateLimit: int | None
    fusion: Literal['weighted', 'rrf']
    rrfK: int

class RerankOptions(TypedDict, total=False):
    enabled: bool
    provider: str | None
    mode: str
    candidateLimit: int | None
    maxCandidateChars: int
    contentField: str | None
    rerankScoreWeight: float
    originalScoreWeight: float
    timeoutSeconds: int | None
    maxOutputBytes: int | None
    fallbackOnFailure: bool

class _OrderExpressionRequired(TypedDict):
    path: str

class OrderExpression(_OrderExpressionRequired, total=False):
    direction: Literal['asc', 'desc']

class _ArtifactRecordIngestManifestRequired(TypedDict):
    collection: str
    record: VyralRecord
    artifact: ArtifactRecordDescriptor

class ArtifactRecordIngestManifest(_ArtifactRecordIngestManifestRequired, total=False):
    externalContext: ExternalContextProof

class _ArtifactRecordDescriptorRequired(TypedDict):
    container: str
    key: str

class ArtifactRecordDescriptor(_ArtifactRecordDescriptorRequired, total=False):
    contentType: str | None
    metadata: dict[str, str] | None

class _ExternalContextProofRequired(TypedDict):
    token: str

class ExternalContextProof(_ExternalContextProofRequired, total=False):
    pass

class _ArtifactRecordIngestReceiptRequired(TypedDict):
    accepted: bool
    collection: str
    recordId: str
    partitionKey: str
    recordUri: str
    artifact: ObjectInfo
    externalContextVerified: bool
    receivedAt: str

class ArtifactRecordIngestReceipt(_ArtifactRecordIngestReceiptRequired, total=False):
    pass

class _RecordQueryResultRequired(TypedDict):
    items: list[VyralRecord]

class RecordQueryResult(_RecordQueryResultRequired, total=False):
    continuationToken: str | None

class _RecordSearchResultRequired(TypedDict):
    items: list[VyralRecordMatch]

class RecordSearchResult(_RecordSearchResultRequired, total=False):
    continuationToken: str | None

class VyralGraphScope(TypedDict, total=False):
    graphId: str
    namespace: str
    collection: str
    tenantId: str
    partitionKey: str

class VyralGraphSourceSpan(TypedDict, total=False):
    sourceRef: str
    charStart: int | None
    charEnd: int | None
    unit: str
    locator: str | None
    textHash: str | None
    metadata: dict[str, JSONValue] | None

class _VyralGraphNodeRequired(TypedDict):
    id: str
    type: str

class VyralGraphNode(_VyralGraphNodeRequired, total=False):
    label: str | None
    properties: dict[str, JSONValue] | None
    sourceSpans: list[VyralGraphSourceSpan]
    assertionIds: list[str]
    createdAt: str | None
    updatedAt: str | None

class _VyralGraphEdgeRequired(TypedDict):
    id: str
    sourceId: str
    targetId: str
    predicate: str

class VyralGraphEdge(_VyralGraphEdgeRequired, total=False):
    label: str | None
    properties: dict[str, JSONValue] | None
    sourceSpans: list[VyralGraphSourceSpan]
    assertionIds: list[str]
    createdAt: str | None
    updatedAt: str | None

class _VyralGraphAssertionRequired(TypedDict):
    id: str
    subjectId: str
    subjectKind: str

class VyralGraphAssertion(_VyralGraphAssertionRequired, total=False):
    status: str
    method: str
    actor: str
    confidence: float | None
    sourceSpans: list[VyralGraphSourceSpan]
    properties: dict[str, JSONValue] | None
    createdAt: str | None

class _VyralGraphReviewEventRequired(TypedDict):
    id: str
    subjectId: str
    subjectKind: str
    status: str
    reviewer: str

class VyralGraphReviewEvent(_VyralGraphReviewEventRequired, total=False):
    notes: str | None
    properties: dict[str, JSONValue] | None
    createdAt: str | None

class VyralGraphTraversalProfile(TypedDict, total=False):
    id: str
    direction: Literal['outgoing', 'incoming', 'both']
    maxDepth: int
    predicates: list[str]
    nodeTypes: list[str]
    limit: int
    edgeLimit: int
    includeStart: bool
    reviewStatuses: list[str]
    assertionStatuses: list[str]
    requireSourceGrounding: bool
    minScore: float | None
    includePathExplanations: bool

class _VyralGraphProjectionRequired(TypedDict):
    id: str

class VyralGraphProjection(_VyralGraphProjectionRequired, total=False):
    profile: VyralGraphTraversalProfile
    startNodeIds: list[str]
    nodes: list[VyralGraphNode]
    edges: list[VyralGraphEdge]
    diagnostics: dict[str, JSONValue] | None
    createdAt: str | None

class VyralGraphEnvelope(TypedDict, total=False):
    schema: str
    scope: VyralGraphScope
    metadata: dict[str, JSONValue] | None
    nodes: list[VyralGraphNode]
    edges: list[VyralGraphEdge]
    assertions: list[VyralGraphAssertion]
    reviews: list[VyralGraphReviewEvent]
    projections: list[VyralGraphProjection]

class VyralGraphProviderShape(TypedDict, total=False):
    providerId: str
    kind: str
    graphIdField: str
    nodeIdField: str
    edgeIdField: str
    sourceField: str
    targetField: str
    partitionField: str
    tenantField: str
    capabilities: list[str]
    limitations: list[str]
    metadata: dict[str, JSONValue] | None
    id: str

class _VyralGraphCollectionImportRequestRequired(TypedDict):
    envelope: VyralGraphEnvelope

class VyralGraphCollectionImportRequest(_VyralGraphCollectionImportRequestRequired, total=False):
    createCollectionIfMissing: bool
    replaceExisting: bool
    continueOnError: bool
    allowNonGraphPolicy: bool

class VyralGraphCollectionImportResult(TypedDict, total=False):
    collection: str
    graphId: str
    partitionKey: str
    policyStatus: str
    nodeCount: int
    edgeCount: int
    assertionCount: int
    reviewCount: int
    projectionCount: int
    recordCount: int
    records: RecordBatchUpsertResult

class VyralGraphCollectionExportRequest(TypedDict, total=False):
    graphId: str | None
    namespace: str | None
    tenantId: str | None
    partitionKey: str | None
    includeProjections: bool
    maxRecords: int | None
    failOnLimitExceeded: bool

class VyralGraphCollectionExportResult(TypedDict, total=False):
    collection: str
    envelope: VyralGraphEnvelope
    recordCount: int
    truncated: bool
    continuationToken: str | None
    exportedAt: str | None

class _VyralGraphTraversalRequestRequired(TypedDict):
    startNodeIds: list[str]

class VyralGraphTraversalRequest(_VyralGraphTraversalRequestRequired, total=False):
    graphId: str | None
    namespace: str | None
    tenantId: str | None
    partitionKey: str | None
    profile: VyralGraphTraversalProfile
    maxRecords: int | None
    allowPartialGraph: bool

class VyralGraphTraversalResult(TypedDict, total=False):
    collection: str
    graphId: str
    projection: VyralGraphProjection
    nodeCount: int
    edgeCount: int
    sourceRecordCount: int
    sourceTruncated: bool
    requestedMaxRecords: int
    exportedRecordCount: int
    estimatedRequiredRecordCount: int | None
    sourceContinuationToken: str | None

class VyralGraphCollectionInspectionRequest(TypedDict, total=False):
    graphId: str | None
    namespace: str | None
    tenantId: str | None
    partitionKey: str | None
    maxRecords: int | None
    allowPartialGraph: bool
    includeAnomalies: bool
    anomalyLimit: int

class VyralGraphSourceGroundingInspection(TypedDict, total=False):
    nodeGroundedCount: int
    nodeUngroundedCount: int
    nodeCoverage: float
    edgeGroundedCount: int
    edgeUngroundedCount: int
    edgeCoverage: float
    assertionGroundedCount: int
    assertionUngroundedCount: int
    assertionCoverage: float

class VyralGraphInspectionAnomaly(TypedDict, total=False):
    kind: str
    id: str
    subjectId: str | None
    subjectKind: str | None
    message: str
    details: dict[str, JSONValue]

class VyralGraphCollectionInspectionResult(TypedDict, total=False):
    collection: str
    generatedAt: str
    graphId: str
    namespace: str
    tenantId: str
    partitionKey: str
    recordCount: int
    truncated: bool
    continuationToken: str | None
    traversalReady: bool
    nodeCount: int
    edgeCount: int
    assertionCount: int
    reviewCount: int
    projectionCount: int
    recordTypeCounts: dict[str, int]
    graphIdCounts: dict[str, int]
    namespaceCounts: dict[str, int]
    tenantIdCounts: dict[str, int]
    partitionKeyCounts: dict[str, int]
    nodeTypeCounts: dict[str, int]
    predicateCounts: dict[str, int]
    assertionStatusCounts: dict[str, int]
    reviewStatusCounts: dict[str, int]
    sourceGrounding: VyralGraphSourceGroundingInspection
    danglingEdgeCount: int
    orphanAssertionCount: int
    orphanReviewCount: int
    danglingAssertionReferenceCount: int
    danglingProjectionStartNodeCount: int
    duplicateNodeIdCount: int
    duplicateEdgeIdCount: int
    duplicateAssertionIdCount: int
    duplicateReviewIdCount: int
    duplicateProjectionIdCount: int
    warningCount: int
    warnings: list[str]
    anomalyCount: int
    returnedAnomalyCount: int
    anomalies: list[VyralGraphInspectionAnomaly]

class _CollectionExportEnvelopeRequired(TypedDict):
    collection: str
    policy: RecordCollectionPolicy
    records: list[VyralRecord]

class CollectionExportEnvelope(_CollectionExportEnvelopeRequired, total=False):
    query: QueryEnvelope | None
    maxRecords: int | None
    recordCount: int | None
    truncated: bool
    continuationToken: str | None
    exportedAt: str | None
    contentHash: str | None

class CollectionExportRequest(TypedDict, total=False):
    query: QueryEnvelope | None
    maxRecords: int | None
    failOnLimitExceeded: bool

class _CollectionImportRequestRequired(TypedDict):
    snapshot: CollectionExportEnvelope

class CollectionImportRequest(_CollectionImportRequestRequired, total=False):
    expectedContentHash: str | None
    replaceExisting: bool
    continueOnError: bool
    allowCollectionRename: bool
    allowPartialSnapshot: bool

class _CollectionImportResultRequired(TypedDict):
    collection: str
    sourceCollection: str
    policyStatus: Literal['created', 'existing_equivalent', 'replaced']
    recordCount: int
    contentHash: str
    contentHashComparison: CollectionSnapshotHashComparison
    records: RecordBatchUpsertResult

class CollectionImportResult(_CollectionImportResultRequired, total=False):
    pass

class _CollectionSnapshotHashComparisonRequired(TypedDict):
    kind: str
    compared: bool
    matches: bool
    status: Literal['not_provided', 'actual_missing', 'matched', 'drifted']

class CollectionSnapshotHashComparison(_CollectionSnapshotHashComparisonRequired, total=False):
    expectedHash: str | None
    actualHash: str | None

class _RecordBatchUpsertRequestRequired(TypedDict):
    records: list[VyralRecord]

class RecordBatchUpsertRequest(_RecordBatchUpsertRequestRequired, total=False):
    preconditions: list[RecordWritePrecondition]
    continueOnError: bool

class RecordWritePrecondition(TypedDict, total=False):
    ifMatch: str
    ifNoneMatch: str
    expectedEtag: str
    expectedRevision: int

class _RecordBatchUpsertResultRequired(TypedDict):
    collection: str
    requested: int
    attempted: int
    succeeded: int
    failed: int
    stoppedOnError: bool
    items: list[RecordBatchUpsertItemResult]

class RecordBatchUpsertResult(_RecordBatchUpsertResultRequired, total=False):
    pass

class _RecordBatchUpsertItemResultRequired(TypedDict):
    index: int
    status: Literal['succeeded', 'failed']

class RecordBatchUpsertItemResult(_RecordBatchUpsertItemResultRequired, total=False):
    id: str | None
    partitionKey: str | None
    etag: str | None
    revision: int | None
    error: str | None

class _RecordImportJobRequired(TypedDict):
    admission: AdmissionReceipt
    id: str
    kind: Literal['batch_upsert', 'collection_import']
    status: Literal['queued', 'running', 'succeeded', 'failed', 'cancelled', 'rejected']
    collection: str
    requestHash: str
    createdAt: str
    cancellationRequested: bool
    requested: int
    attempted: int
    succeeded: int
    failed: int
    progress: float
    stoppedOnError: bool

class RecordImportJob(_RecordImportJobRequired, total=False):
    sourceCollection: str | None
    startedAt: str | None
    completedAt: str | None
    durationMs: float | None
    failureClass: str | None
    error: str | None
    batchResult: RecordBatchUpsertResult
    importResult: CollectionImportResult

class _VyralRecordMatchRequired(TypedDict):
    record: VyralRecord
    score: float

class VyralRecordMatch(_VyralRecordMatchRequired, total=False):
    diagnostics: RetrievalDiagnostics

class RetrievalDiagnostics(TypedDict, total=False):
    schemaVersion: str
    resultIdentity: RetrievalResultIdentity
    scoreComponents: dict[str, float]
    scoreNormalization: RetrievalScoreNormalization
    candidateSources: list[str]
    candidateCounts: dict[str, int]
    reasonCodes: list[str]
    matchedFields: list[str]
    matchedTerms: list[str]
    traceReferences: list[RetrievalTraceReference]
    details: dict[str, JSONValue]

class RetrievalResultIdentity(TypedDict, total=False):
    collection: str
    partitionKey: str
    id: str
    type: str
    etag: str | None
    revision: int | None

class RetrievalScoreNormalization(TypedDict, total=False):
    finalScoreKind: str
    vectorScoreKind: str | None
    lexicalScoreKind: str | None
    hybridFusion: str | None
    vectorDistanceFunction: str | None
    vectorNormalization: str | None
    weights: dict[str, float]
    parameters: dict[str, JSONValue]

class RetrievalTraceReference(TypedDict, total=False):
    kind: str
    operation: str
    traceId: str
    provider: str | None
    modelId: str | None
    redaction: str
    safe: bool

class _ObjectInfoRequired(TypedDict):
    container: str
    key: str
    contentLength: int
    etag: str
    contentHash: str
    metadata: dict[str, str]
    updatedAt: str

class ObjectInfo(_ObjectInfoRequired, total=False):
    contentType: str | None

class _ObjectListResultRequired(TypedDict):
    items: list[ObjectInfo]

class ObjectListResult(_ObjectListResultRequired, total=False):
    continuationToken: str | None

class EmbeddingOptions(TypedDict, total=False):
    field: str | None
    purpose: Literal['query', 'passage', 'document', 'symmetric'] | None
    queryPrefix: str | None
    passagePrefix: str | None
    symmetricPrefix: str | None

class _RetrievalProfileDescriptorRequired(TypedDict):
    id: str
    label: str
    description: str
    searchMode: Literal['vector', 'lexical', 'hybrid']
    requiresVector: bool
    usesRerank: bool
    recommendedFor: list[str]
    cautions: list[str]
    defaults: RetrievalProfileDefaults

class RetrievalProfileDescriptor(_RetrievalProfileDescriptorRequired, total=False):
    pass

class _RetrievalProfileDefaultsRequired(TypedDict):
    searchMode: Literal['vector', 'lexical', 'hybrid']
    limit: int
    includeTrace: bool

class RetrievalProfileDefaults(_RetrievalProfileDefaultsRequired, total=False):
    embedding: EmbeddingOptions | None
    lexical: LexicalSearchOptions | None
    hybrid: HybridSearchOptions | None
    rerank: RerankOptions | None

class _RetrievalRequestRequired(TypedDict):
    query: str
    collections: list[str]

class RetrievalRequest(_RetrievalRequestRequired, total=False):
    profile: str | None
    partitionKeys: list[str] | None
    filter: FilterNode
    embedding: EmbeddingOptions
    vectorFields: list[RetrievalVectorFieldQuery] | None
    searchMode: Literal['vector', 'lexical', 'hybrid']
    lexical: LexicalSearchOptions
    hybrid: HybridSearchOptions
    rerank: RerankOptions
    limit: int
    minScore: float | None
    includeTrace: bool

class _RetrievalResultEnvelopeRequired(TypedDict):
    query: str
    results: list[RetrievalMatch]

class RetrievalResultEnvelope(_RetrievalResultEnvelopeRequired, total=False):
    trace: dict[str, JSONValue] | None

class _RetrievalMatchRequired(TypedDict):
    rank: int
    score: float
    collection: str
    record: VyralRecord

class RetrievalMatch(_RetrievalMatchRequired, total=False):
    snippet: str | None
    diagnostics: RetrievalDiagnostics

class _RetrievalEvaluationRequestRequired(TypedDict):
    cases: list[RetrievalEvaluationCase]

class RetrievalEvaluationRequest(_RetrievalEvaluationRequestRequired, total=False):
    continueOnError: bool
    defaultK: int | None
    includeTopResults: bool

class _RetrievalEvaluationComparisonRequestRequired(TypedDict):
    cases: list[RetrievalEvaluationCase]
    variants: list[RetrievalEvaluationVariant]

class RetrievalEvaluationComparisonRequest(_RetrievalEvaluationComparisonRequestRequired, total=False):
    continueOnError: bool
    defaultK: int | None
    includeTopResults: bool
    includeCaseResults: bool

class _RetrievalEvaluationVariantRequired(TypedDict):
    id: str

class RetrievalEvaluationVariant(_RetrievalEvaluationVariantRequired, total=False):
    label: str | None
    profile: str | None
    collections: list[str] | None
    partitionKeys: list[str] | None
    filter: FilterNode
    embedding: EmbeddingOptions
    vectorFields: list[RetrievalVectorFieldQuery] | None
    searchMode: Literal['lexical', 'vector', 'hybrid'] | None
    lexical: LexicalSearchOptions
    hybrid: HybridSearchOptions
    rerank: RerankOptions
    limit: int | None
    minScore: float | None
    includeTrace: bool | None

class _RetrievalEvaluationCaseRequired(TypedDict):
    request: RetrievalRequest
    expected: list[RetrievalEvaluationExpectedMatch]

class RetrievalEvaluationCase(_RetrievalEvaluationCaseRequired, total=False):
    name: str | None
    hardNegatives: list[RetrievalEvaluationHardNegativeMatch]
    k: int | None
    metadata: dict[str, JSONValue] | None

class RetrievalEvaluationExpectedMatch(TypedDict, total=False):
    id: str
    partitionKey: str | None
    collection: str | None
    aliases: list[str]
    sourceIds: list[str]
    sources: list[VyralSourceReference]
    relevance: float

class RetrievalEvaluationHardNegativeMatch(TypedDict, total=False):
    id: str
    partitionKey: str | None
    collection: str | None
    aliases: list[str]
    sourceIds: list[str]
    sources: list[VyralSourceReference]
    reason: str | None

class _RetrievalEvaluationResultRequired(TypedDict):
    requested: int
    attempted: int
    succeeded: int
    failed: int
    hitCount: int
    hitRate: float
    cases: list[RetrievalEvaluationCaseResult]

class RetrievalEvaluationResult(_RetrievalEvaluationResultRequired, total=False):
    stoppedOnError: bool
    meanReciprocalRank: float
    meanPrecisionAtK: float
    meanRecallAtK: float
    meanNdcgAtK: float
    hardNegativeCaseCount: int
    hardNegativeHitCount: int
    hardNegativeHitRate: float
    meanHardNegativeRateAtK: float
    rerankCaseCount: int
    rerankFallbackCaseCount: int
    rerankFallbackRate: float

class _RetrievalEvaluationComparisonResultRequired(TypedDict):
    requested: int
    variantsRequested: int
    variantsAttempted: int
    variantsSucceeded: int
    variantsFailed: int
    variants: list[RetrievalEvaluationVariantResult]

class RetrievalEvaluationComparisonResult(_RetrievalEvaluationComparisonResultRequired, total=False):
    stoppedOnError: bool
    baselineVariantId: str | None

class RetrievalEvaluationProgress(TypedDict, total=False):
    currentCaseIndex: int | None
    currentCaseName: str | None
    requested: int
    casesAttempted: int
    casesSucceeded: int
    casesFailed: int
    result: RetrievalEvaluationResult

class RetrievalEvaluationComparisonProgress(TypedDict, total=False):
    currentVariantId: str | None
    currentVariantIndex: int | None
    requested: int
    variantsRequested: int
    variantsAttempted: int
    variantsSucceeded: int
    variantsFailed: int
    result: RetrievalEvaluationComparisonResult

class _RetrievalEvaluationJobRequired(TypedDict):
    admission: AdmissionReceipt
    id: str
    kind: Literal['evaluation', 'comparison']
    status: Literal['queued', 'running', 'succeeded', 'failed', 'cancelled', 'rejected']
    requestHash: str
    createdAt: str
    requested: int
    casesAttempted: int
    casesSucceeded: int
    casesFailed: int
    variantsRequested: int
    variantsAttempted: int
    variantsSucceeded: int
    variantsFailed: int
    progress: float

class RetrievalEvaluationJob(_RetrievalEvaluationJobRequired, total=False):
    startedAt: str | None
    completedAt: str | None
    durationMs: float | None
    cancellationRequested: bool
    currentCaseIndex: int | None
    currentCaseName: str | None
    currentVariantId: str | None
    currentVariantIndex: int | None
    failureClass: str | None
    error: str | None
    evaluationResult: RetrievalEvaluationResult
    result: RetrievalEvaluationComparisonResult

class _RetrievalEvaluationVariantResultRequired(TypedDict):
    id: str
    status: Literal['succeeded', 'failed']
    durationMs: float
    metrics: RetrievalEvaluationMetrics
    cases: list[RetrievalEvaluationCaseResult]

class RetrievalEvaluationVariantResult(_RetrievalEvaluationVariantResultRequired, total=False):
    label: str | None
    error: str | None
    deltaFromBaseline: RetrievalEvaluationMetricDeltas

class RetrievalEvaluationMetrics(TypedDict, total=False):
    requested: int
    attempted: int
    succeeded: int
    failed: int
    stoppedOnError: bool
    hitCount: int
    hitRate: float
    meanReciprocalRank: float
    meanPrecisionAtK: float
    meanRecallAtK: float
    meanNdcgAtK: float
    hardNegativeCaseCount: int
    hardNegativeHitCount: int
    hardNegativeHitRate: float
    meanHardNegativeRateAtK: float
    rerankCaseCount: int
    rerankFallbackCaseCount: int
    rerankFallbackRate: float

class RetrievalEvaluationMetricDeltas(TypedDict, total=False):
    hitRate: float
    meanReciprocalRank: float
    meanPrecisionAtK: float
    meanRecallAtK: float
    meanNdcgAtK: float
    hardNegativeHitRate: float
    meanHardNegativeRateAtK: float
    rerankFallbackRate: float

class _RetrievalEvaluationCaseResultRequired(TypedDict):
    index: int
    query: str
    status: Literal['succeeded', 'failed']
    durationMs: float
    k: int
    expectedCount: int
    retrievedCount: int
    matchedCount: int
    hit: bool

class RetrievalEvaluationCaseResult(_RetrievalEvaluationCaseResultRequired, total=False):
    name: str | None
    error: str | None
    firstRelevantRank: int | None
    reciprocalRank: float
    precisionAtK: float
    recallAtK: float
    ndcgAtK: float
    hardNegativeCount: int
    hardNegativeMatchedCount: int
    hardNegativeHit: bool
    firstHardNegativeRank: int | None
    hardNegativeRateAtK: float
    rerankEnabled: bool
    rerankProvider: str | None
    rerankTraceId: str | None
    rerankFallbackApplied: bool
    rerankFailureClass: str | None
    rerankProviderStatus: str | None
    rerankInputCandidateCount: int
    rerankProviderPayloadBytes: int
    rerankProviderMaxInputBytes: int
    expected: list[RetrievalEvaluationExpectedResult]
    hardNegatives: list[RetrievalEvaluationHardNegativeResult]
    topResults: list[RetrievalEvaluationTopResult]

class RetrievalEvaluationExpectedResult(TypedDict, total=False):
    id: str
    partitionKey: str | None
    collection: str | None
    relevance: float
    rank: int | None
    score: float | None

class RetrievalEvaluationHardNegativeResult(TypedDict, total=False):
    id: str
    partitionKey: str | None
    collection: str | None
    reason: str | None
    rank: int | None
    score: float | None

class RetrievalEvaluationTopResult(TypedDict, total=False):
    rank: int
    score: float
    collection: str
    id: str
    partitionKey: str
    type: str | None
    matchedExpected: bool
    matchedHardNegative: bool
    rerankFallbackApplied: bool
    rerankProviderStatus: str | None
    vectorIndexUsed: bool
    vectorIndexProvider: str | None
    vectorIndexFields: list[str]
    snippet: str | None

class _RagIngestTextRequestRequired(TypedDict):
    partitionKey: str
    text: str

class RagIngestTextRequest(_RagIngestTextRequestRequired, total=False):
    documentId: str | None
    idPrefix: str | None
    type: str
    schemaVersion: str | None
    contentField: str
    embedding: EmbeddingOptions
    metadata: dict[str, JSONValue] | None
    sourceUri: str | None
    sourceKind: str | None
    sourceId: str | None
    sourceLabel: str | None
    sources: list[VyralSourceReference] | None
    options: RagIngestionOptions

class RagIngestionOptions(TypedDict, total=False):
    chunkChars: int
    chunkOverlapChars: int
    dryRun: bool
    replaceDocumentChunks: bool
    skipUnchangedChunks: bool
    reuseExistingChunkVectors: bool
    vectorReuseScope: Literal['request', 'partition', 'collection']
    deduplicateExistingChunks: bool
    chunkDedupeScope: Literal['request', 'partition', 'collection']
    persistManifest: bool
    manifestId: str | None
    expectedPlanHash: str | None
    expectedManifestHash: str | None
    includeTrace: bool

class _RagIngestTextBatchRequestRequired(TypedDict):
    items: list[RagIngestTextRequest]

class RagIngestTextBatchRequest(_RagIngestTextBatchRequestRequired, total=False):
    continueOnError: bool

class _RagIngestTextBatchResultRequired(TypedDict):
    collection: str
    requested: int
    attempted: int
    succeeded: int
    failed: int
    stoppedOnError: bool
    textLength: int
    chunkCount: int
    deletedStaleCount: int
    createdCount: int
    updatedCount: int
    reusedCount: int
    vectorGeneratedCount: int
    vectorReusedCount: int
    deduplicatedCount: int
    items: list[RagIngestTextBatchItemResult]

class RagIngestTextBatchResult(_RagIngestTextBatchResultRequired, total=False):
    pass

class _RagIngestTextBatchItemResultRequired(TypedDict):
    index: int
    status: Literal['succeeded', 'failed']

class RagIngestTextBatchItemResult(_RagIngestTextBatchItemResultRequired, total=False):
    documentId: str | None
    partitionKey: str | None
    result: RagIngestTextResult | None
    error: str | None

class _RagIngestTextResultRequired(TypedDict):
    collection: str
    documentId: str
    partitionKey: str
    embeddingField: str
    embeddingProvider: str
    embeddingModel: str
    embeddingPurpose: str
    dimensions: int
    textLength: int
    textHash: str
    planHash: str
    chunkCount: int
    dryRun: bool
    deletedStaleCount: int
    createdCount: int
    updatedCount: int
    reusedCount: int
    vectorGeneratedCount: int
    vectorReusedCount: int
    deduplicatedCount: int
    actionSummary: RagIngestActionSummary
    planHashComparison: RagIngestHashComparison
    manifestHashComparison: RagIngestHashComparison
    staleDeletes: list[RagIngestStaleDeleteResult]
    chunks: list[RagIngestChunkResult]

class RagIngestTextResult(_RagIngestTextResultRequired, total=False):
    manifestId: str | None
    manifestHash: str | None
    manifestAction: Literal['created', 'updated', 'reused', None] | None
    manifestEtag: str | None
    manifestRevision: int | None
    trace: dict[str, JSONValue] | None

class RagIngestActionSummary(TypedDict, total=False):
    actionCounts: dict[str, int]
    embeddingActionCounts: dict[str, int]
    createdIds: list[str]
    updatedIds: list[str]
    reusedIds: list[str]
    deduplicatedIds: list[str]
    staleDeleteIds: list[str]

class RagIngestHashComparison(TypedDict, total=False):
    kind: str
    expectedHash: str | None
    actualHash: str | None
    compared: bool
    matches: bool
    status: Literal['not_provided', 'matched', 'drifted', 'actual_missing']

class _RagIngestStaleDeleteResultRequired(TypedDict):
    id: str
    partitionKey: str

class RagIngestStaleDeleteResult(_RagIngestStaleDeleteResultRequired, total=False):
    chunkIndex: int | None
    textHash: str | None
    etag: str | None
    revision: int | None

class _RagIngestChunkResultRequired(TypedDict):
    index: int
    id: str
    partitionKey: str
    charStart: int
    charEnd: int
    textLength: int
    textHash: str
    embeddingTextHash: str
    action: Literal['created', 'updated', 'reused', 'deduplicated']
    embeddingAction: Literal['generated', 'reused', 'unchanged', 'deduplicated']

class RagIngestChunkResult(_RagIngestChunkResultRequired, total=False):
    reusedVectorFromId: str | None
    reusedVectorFromPartitionKey: str | None
    deduplicatedFromId: str | None
    deduplicatedFromPartitionKey: str | None
    etag: str | None
    revision: int | None

class _RetrievalVectorFieldQueryRequired(TypedDict):
    field: str

class RetrievalVectorFieldQuery(_RetrievalVectorFieldQueryRequired, total=False):
    weight: float
    query: str | None
    embedding: EmbeddingOptions
    candidateLimit: int | None
    minScore: float | None

class _RagContextRequestRequired(TypedDict):
    retrieval: RetrievalRequest

class RagContextRequest(_RagContextRequestRequired, total=False):
    contentField: str
    maxChars: int
    maxCharsPerChunk: int
    maxCitationsPerChunk: int | None
    contextAssembly: RagContextAssemblyOptions
    graphExpansion: RagContextGraphExpansionOptions
    includeRecords: bool
    includeCitations: bool
    includeContextText: bool
    includeTrace: bool

class _RagContextEvaluationRequestRequired(TypedDict):
    cases: list[RagContextEvaluationCase]

class RagContextEvaluationRequest(_RagContextEvaluationRequestRequired, total=False):
    continueOnError: bool
    includeContext: bool

class _RagContextEvaluationCaseRequired(TypedDict):
    request: RagContextRequest

class RagContextEvaluationCase(_RagContextEvaluationCaseRequired, total=False):
    name: str | None
    expectedGraph: RagContextExpectedGraph
    metadata: dict[str, JSONValue] | None

class RagContextExpectedGraph(TypedDict, total=False):
    nodeIds: list[str]
    edgeIds: list[str]
    provenanceEntityIds: list[str]
    requireSourceGroundedProvenance: bool
    requireGraphContextText: bool
    requireContextTextNotTruncated: bool

class RagContextEvaluationResult(TypedDict, total=False):
    requested: int
    attempted: int
    succeeded: int
    failed: int
    stoppedOnError: bool
    passedCount: int
    passRate: float
    nodeHitRate: float
    edgeHitRate: float
    provenanceHitRate: float
    cases: list[RagContextEvaluationCaseResult]
    failureCategoryCounts: dict[str, int]
    limitReasonCounts: dict[str, int]

class RagContextEvaluationCaseResult(TypedDict, total=False):
    index: int
    name: str | None
    status: Literal['succeeded', 'failed']
    passed: bool
    durationMs: float
    graph: RagContextGraphEvaluationResult
    context: RagContextEnvelope | None
    error: str | None
    queryId: str | None
    profileName: str | None
    expectedAnchorIds: list[str]
    retrievedRecordIds: list[str]
    graphExpandedNodeIds: list[str]
    graphExpandedEdgeIds: list[str]
    lexicalContributionCount: int
    vectorContributionCount: int
    graphContributionCount: int
    failureCategories: list[str]
    limitReasons: list[str]
    graphContribution: RagContextGraphExpansionSummary | None

class RagContextGraphEvaluationResult(TypedDict, total=False):
    status: str | None
    expectedNodeCount: int
    matchedNodeCount: int
    missingNodeIds: list[str]
    expectedEdgeCount: int
    matchedEdgeCount: int
    missingEdgeIds: list[str]
    expectedProvenanceCount: int
    matchedProvenanceCount: int
    missingProvenanceEntityIds: list[str]
    sourceGroundedProvenanceCount: int
    sourceGroundingSatisfied: bool
    graphContextTextPresent: bool
    contextTextTruncated: bool
    passed: bool
    budgetTruncated: bool
    failureModes: RagContextGraphEvaluationFailureModes
    failureCategories: list[str]

class RagContextGraphExpansionOptions(TypedDict, total=False):
    enabled: bool
    collection: str
    graphId: str | None
    namespace: str | None
    tenantId: str | None
    partitionKey: str | None
    seedNodeIds: list[str]
    seedJsonPointers: list[str]
    maxSeedNodes: int
    profile: VyralGraphTraversalProfile
    maxRecords: int | None
    allowPartialGraph: bool
    includeGraphContextText: bool
    maxGraphContextChars: int
    includeGraphProvenance: bool
    maxGraphProvenanceItems: int
    fallbackOnFailure: bool

class RagContextAssemblyOptions(TypedDict, total=False):
    groupBy: Literal['collection', 'sourceKind', 'metadata', 'jsonPointer', None] | None
    groupByPath: str | None
    defaultMaxChunksPerGroup: int | None
    defaultMaxCharsPerGroup: int | None
    failOnUnsatisfiedRequiredGroups: bool
    groups: list[RagContextGroupBudget]

class _RagContextGroupBudgetRequired(TypedDict):
    key: str

class RagContextGroupBudget(_RagContextGroupBudgetRequired, total=False):
    priority: int | None
    required: bool
    minChunks: int | None
    maxChunks: int | None
    minChars: int | None
    maxChars: int | None

class _RagContextEnvelopeRequired(TypedDict):
    query: str
    chunks: list[RagContextChunk]
    citations: list[RagContextCitation]
    totalChars: int

class RagContextEnvelope(_RagContextEnvelopeRequired, total=False):
    omittedCitationCount: int
    contextText: str | None
    contextTextFormat: Literal['citation-markdown', None] | None
    contextTextHash: str | None
    graphContext: RagContextGraphContext | None
    trace: dict[str, JSONValue] | None
    graphExpansion: RagContextGraphExpansionSummary | None

class RagContextGraphProvenance(TypedDict, total=False):
    entityKind: str
    entityId: str
    label: str | None
    nodeType: str | None
    predicate: str | None
    sourceId: str | None
    targetId: str | None
    sourceSpans: list[VyralGraphSourceSpan]
    assertionIds: list[str]

class RagContextGraphContext(TypedDict, total=False):
    status: Literal['not_requested', 'succeeded', 'no_seeds', 'graph_not_found', 'budget_truncated', 'failed']
    collection: str
    graphId: str | None
    seedNodeIds: list[str]
    seedCandidateCount: int
    projection: VyralGraphProjection | None
    nodeCount: int
    edgeCount: int
    sourceRecordCount: int
    sourceTruncated: bool
    contextText: str | None
    contextTextHash: str | None
    contextTextChars: int
    contextTextTruncated: bool
    provenance: list[RagContextGraphProvenance]
    omittedProvenanceCount: int
    failureReason: str | None
    seedJsonPointers: list[str]
    seedDiagnostics: list[RagContextGraphSeedDiagnostic]
    omittedSeedDiagnosticCount: int
    droppedSeedCount: int
    maxSeedNodes: int
    requestedMaxRecords: int | None
    exportedRecordCount: int
    estimatedRequiredRecordCount: int | None
    sourceContinuationToken: str | None
    limitsHit: list[str]

class _RagPromptRequestRequired(TypedDict):
    context: RagContextRequest

class RagPromptRequest(_RagPromptRequestRequired, total=False):
    template: RagPromptTemplateOptions

class RagPromptTemplateOptions(TypedDict, total=False):
    format: Literal['chat-markdown']
    systemInstruction: str | None
    userInstruction: str | None
    citationInstruction: str | None
    includeCitationInstruction: bool
    failOnEmptyContext: bool
    maxPromptChars: int | None

class _RagPromptEnvelopeRequired(TypedDict):
    query: str
    format: Literal['chat-markdown']
    prompt: str
    promptHash: str
    messages: list[RagPromptMessage]
    context: RagContextEnvelope

class RagPromptEnvelope(_RagPromptEnvelopeRequired, total=False):
    trace: dict[str, JSONValue] | None

class _RagPromptMessageRequired(TypedDict):
    role: Literal['system', 'user']
    content: str

class RagPromptMessage(_RagPromptMessageRequired, total=False):
    pass

class _RagContextChunkRequired(TypedDict):
    rank: int
    score: float
    collection: str
    partitionKey: str
    id: str
    text: str
    contentField: str
    charStart: int
    charEnd: int
    originalTextLength: int
    truncated: bool
    contextExcerptHash: str

class RagContextChunk(_RagContextChunkRequired, total=False):
    groupKey: str | None
    citationIds: list[str]
    retrievalDiagnostics: RetrievalDiagnostics
    retrievalMatch: RagContextRetrievalMatch
    metadata: dict[str, JSONValue] | None
    sources: list[VyralSourceReference] | None
    record: VyralRecord

class _RagContextCitationRequired(TypedDict):
    id: str
    chunkRank: int
    collection: str
    partitionKey: str
    recordId: str
    contextCharStart: int
    contextCharEnd: int
    contextExcerptHash: str

class RagContextCitation(_RagContextCitationRequired, total=False):
    sourceId: str | None
    sourceKind: str | None
    sourceUri: str | None
    sourceLabel: str | None
    sourceSpan: dict[str, JSONValue] | None
    includedSourceSpan: dict[str, JSONValue] | None

class _RagContextRetrievalMatchRequired(TypedDict):
    rank: int
    score: float
    collection: str
    searchMode: str

class RagContextRetrievalMatch(_RagContextRetrievalMatchRequired, total=False):
    snippet: str | None

class _TraceRecordRequired(TypedDict):
    id: str
    operation: str
    request: dict[str, JSONValue]
    resultSummary: dict[str, JSONValue]
    startedAt: str
    durationMs: float
    createdAt: str

class TraceRecord(_TraceRecordRequired, total=False):
    adapter: str | None

class TracePruneRequest(TypedDict, total=False):
    operation: str | None
    olderThan: str | None
    keepLatest: int | None
    limit: int | None
    dryRun: bool

class _TraceSummaryRequired(TypedDict):
    totalCount: int
    statusCounts: dict[str, int]
    failureClassCounts: dict[str, int]
    providerStatusCounts: dict[str, int]
    providerCounts: dict[str, int]
    capabilityCounts: dict[str, int]
    operations: list[TraceOperationSummary]

class TraceSummary(_TraceSummaryRequired, total=False):
    operation: str | None

class _TraceOperationSummaryRequired(TypedDict):
    operation: str
    count: int
    firstCreatedAt: str
    latestCreatedAt: str
    adapters: list[str]
    statusCounts: dict[str, int]
    failureClassCounts: dict[str, int]
    providerStatusCounts: dict[str, int]
    providerCounts: dict[str, int]
    capabilityCounts: dict[str, int]

class TraceOperationSummary(_TraceOperationSummaryRequired, total=False):
    pass

class TraceExportRequest(TypedDict, total=False):
    operation: str | None
    limit: int | None
    failOnUnsafeContent: bool

class _TraceExportBundleRequired(TypedDict):
    formatVersion: str
    exportedAt: str
    limit: int
    traceCount: int
    warningCount: int
    contentHash: str
    warnings: list[TraceExportWarning]
    traces: list[TraceRecord]

class TraceExportBundle(_TraceExportBundleRequired, total=False):
    operation: str | None

class _TraceExportWarningRequired(TypedDict):
    traceId: str
    location: str
    reason: str

class TraceExportWarning(_TraceExportWarningRequired, total=False):
    pass

class _TracePruneResultRequired(TypedDict):
    dryRun: bool
    matchedCount: int
    deletedCount: int
    matchedIds: list[str]
    deletedIds: list[str]

class TracePruneResult(_TracePruneResultRequired, total=False):
    operation: str | None
    olderThan: str | None
    keepLatest: int | None
    limit: int | None

class _ServerHealthStatusRequired(TypedDict):
    status: Literal['ok']
    service: str
    version: str
    contractPath: str
    schemaContractPath: str
    storage: ServerStorageStatus
    embedding: ServerEmbeddingStatus
    security: ServerSecurityStatus
    checkedAt: str

class ServerHealthStatus(_ServerHealthStatusRequired, total=False):
    pass

class _ServerStorageStatusRequired(TypedDict):
    recordStore: str
    objectStore: str
    traceStore: str
    canonicalStore: str

class ServerStorageStatus(_ServerStorageStatusRequired, total=False):
    pass

class _ServerEmbeddingStatusRequired(TypedDict):
    provider: str
    modelId: str
    dimensions: int

class ServerEmbeddingStatus(_ServerEmbeddingStatusRequired, total=False):
    runtime: dict[str, JSONValue]

class _ExecutionRuntimeSurfaceRequired(TypedDict):
    status: ExecutionRuntimeAdapterStatus
    plugins: list[ExecutionPluginDescriptor]
    handlers: list[ExecutionHandlerDescriptor]

class ExecutionRuntimeSurface(_ExecutionRuntimeSurfaceRequired, total=False):
    pass

class _EffectiveExecutionRuntimeSurfaceRequired(TypedDict):
    status: ExecutionRuntimeAdapterStatus
    scope: ExecutionRuntimeDiscoveryScope
    handlers: list[ExecutionHandlerDescriptor]

class EffectiveExecutionRuntimeSurface(_EffectiveExecutionRuntimeSurfaceRequired, total=False):
    pass

class _ExecutionRuntimeDiscoveryScopeRequired(TypedDict):
    sharedExecution: bool
    scopeRequired: bool

class ExecutionRuntimeDiscoveryScope(_ExecutionRuntimeDiscoveryScopeRequired, total=False):
    productId: str | None
    tenantId: str | None

class _ExecutionRuntimeAdapterStatusRequired(TypedDict):
    adapter: ExecutionRuntimeAdapterDescriptor
    available: bool
    status: str
    checkedAtUtc: str

class ExecutionRuntimeAdapterStatus(_ExecutionRuntimeAdapterStatusRequired, total=False):
    activeRuns: int | None
    operationalPolicy: ExecutionOperationalPolicy | None
    resumePolicy: ExecutionResumePolicy | None
    details: dict[str, JSONValue] | None

class _ExecutionMaintenanceStatusRequired(TypedDict):
    adapterId: str
    runtimeKind: str
    checkedAtUtc: str
    retentionScope: str
    runCounts: dict[str, int]
    rowCounts: dict[str, int]

class ExecutionMaintenanceStatus(_ExecutionMaintenanceStatusRequired, total=False):
    maxRetainedTerminalRuns: int | None
    artifactDirectory: str | None
    artifactDirectoryCount: int | None
    artifactFileCount: int | None
    artifactBytes: int | None

class ExecutionMaintenancePruneRequest(TypedDict, total=False):
    dryRun: bool
    retainTerminalRuns: int | None

class _ExecutionMaintenancePruneResultRequired(TypedDict):
    dryRun: bool
    retainTerminalRuns: int
    prunedAtUtc: str
    runIds: list[str]
    runs: int
    events: int
    artifacts: int
    checkpoints: int
    timers: int
    externalEvents: int
    leases: int
    artifactDirectories: int

class ExecutionMaintenancePruneResult(_ExecutionMaintenancePruneResultRequired, total=False):
    pass

class ExecutionMaintenanceDispatchReconcileRequest(TypedDict, total=False):
    dryRun: bool
    limit: int | None

class _ExecutionMaintenanceDispatchReconcileResultRequired(TypedDict):
    dryRun: bool
    limit: int
    reconciledAtUtc: str
    candidateRunIds: list[str]
    dispatched: int
    failures: dict[str, str]

class ExecutionMaintenanceDispatchReconcileResult(_ExecutionMaintenanceDispatchReconcileResultRequired, total=False):
    pass

class _ExecutionOperationalPolicyRequired(TypedDict):
    maxActiveRuns: int
    defaultListLimit: int
    maxListLimit: int
    defaultHistoryLimit: int
    maxHistoryLimit: int
    maxPayloadBytes: int
    maxResultBytes: int
    maxStatusDetailsBytes: int
    maxArtifactBytes: int
    maxArtifactInlineBytes: int
    maxTraceMessageChars: int
    maxTraceDetailsBytes: int
    maxRetryAttempts: int
    maxRetryDelaySeconds: float
    maxLeaseTtlSeconds: float
    concurrencyKeyPolicy: str
    defaultTraceSeverity: str
    retentionScope: str

class ExecutionOperationalPolicy(_ExecutionOperationalPolicyRequired, total=False):
    maxRetainedTerminalRuns: int | None
    concurrencyRetryDelayMs: int | None

class _ExecutionResumePolicyRequired(TypedDict):
    mode: str
    interruptedRunningBehavior: str
    scheduledWaitingBehavior: str
    terminalBehavior: str
    pluginCheckpointBehavior: str
    idempotencyScope: str
    createsLinkedFollowUpRuns: bool

class ExecutionResumePolicy(_ExecutionResumePolicyRequired, total=False):
    pass

class _ExecutionRuntimeAdapterDescriptorRequired(TypedDict):
    adapterId: str
    runtimeKind: str
    displayName: str
    version: str
    capabilities: list[str]
    metadata: dict[str, str]

class ExecutionRuntimeAdapterDescriptor(_ExecutionRuntimeAdapterDescriptorRequired, total=False):
    pass

class _ExecutionPluginDescriptorRequired(TypedDict):
    pluginId: str
    name: str
    version: str
    handlers: list[ExecutionHandlerDescriptor]

class ExecutionPluginDescriptor(_ExecutionPluginDescriptorRequired, total=False):
    pass

class _ExecutionHandlerDescriptorRequired(TypedDict):
    handlerId: str
    displayName: str
    maxAttempts: int
    tags: dict[str, str]

class ExecutionHandlerDescriptor(_ExecutionHandlerDescriptorRequired, total=False):
    pluginId: str | None
    description: str | None
    concurrencyKey: str | None

class ExecutionRetryPolicy(TypedDict, total=False):
    maxAttempts: int
    initialDelaySeconds: float
    maxDelaySeconds: float
    backoffMultiplier: float

class _ExecutionRunRequestRequired(TypedDict):
    handlerId: str

class ExecutionRunRequest(_ExecutionRunRequestRequired, total=False):
    pluginId: str | None
    payload: JSONValue
    idempotencyKey: str | None
    correlationId: str | None
    scope: ExecutionScope | None
    scheduledAtUtc: str | None
    retryPolicy: ExecutionRetryPolicy
    tags: dict[str, str]

class _ExecutionRunRequired(TypedDict):
    admission: AdmissionReceipt
    id: str
    handlerId: str
    status: Literal['queued', 'waiting', 'running', 'succeeded', 'failed', 'cancelled', 'rejected', 'timed_out']
    attempt: int
    maxAttempts: int
    correlationId: str
    payloadHash: str
    createdAtUtc: str
    updatedAtUtc: str
    cancellationRequested: bool
    tags: dict[str, str]

class ExecutionRun(_ExecutionRunRequired, total=False):
    pluginId: str | None
    retryPolicy: dict[str, JSONValue]
    scope: ExecutionScope | None
    payload: JSONValue
    scheduledAtUtc: str | None
    startedAtUtc: str | None
    completedAtUtc: str | None
    durationMs: float | None
    requested: int | None
    attempted: int | None
    succeeded: int | None
    failed: int | None
    progress: float | None
    currentStep: str | None
    failureClass: str | None
    error: str | None
    result: JSONValue
    statusDetails: dict[str, JSONValue] | None

class _ExecutionTraceEventRequired(TypedDict):
    id: str
    sequenceId: str
    runId: str
    type: str
    timestampUtc: str
    attempt: int
    severity: str
    context: dict[str, str]

class ExecutionTraceEvent(_ExecutionTraceEventRequired, total=False):
    stepId: str | None
    status: str | None
    message: str | None
    details: dict[str, JSONValue] | None

class _ExecutionArtifactRequired(TypedDict):
    id: str
    runId: str
    name: str
    kind: str
    contentHash: str
    sizeBytes: int
    createdAtUtc: str
    metadata: dict[str, str]

class ExecutionArtifact(_ExecutionArtifactRequired, total=False):
    mediaType: str | None
    text: str | None
    content: JSONValue
    uri: str | None

class _ExecutionCheckpointRequired(TypedDict):
    runId: str
    key: str
    contentHash: str
    updatedAtUtc: str
    metadata: dict[str, str]

class ExecutionCheckpoint(_ExecutionCheckpointRequired, total=False):
    content: JSONValue

class _ExecutionScopeRequired(TypedDict):
    productId: str
    tenantId: str

class ExecutionScope(_ExecutionScopeRequired, total=False):
    serviceIdentity: str | None

class ExecutionRunUpdate(TypedDict, total=False):
    status: str | None
    requested: int | None
    attempted: int | None
    succeeded: int | None
    failed: int | None
    progress: float | None
    currentStep: str | None
    failureClass: str | None
    error: str | None
    result: JSONValue
    statusDetails: dict[str, JSONValue] | None

class _ExecutionRunResultRequired(TypedDict):
    status: str

class ExecutionRunResult(_ExecutionRunResultRequired, total=False):
    result: JSONValue
    failureClass: str | None
    error: str | None
    statusDetails: dict[str, JSONValue] | None

class _ExecutionArtifactWriteRequired(TypedDict):
    name: str
    metadata: dict[str, str]

class ExecutionArtifactWrite(_ExecutionArtifactWriteRequired, total=False):
    kind: str | None
    mediaType: str | None
    text: str | None
    content: JSONValue
    uri: str | None

class _ExecutionCheckpointWriteRequired(TypedDict):
    key: str
    metadata: dict[str, str]

class ExecutionCheckpointWrite(_ExecutionCheckpointWriteRequired, total=False):
    content: JSONValue

class _ExecutionExternalEventRequestRequired(TypedDict):
    name: str

class ExecutionExternalEventRequest(_ExecutionExternalEventRequestRequired, total=False):
    runId: str | None
    payload: JSONValue

class _ExecutionExternalEventRequired(TypedDict):
    id: str
    name: str
    raisedAtUtc: str

class ExecutionExternalEvent(_ExecutionExternalEventRequired, total=False):
    runId: str | None
    payload: JSONValue

class _ExecutionTimerRequired(TypedDict):
    id: str
    name: str
    fireAtUtc: str
    createdAtUtc: str

class ExecutionTimer(_ExecutionTimerRequired, total=False):
    runId: str | None
    payload: JSONValue

class _ExecutionWaitResultRequired(TypedDict):
    name: str
    outcome: str

class ExecutionWaitResult(_ExecutionWaitResultRequired, total=False):
    event: ExecutionExternalEvent | None
    timer: ExecutionTimer | None

class _ExecutionExternalWorkerLeaseRequestRequired(TypedDict):
    workerId: str
    handlerIds: list[str]
    ttlSeconds: float

class ExecutionExternalWorkerLeaseRequest(_ExecutionExternalWorkerLeaseRequestRequired, total=False):
    runId: str | None

class _ExecutionExternalWorkerLeaseRequired(TypedDict):
    leaseKey: str
    leaseToken: str
    workerId: str
    run: ExecutionRun
    acquiredAtUtc: str
    expiresAtUtc: str

class ExecutionExternalWorkerLease(_ExecutionExternalWorkerLeaseRequired, total=False):
    pass

class _ExecutionExternalWorkerHeartbeatRequestRequired(TypedDict):
    leaseKey: str
    leaseToken: str
    workerId: str
    ttlSeconds: float

class ExecutionExternalWorkerHeartbeatRequest(_ExecutionExternalWorkerHeartbeatRequestRequired, total=False):
    pass

class _ExecutionExternalWorkerReportRequestRequired(TypedDict):
    leaseKey: str
    leaseToken: str
    workerId: str
    update: ExecutionRunUpdate

class ExecutionExternalWorkerReportRequest(_ExecutionExternalWorkerReportRequestRequired, total=False):
    pass

class _ExecutionExternalWorkerEventRequestRequired(TypedDict):
    leaseKey: str
    leaseToken: str
    workerId: str
    type: str
    severity: str

class ExecutionExternalWorkerEventRequest(_ExecutionExternalWorkerEventRequestRequired, total=False):
    message: str | None
    details: dict[str, JSONValue] | None

class _ExecutionExternalWorkerArtifactRequestRequired(TypedDict):
    leaseKey: str
    leaseToken: str
    workerId: str
    artifact: ExecutionArtifactWrite

class ExecutionExternalWorkerArtifactRequest(_ExecutionExternalWorkerArtifactRequestRequired, total=False):
    pass

class _ExecutionExternalWorkerCheckpointRequestRequired(TypedDict):
    leaseKey: str
    leaseToken: str
    workerId: str
    checkpoint: ExecutionCheckpointWrite

class ExecutionExternalWorkerCheckpointRequest(_ExecutionExternalWorkerCheckpointRequestRequired, total=False):
    pass

class _ExecutionExternalWorkerCheckpointReadRequestRequired(TypedDict):
    leaseKey: str
    leaseToken: str
    workerId: str
    key: str

class ExecutionExternalWorkerCheckpointReadRequest(_ExecutionExternalWorkerCheckpointReadRequestRequired, total=False):
    pass

class _ExecutionExternalWorkerWaitRequestRequired(TypedDict):
    leaseKey: str
    leaseToken: str
    workerId: str
    kind: Literal['external_event', 'timer']
    name: str

class ExecutionExternalWorkerWaitRequest(_ExecutionExternalWorkerWaitRequestRequired, total=False):
    timeoutAtUtc: str | None
    fireAtUtc: str | None
    payload: JSONValue

class _ExecutionExternalWorkerWaitResponseRequired(TypedDict):
    run: ExecutionRun
    suspended: bool

class ExecutionExternalWorkerWaitResponse(_ExecutionExternalWorkerWaitResponseRequired, total=False):
    outcome: ExecutionWaitResult | None

class _ExecutionExternalWorkerCompletionRequestRequired(TypedDict):
    leaseKey: str
    leaseToken: str
    workerId: str
    result: ExecutionRunResult

class ExecutionExternalWorkerCompletionRequest(_ExecutionExternalWorkerCompletionRequestRequired, total=False):
    pass

class _ServerSecurityStatusRequired(TypedDict):
    apiKeyRequired: bool
    apiKeyHeader: str
    providerRunLimits: dict[str, JSONValue]

class ServerSecurityStatus(_ServerSecurityStatusRequired, total=False):
    pass

class _ServerReadinessReportRequired(TypedDict):
    status: Literal['ok', 'warning', 'failed', 'unknown']
    ready: bool
    summary: str
    checkedAt: str
    health: ServerHealthStatus
    checks: list[ServerReadinessCheck]
    blockers: list[str]
    warnings: list[str]
    embedding: dict[str, JSONValue]
    providers: ServerProviderReadinessSummary
    operationalLimits: dict[str, JSONValue]

class ServerReadinessReport(_ServerReadinessReportRequired, total=False):
    pass

class _ServerReadinessCheckRequired(TypedDict):
    id: str
    status: Literal['ok', 'warning', 'failed', 'unknown']
    message: str
    details: dict[str, JSONValue]

class ServerReadinessCheck(_ServerReadinessCheckRequired, total=False):
    pass

class _ServerProviderReadinessSummaryRequired(TypedDict):
    providerCount: int
    capabilityCount: int
    callableCapabilityCount: int
    readyCapabilityCount: int
    unvalidatedCapabilityCount: int
    networkProviderCount: int
    authProviderCount: int

class ServerProviderReadinessSummary(_ServerProviderReadinessSummaryRequired, total=False):
    pass

class _EmbeddingProviderDescriptorRequired(TypedDict):
    provider: str
    displayName: str
    description: str
    defaultModelId: str
    defaultDimensions: int
    local: bool
    cpuOnly: bool
    requiresNetwork: bool
    semanticQuality: str
    defaultQueryPrefix: str | None
    defaultPassagePrefix: str | None
    defaultSymmetricPrefix: str | None

class EmbeddingProviderDescriptor(_EmbeddingProviderDescriptorRequired, total=False):
    pass

class _EmbeddingProviderGuidanceRequired(TypedDict):
    provider: str
    displayName: str
    semanticQuality: str
    defaultDimensions: int
    hardwareProfile: str
    requiresModelFiles: bool
    realisticForSemanticRetrieval: bool
    recommendedFor: list[str]
    cautions: list[str]
    suggestedRetrievalProfiles: list[str]
    suggestedEvaluationVariants: list[str]
    selectionNotes: list[str]

class EmbeddingProviderGuidance(_EmbeddingProviderGuidanceRequired, total=False):
    defaultQueryPrefix: str | None
    defaultPassagePrefix: str | None

class EmbeddingRequest(TypedDict, total=False):
    """Request one or more vectors from the server's configured embedding provider. Supply either text, texts, or both."""
    text: str | None
    texts: list[str] | None
    purpose: Literal['query', 'passage', 'document', 'symmetric'] | None
    queryPrefix: str | None
    passagePrefix: str | None
    symmetricPrefix: str | None

class _EmbeddingResponseRequired(TypedDict):
    provider: str
    modelId: str
    dimensions: int
    purpose: str
    items: list[EmbeddingResult]

class EmbeddingResponse(_EmbeddingResponseRequired, total=False):
    pass

class _EmbeddingJobRequired(TypedDict):
    admission: AdmissionReceipt
    id: str
    status: Literal['queued', 'running', 'succeeded', 'failed', 'cancelled', 'rejected']
    provider: str
    modelId: str
    dimensions: int
    purpose: str
    requestHash: str
    createdAt: str
    cancellationRequested: bool
    requested: int
    attempted: int
    succeeded: int
    failed: int
    progress: float

class EmbeddingJob(_EmbeddingJobRequired, total=False):
    startedAt: str | None
    completedAt: str | None
    durationMs: float | None
    currentIndex: int | None
    failureClass: str | None
    error: str | None
    result: EmbeddingResponse

class _EmbeddingResultRequired(TypedDict):
    index: int
    textLength: int
    preparedTextLength: int
    prefixApplied: bool
    prefixLength: int
    values: list[float]

class EmbeddingResult(_EmbeddingResultRequired, total=False):
    pass

class _ProviderProfileRequired(TypedDict):
    id: str
    displayName: str
    family: str
    local: bool
    requiresNetwork: bool
    auth: str
    capabilities: list[str]

class ProviderProfile(_ProviderProfileRequired, total=False):
    profileVersion: str
    implementationVersion: str
    configHash: str | None

class _ProviderCapabilityDescriptorRequired(TypedDict):
    id: str
    operations: list[str]

class ProviderCapabilityDescriptor(_ProviderCapabilityDescriptorRequired, total=False):
    version: str
    inputLimits: dict[str, JSONValue]
    outputLimits: dict[str, JSONValue]
    toolPolicy: str
    modePolicies: list[ProviderModePolicy]
    unsupportedFeatures: list[str]

class _ProviderQualificationRequired(TypedDict):
    provider: str
    capability: str
    operationSet: list[str]
    status: Literal['unvalidated', 'validated', 'failed', 'unsupported']
    driftTriggers: list[str]
    unsupportedFeatures: list[str]
    evidenceRefs: list[str]

class ProviderQualification(_ProviderQualificationRequired, total=False):
    configHash: str | None
    lastValidatedAt: str | None

class ProviderQualificationRequest(TypedDict, total=False):
    capability: str | None
    mode: str

class _ProviderDoctorResultRequired(TypedDict):
    provider: str
    status: Literal['ok', 'warning', 'failed', 'unknown']
    summary: str
    generatedAt: str
    checks: list[ProviderDoctorCheck]
    metadata: dict[str, JSONValue]

class ProviderDoctorResult(_ProviderDoctorResultRequired, total=False):
    pass

class _ProviderDoctorCheckRequired(TypedDict):
    id: str
    status: Literal['ok', 'warning', 'failed', 'unknown']
    message: str
    details: dict[str, JSONValue]

class ProviderDoctorCheck(_ProviderDoctorCheckRequired, total=False):
    pass

class _ProviderCapabilityMatrixRequired(TypedDict):
    generatedAt: str
    capabilityIds: list[str]
    items: list[ProviderCapabilityMatrixItem]
    disabledProviders: list[ProviderDisabledInfo]
    failureClasses: list[str]
    operationalLimits: dict[str, JSONValue]
    notes: list[str]

class ProviderCapabilityMatrix(_ProviderCapabilityMatrixRequired, total=False):
    pass

class _ProviderCapabilityMatrixItemRequired(TypedDict):
    provider: str
    displayName: str
    family: str
    registered: bool
    enabled: bool
    registrationStatus: str
    local: bool
    requiresNetwork: bool
    auth: str
    capabilityIds: list[str]
    capabilities: dict[str, ProviderCapabilitySupport]
    supportsModelListing: bool
    supportsQuota: bool
    supportsAsyncJobs: bool
    supportsArtifacts: bool
    artifactPolicy: str
    failureSemantics: list[str]

class ProviderCapabilityMatrixItem(_ProviderCapabilityMatrixItemRequired, total=False):
    registrationHint: str | None

class _ProviderCapabilitySupportRequired(TypedDict):
    supported: bool
    operations: list[str]
    modes: list[str]
    toolPolicy: str
    unsupportedFeatures: list[str]

class ProviderCapabilitySupport(_ProviderCapabilitySupportRequired, total=False):
    pass

class _ProviderReadinessEnvelopeRequired(TypedDict):
    generatedAt: str
    items: list[ProviderCapabilityReadiness]
    disabledProviders: list[ProviderDisabledInfo]

class ProviderReadinessEnvelope(_ProviderReadinessEnvelopeRequired, total=False):
    pass

class _ProviderDisabledInfoRequired(TypedDict):
    providerId: str
    registrationStatus: str
    enableLiveTargets: bool
    hint: str

class ProviderDisabledInfo(_ProviderDisabledInfoRequired, total=False):
    pass

class _ProviderModelListResultRequired(TypedDict):
    provider: str
    status: Literal['succeeded', 'unsupported', 'failed']
    source: str
    items: list[ProviderModelDescriptor]
    generatedAt: str

class ProviderModelListResult(_ProviderModelListResultRequired, total=False):
    defaultModelId: str | None
    failureClass: str | None
    providerStatus: str | None

class _ProviderModelDescriptorRequired(TypedDict):
    id: str
    default: bool
    capabilities: list[str]
    metadata: dict[str, JSONValue]

class ProviderModelDescriptor(_ProviderModelDescriptorRequired, total=False):
    displayName: str | None

class _ProviderQuotaResultRequired(TypedDict):
    provider: str
    status: Literal['succeeded', 'unsupported', 'unavailable', 'failed']
    source: str
    advisory: bool
    items: list[ProviderQuotaBucket]
    generatedAt: str
    metadata: dict[str, JSONValue]

class ProviderQuotaResult(_ProviderQuotaResultRequired, total=False):
    failureClass: str | None
    providerStatus: str | None

class _ProviderQuotaBucketRequired(TypedDict):
    limitId: str
    metadata: dict[str, JSONValue]

class ProviderQuotaBucket(_ProviderQuotaBucketRequired, total=False):
    limitName: str | None
    primary: ProviderQuotaWindow | None
    secondary: ProviderQuotaWindow | None
    rateLimitReachedType: str | None
    planType: str | None
    credits: dict[str, JSONValue] | None

class ProviderQuotaWindow(TypedDict, total=False):
    usedPercent: float | None
    remainingPercent: float | None
    windowDurationMins: int | None
    resetsAtUnixSeconds: int | None
    resetsAt: str | None

class _ProviderCapabilityReadinessRequired(TypedDict):
    provider: str
    capability: str
    registrationStatus: str
    operations: list[str]
    modes: list[str]
    qualificationStatus: Literal['unvalidated', 'validated', 'failed', 'unsupported']
    callable: bool
    ready: bool
    canRunUnvalidated: bool
    reason: str
    evidenceRefs: list[str]
    driftTriggers: list[str]
    unsupportedFeatures: list[str]
    local: bool
    requiresNetwork: bool
    auth: str
    authRequired: bool
    operationalLimits: dict[str, JSONValue]

class ProviderCapabilityReadiness(_ProviderCapabilityReadinessRequired, total=False):
    registrationHint: str | None
    configHash: str | None
    lastValidatedAt: str | None

class _ProviderModePolicyRequired(TypedDict):
    id: str
    maxInputBytes: int
    maxOutputBytes: int
    toolPolicy: str
    allowNetwork: bool
    allowSourceWrites: bool
    reviewRequired: bool
    traceRequired: bool
    timeoutSeconds: int

class ProviderModePolicy(_ProviderModePolicyRequired, total=False):
    allowedOutputKinds: list[str]

class _ProviderTargetDescriptorRequired(TypedDict):
    profile: ProviderProfile
    capabilities: list[ProviderCapabilityDescriptor]

class ProviderTargetDescriptor(_ProviderTargetDescriptorRequired, total=False):
    pass

class _ProviderRunRequestRequired(TypedDict):
    capability: str
    payload: AiChatPayload | AiExtractPayload | AiRerankPayload | AiReviewPayload | AiScaffoldPayload | AiToolPlanPayload | dict[str, JSONValue]

class ProviderRunRequest(_ProviderRunRequestRequired, total=False):
    provider: str | None
    operation: str
    mode: str
    modelId: str | None
    correlationId: str
    contextRefs: list[str]
    timeoutSeconds: int | None
    maxOutputBytes: int | None
    artifactDirectory: str | None
    meteringContext: AiMeteringContext | None

class _ProviderRunResultRequired(TypedDict):
    status: Literal['Succeeded', 'Failed', 'TimedOut', 'Rejected', 'Unsupported', 'NotConfigured', 'Cancelled']
    provider: str
    capability: str
    operation: str
    mode: str
    output: AiChatResult | AiExtractResult | AiRerankResult | AiReviewResult | AiScaffoldResult | AiToolPlanResult | dict[str, JSONValue]

class ProviderRunResult(_ProviderRunResultRequired, total=False):
    failureClass: str | None
    providerStatus: str | None
    error: str | None
    rejection: ProviderRunRejectionDiagnostic | None
    trace: ProviderTraceEvent | None
    metering: list[AiMeteringReceipt]

class _ProviderRunRejectionDiagnosticRequired(TypedDict):
    source: Literal['vyral_policy', 'vyral_guardrail', 'vyral_classification', 'provider_policy', 'provider_runtime', 'configuration', 'unsupported', 'unknown']
    category: str
    message: str
    contentUsable: bool
    parsedOutputPresent: bool
    structuredOutputAccepted: bool
    parsedOutputDisposition: Literal['none', 'not_capability_output', 'quarantine_for_operator_review', 'debug_only']
    decisionAuthority: Literal['vyral_preflight', 'vyral_policy', 'vyral_guardrail', 'vyral_structured_output_validation', 'provider_process_exit', 'provider_response_status', 'server_guardrail', 'unknown']
    processOutcome: Literal['not_started', 'exit_zero', 'exit_nonzero', 'cancelled', 'timed_out', 'output_truncated', 'http_success', 'http_failure', 'unknown']
    retryable: bool
    retryRecommendation: Literal['do_not_retry', 'retry_after_backoff', 'retry_with_smaller_input', 'retry_with_redacted_input', 'retry_with_stricter_structured_output_instructions', 'fix_configuration', 'use_supported_capability', 'operator_review']
    operatorReviewRecommended: bool

class ProviderRunRejectionDiagnostic(_ProviderRunRejectionDiagnosticRequired, total=False):
    structuredOutputValidationStatus: str | None

class _ProviderRunJobRequired(TypedDict):
    admission: AdmissionReceipt
    id: str
    status: Literal['Succeeded', 'Failed', 'TimedOut', 'Rejected', 'Unsupported', 'NotConfigured', 'Cancelled', 'Queued', 'Running']
    provider: str
    capability: str
    operation: str
    mode: str
    correlationId: str
    requestHash: str
    createdAt: str
    cancellationRequested: bool

class ProviderRunJob(_ProviderRunJobRequired, total=False):
    startedAt: str | None
    completedAt: str | None
    durationMs: float | None
    traceId: str | None
    failureClass: str | None
    providerStatus: str | None
    result: ProviderRunResult | None
    metering: list[AiMeteringReceipt]

class ProviderTraceEvent(TypedDict, total=False):
    traceId: str
    timestamp: str
    provider: str
    capability: str
    operation: str
    mode: str
    inputHash: str | None
    outputHash: str | None
    modelId: str | None
    adapterId: str | None
    configHash: str | None
    durationMs: float
    failureClass: str | None
    authorityBoundary: str
    artifactRefs: list[str]
    meteringReceiptHashes: list[str]

class AiMeteringContext(TypedDict, total=False):
    """Optional caller correlation for a provider thread, runner session, or turn. Vyral-owned run identifiers are assigned at admission."""
    providerThreadId: str | None
    runnerSessionId: str | None
    turnId: str | None
    sequence: int | None
    previousReceiptHash: str | None

class AiMeteringSubject(TypedDict, total=False):
    """Correlated Vyral run, provider thread, runner session, and turn scopes. Their relationship is intentionally not assumed to be one-to-one."""
    providerRunId: str | None
    executionRunId: str | None
    providerThreadId: str | None
    runnerSessionId: str | None
    turnId: str | None
    correlationId: str | None

class _AiMeteringPeriodRequired(TypedDict):
    observedStartedAt: str
    observedCompletedAt: str
    elapsedDurationMs: int

class AiMeteringPeriod(_AiMeteringPeriodRequired, total=False):
    queueDurationMs: int | None
    activeDurationMs: int | None
    idleDurationMs: int | None
    providerDurationMs: int | None

class _AiMeteringMeasurementRequired(TypedDict):
    name: str
    value: int
    unit: str
    source: Literal['provider_response', 'provider_event_stream', 'runner_observer', 'gateway_observer', 'consumer_inference']
    quality: Literal['reported', 'observed', 'estimated', 'reconciled', 'unknown']

class AiMeteringMeasurement(_AiMeteringMeasurementRequired, total=False):
    sourceId: str | None
    method: str | None
    tokenizerId: str | None

class _AiMeteringEvidenceReferenceRequired(TypedDict):
    kind: str
    digest: str
    redacted: bool

class AiMeteringEvidenceReference(_AiMeteringEvidenceReferenceRequired, total=False):
    uri: str | None
    mediaType: str | None

class _AiMeteringIntegrityRequired(TypedDict):
    algorithm: Literal['ES256']
    issuer: str
    keyId: str
    payloadHash: str
    signature: str

class AiMeteringIntegrity(_AiMeteringIntegrityRequired, total=False):
    pass

class _AiMeteringReceiptRequired(TypedDict):
    schema: Literal['vyral.ai-metering.v1']
    receiptId: str
    kind: Literal['observation', 'summary']
    subject: AiMeteringSubject
    provider: str
    capability: str
    operation: str
    outcome: Literal['succeeded', 'failed', 'timed_out', 'rejected', 'unsupported', 'not_configured', 'cancelled']
    period: AiMeteringPeriod
    measurements: list[AiMeteringMeasurement]
    evidence: list[AiMeteringEvidenceReference]
    completeness: Literal['complete', 'partial', 'sampled', 'unknown']
    attestationLevel: Literal['self_reported', 'observer_signed', 'provider_attested', 'reconciled', 'hardware_attested']
    issuedAt: str

class AiMeteringReceipt(_AiMeteringReceiptRequired, total=False):
    modelId: str | None
    adapterId: str | None
    sequence: int | None
    previousReceiptHash: str | None
    integrity: AiMeteringIntegrity | None

class _AiMeteringReviewFindingRequired(TypedDict):
    code: str
    severity: Literal['info', 'warning', 'error']
    message: str
    receiptIds: list[str]
    measurementNames: list[str]

class AiMeteringReviewFinding(_AiMeteringReviewFindingRequired, total=False):
    pass

class _AiMeteringScopeRequired(TypedDict):
    kind: Literal['provider_thread', 'runner_session']
    id: str

class AiMeteringScope(_AiMeteringScopeRequired, total=False):
    pass

class _AiMeteringAggregatePeriodRequired(TypedDict):
    observedStartedAt: str
    observedCompletedAt: str
    wallSpanDurationMs: int
    summedElapsedDurationMs: int
    concurrentIntervalsDetected: bool

class AiMeteringAggregatePeriod(_AiMeteringAggregatePeriodRequired, total=False):
    summedQueueDurationMs: int | None
    summedActiveDurationMs: int | None
    summedIdleDurationMs: int | None
    summedProviderDurationMs: int | None

class _AiMeteringAggregateMeasurementRequired(TypedDict):
    receiptKind: Literal['observation', 'summary']
    evidenceIssuer: str
    name: str
    value: int
    unit: str
    source: Literal['provider_response', 'provider_event_stream', 'runner_observer', 'gateway_observer', 'consumer_inference']
    quality: Literal['reported', 'observed', 'estimated', 'reconciled', 'unknown']
    provider: str
    receiptCount: int

class AiMeteringAggregateMeasurement(_AiMeteringAggregateMeasurementRequired, total=False):
    modelId: str | None
    method: str | None
    tokenizerId: str | None

class _AiMeteringAggregateRequired(TypedDict):
    receiptCount: int
    summaryReceiptCount: int
    observationReceiptCount: int
    providerRunCount: int
    period: AiMeteringAggregatePeriod
    measurements: list[AiMeteringAggregateMeasurement]

class AiMeteringAggregate(_AiMeteringAggregateRequired, total=False):
    pass

class _AiMeteringReviewRequired(TypedDict):
    schema: Literal['vyral.ai-metering-review.v1']
    reviewId: str
    rulesetId: str
    scope: AiMeteringScope
    receiptHashes: list[str]
    verdict: Literal['verified', 'verified_with_gaps', 'rejected']
    findings: list[AiMeteringReviewFinding]
    aggregate: AiMeteringAggregate | None
    reviewedAt: str

class AiMeteringReview(_AiMeteringReviewRequired, total=False):
    """A separately reviewable assessment over the exact ordered receipt set identified by receiptHashes. The basic-v1 ruleset does not by itself claim that this set exhausts every run in the named scope."""
    integrity: AiMeteringIntegrity | None

class AiChatPayload(TypedDict, total=False):
    messages: list[AiMessage]
    system: str | None
    maxOutputChars: int | None

class _AiChatResultRequired(TypedDict):
    message: AiMessage
    stopReason: str

class AiChatResult(_AiChatResultRequired, total=False):
    pass

class _AiExtractPayloadRequired(TypedDict):
    text: str

class AiExtractPayload(_AiExtractPayloadRequired, total=False):
    schema: dict[str, JSONValue] | None
    instructions: str | None

class _AiExtractResultRequired(TypedDict):
    data: dict[str, JSONValue]
    validationStatus: str

class AiExtractResult(_AiExtractResultRequired, total=False):
    pass

class _AiRerankPayloadRequired(TypedDict):
    query: str
    candidates: list[AiRerankCandidate]

class AiRerankPayload(_AiRerankPayloadRequired, total=False):
    limit: int | None

class _AiRerankResultRequired(TypedDict):
    items: list[AiRerankItem]
    validationStatus: str

class AiRerankResult(_AiRerankResultRequired, total=False):
    pass

class _AiRerankCandidateRequired(TypedDict):
    id: str
    text: str

class AiRerankCandidate(_AiRerankCandidateRequired, total=False):
    metadata: dict[str, JSONValue] | None

class _AiRerankItemRequired(TypedDict):
    id: str
    rank: int
    score: float

class AiRerankItem(_AiRerankItemRequired, total=False):
    pass

class AiReviewPayload(TypedDict, total=False):
    prompt: str | None
    subject: str | None
    instructions: str | None
    references: list[AiReference]
    maxFindings: int | None

class _AiReviewResultRequired(TypedDict):
    summary: str
    findings: list[AiReviewFinding]
    validationStatus: str
    references: list[AiReference]

class AiReviewResult(_AiReviewResultRequired, total=False):
    pass

class _AiReviewFindingRequired(TypedDict):
    id: str
    severity: str
    message: str
    evidenceRefs: list[str]

class AiReviewFinding(_AiReviewFindingRequired, total=False):
    category: str | None
    location: AiReviewLocation
    confidence: float | None

class AiReviewLocation(TypedDict, total=False):
    path: str | None
    line: int | None
    column: int | None
    symbol: str | None

class _AiScaffoldPayloadRequired(TypedDict):
    prompt: str

class AiScaffoldPayload(_AiScaffoldPayloadRequired, total=False):
    instructions: str | None
    target: str | None
    references: list[AiReference]
    allowedPaths: list[str]
    maxArtifacts: int | None

class _AiScaffoldResultRequired(TypedDict):
    summary: str
    artifacts: list[AiScaffoldArtifact]
    validationStatus: str
    references: list[AiReference]

class AiScaffoldResult(_AiScaffoldResultRequired, total=False):
    pass

class _AiScaffoldArtifactRequired(TypedDict):
    path: str
    kind: str
    action: str
    evidenceRefs: list[str]

class AiScaffoldArtifact(_AiScaffoldArtifactRequired, total=False):
    content: str | None
    contentHash: str | None
    metadata: dict[str, JSONValue] | None

class _AiReferenceRequired(TypedDict):
    id: str
    kind: str

class AiReference(_AiReferenceRequired, total=False):
    uri: str | None
    contentHash: str | None
    label: str | None
    metadata: dict[str, JSONValue] | None

class _AiToolPlanPayloadRequired(TypedDict):
    prompt: str

class AiToolPlanPayload(_AiToolPlanPayloadRequired, total=False):
    tools: list[AiToolDefinition]

class _AiToolPlanResultRequired(TypedDict):
    calls: list[AiToolCallProposal]
    validationStatus: str

class AiToolPlanResult(_AiToolPlanResultRequired, total=False):
    pass

class _AiToolCallProposalRequired(TypedDict):
    tool: str
    arguments: dict[str, JSONValue]
    requiresApproval: bool

class AiToolCallProposal(_AiToolCallProposalRequired, total=False):
    rationale: str | None

class _AiToolDefinitionRequired(TypedDict):
    name: str

class AiToolDefinition(_AiToolDefinitionRequired, total=False):
    description: str | None
    inputSchema: dict[str, JSONValue] | None

class _AiMessageRequired(TypedDict):
    role: str
    content: str

class AiMessage(_AiMessageRequired, total=False):
    contentBlocks: list[dict[str, JSONValue]] | None

class ProblemDetails(TypedDict, total=False):
    type: str | None
    title: str | None
    status: int | None
    detail: str | None
    instance: str | None
    admission: AdmissionReceipt | None

class VyralGraphCollectionImportPreflightResult(TypedDict, total=False):
    collection: str
    generatedAt: str
    valid: bool
    readyToImport: bool
    graphId: str
    namespace: str
    tenantId: str
    partitionKey: str
    collectionExists: bool
    collectionPolicyStatus: str
    wouldCreateCollection: bool
    wouldReplaceCollection: bool
    wouldAllowNonGraphPolicy: bool
    createCollectionIfMissing: bool
    replaceExisting: bool
    allowNonGraphPolicy: bool
    nodeCount: int
    edgeCount: int
    assertionCount: int
    reviewCount: int
    projectionCount: int
    recordCount: int
    maxRecords: int
    warningCount: int
    warnings: list[str]
    errorCount: int
    errors: list[str]

class VyralGraphDoctorRequest(TypedDict, total=False):
    graphId: str | None
    namespace: str | None
    tenantId: str | None
    partitionKey: str | None
    targetCollection: str | None
    targetPartitionKeys: list[str]
    seedJsonPointers: list[str]
    maxGraphRecords: int | None
    maxTargetRecords: int
    allowPartialGraph: bool
    includeAnomalies: bool
    anomalyLimit: int

class VyralGraphSeedCoverage(TypedDict, total=False):
    targetCollection: str
    targetRecordCount: int
    targetTruncated: bool
    seedJsonPointers: list[str]
    recordsWithSeedMetadataCount: int
    seedValueCount: int
    uniqueSeedValueCount: int
    resolvedSeedNodeCount: int
    unresolvedSeedNodeCount: int
    seedCoverage: float
    resolvedSeedCoverage: float
    resolvedSeedNodeIds: list[str]
    unresolvedSeedNodeIds: list[str]

class VyralGraphDoctorResult(TypedDict, total=False):
    collection: str
    generatedAt: str
    ready: bool
    status: str
    failureMode: str | None
    graphReady: bool
    graphRecordCount: int
    graphNodeCount: int
    graphEdgeCount: int
    graphTruncated: bool
    inspection: VyralGraphCollectionInspectionResult | None
    seedCoverage: VyralGraphSeedCoverage | None
    recommendedActions: list[str]

class RagContextGraphSeedDiagnostic(TypedDict, total=False):
    recordId: str | None
    partitionKey: str | None
    pointer: str
    found: bool
    rawValue: str | None
    normalizedValue: str | None
    skippedReason: str | None
    accepted: bool

class RagContextGraphExpansionSummary(TypedDict, total=False):
    expansionAttempted: bool
    expansionEnabled: bool
    collection: str
    graphId: str | None
    namespace: str | None
    tenantId: str | None
    partitionKey: str | None
    status: str
    skippedReason: str | None
    profileId: str | None
    maxDepth: int
    nodeLimit: int
    edgeLimit: int
    maxRecords: int | None
    maxGraphContextChars: int
    maxGraphProvenanceItems: int
    retrievedRecordIds: list[str]
    sourceRecordIdsTouched: list[str]
    seedJsonPointers: list[str]
    seedCandidateCount: int
    seedCount: int
    seedNodeIds: list[str]
    droppedSeedCount: int
    nodesAdded: int
    edgesAdded: int
    relationshipsAdded: int
    sourceRecordCount: int
    sourceTruncated: bool
    exportedRecordCount: int
    estimatedRequiredRecordCount: int | None
    limitsHit: list[str]
    groundingStatus: str
    graphContextInfluencedContextText: bool
    contextTextTruncated: bool
    omittedProvenanceCount: int

class _GraphJobRequired(TypedDict):
    admission: AdmissionReceipt
    id: str
    kind: Literal['import', 'inspect', 'doctor']
    status: Literal['queued', 'running', 'succeeded', 'failed', 'cancelled', 'rejected']
    collection: str
    requestHash: str
    createdAt: str
    cancellationRequested: bool
    requested: int
    attempted: int
    succeeded: int
    failed: int
    progress: float
    recordCount: int
    nodeCount: int
    edgeCount: int
    assertionCount: int
    reviewCount: int
    projectionCount: int
    warningCount: int
    errorCount: int
    anomalyCount: int

class GraphJob(_GraphJobRequired, total=False):
    startedAt: str | None
    completedAt: str | None
    durationMs: float | None
    graphId: str | None
    partitionKey: str | None
    failureClass: str | None
    error: str | None
    importResult: VyralGraphCollectionImportResult
    inspectionResult: VyralGraphCollectionInspectionResult
    doctorResult: VyralGraphDoctorResult

class _RagIngestionJobRequired(TypedDict):
    admission: AdmissionReceipt
    id: str
    kind: Literal['text', 'batch']
    status: Literal['queued', 'running', 'succeeded', 'failed', 'cancelled', 'rejected']
    collection: str
    requestHash: str
    createdAt: str
    cancellationRequested: bool
    requested: int
    attempted: int
    succeeded: int
    failed: int
    progress: float
    textLength: int
    chunkCount: int
    deletedStaleCount: int
    createdCount: int
    updatedCount: int
    reusedCount: int
    vectorGeneratedCount: int
    vectorReusedCount: int
    deduplicatedCount: int

class RagIngestionJob(_RagIngestionJobRequired, total=False):
    startedAt: str | None
    completedAt: str | None
    durationMs: float | None
    currentIndex: int | None
    currentDocumentId: str | None
    currentPartitionKey: str | None
    failureClass: str | None
    error: str | None
    textResult: RagIngestTextResult
    batchResult: RagIngestTextBatchResult

class RagContextGraphEvaluationFailureModes(TypedDict, total=False):
    retrievalMiss: bool
    seedMiss: bool
    graphNotFound: bool
    traversalEmpty: bool
    expectedNodeMissing: bool
    expectedEdgeMissing: bool
    expectedProvenanceMissing: bool
    sourceGroundingFailed: bool
    graphContextTextMissing: bool
    contextTextTruncated: bool
    budgetTruncated: bool
