"""Deterministic local RAG ingestion, context, prompting, and evaluation."""

from .context import (
    CONTEXT_TEXT_FORMAT,
    RagContextService,
    RagPromptService,
)
from .context_models import (
    RagContextAssemblyOptions,
    RagContextChunk,
    RagContextCitation,
    RagContextEnvelope,
    RagContextGraphExpansionOptions,
    RagContextGroupBudget,
    RagContextRequest,
    RagContextRetrievalMatch,
    RagPromptEnvelope,
    RagPromptMessage,
    RagPromptRequest,
    RagPromptTemplateOptions,
)
from .ingestion import RagIngestionService
from .evaluation_models import (
    MAX_EXPECTED_GRAPH_ITEMS,
    MAX_RAG_EVALUATION_CASES,
    RagContextEvaluationCase,
    RagContextEvaluationCaseResult,
    RagContextEvaluationRequest,
    RagContextEvaluationResult,
    RagContextExpectedGraph,
    RagContextGraphEvaluationFailureModes,
    RagContextGraphEvaluationResult,
)
from .models import (
    MAX_RAG_BATCH_ITEMS,
    MAX_RAG_CHUNK_CHARS,
    MAX_RAG_CHUNKS,
    MAX_RAG_TEXT_LENGTH,
    RagIngestActionSummary,
    RagIngestChunkResult,
    RagIngestHashComparison,
    RagIngestStaleDeleteResult,
    RagIngestTextBatchItemResult,
    RagIngestTextBatchRequest,
    RagIngestTextBatchResult,
    RagIngestTextRequest,
    RagIngestTextResult,
    RagIngestionOptions,
)

__all__ = [
    "MAX_RAG_BATCH_ITEMS",
    "MAX_RAG_CHUNK_CHARS",
    "MAX_RAG_CHUNKS",
    "MAX_RAG_TEXT_LENGTH",
    "MAX_EXPECTED_GRAPH_ITEMS",
    "MAX_RAG_EVALUATION_CASES",
    "CONTEXT_TEXT_FORMAT",
    "RagContextAssemblyOptions",
    "RagContextChunk",
    "RagContextCitation",
    "RagContextEnvelope",
    "RagContextEvaluationCase",
    "RagContextEvaluationCaseResult",
    "RagContextEvaluationRequest",
    "RagContextEvaluationResult",
    "RagContextExpectedGraph",
    "RagContextGraphExpansionOptions",
    "RagContextGraphEvaluationFailureModes",
    "RagContextGraphEvaluationResult",
    "RagContextGroupBudget",
    "RagContextRequest",
    "RagContextRetrievalMatch",
    "RagContextService",
    "RagIngestActionSummary",
    "RagIngestChunkResult",
    "RagIngestHashComparison",
    "RagIngestStaleDeleteResult",
    "RagIngestTextBatchItemResult",
    "RagIngestTextBatchRequest",
    "RagIngestTextBatchResult",
    "RagIngestTextRequest",
    "RagIngestTextResult",
    "RagIngestionOptions",
    "RagIngestionService",
    "RagPromptEnvelope",
    "RagPromptMessage",
    "RagPromptRequest",
    "RagPromptService",
    "RagPromptTemplateOptions",
]
